import type { AugmentDefinition } from '../types'

export const AUGMENTS: AugmentDefinition[] = [
  // ── Common (8) ───────────────────────────────────────────────────────────
  {
    id: 'common_cps_30',
    name: 'Melodic Surge',
    description: 'Deine Chimes-Produktion fließt stärker.',
    icon: '🎵',
    rarity: 'common',
    effects: { cpsMultiplier: 1.3 },
  },
  {
    id: 'common_cpc_50',
    name: 'Resonant Strike',
    description: 'Jeder Klick hallt weithin nach.',
    icon: '🔔',
    rarity: 'common',
    effects: { cpcMultiplier: 1.5 },
  },
  {
    id: 'common_power_200',
    name: 'Warrior\'s Beat',
    description: 'Deine Kampfkraft wächst mit jeder Fähigkeitsstufe.',
    icon: '⚔️',
    rarity: 'common',
    effects: { abilityPowerPerLevel: 200 },
  },
  {
    id: 'common_building_cost_15',
    name: 'Frugal Harmony',
    description: 'Gebäude kosten weniger Chimes.',
    icon: '🏛️',
    rarity: 'common',
    effects: { buildingCostMultiplier: 0.85 },
  },
  {
    id: 'common_meep_cost_20',
    name: 'Meep Bargain',
    description: 'Meeps entstehen günstiger.',
    icon: '🐾',
    rarity: 'common',
    effects: { meepCostMultiplier: 0.8 },
  },
  {
    id: 'common_expedition_25',
    name: 'Wanderer\'s Luck',
    description: 'Expeditionen bringen mehr zurück.',
    icon: '🗺️',
    rarity: 'common',
    effects: { expeditionRewardMultiplier: 1.25 },
  },
  {
    id: 'common_cps_cpc_20',
    name: 'Balanced Chord',
    description: 'Passive und aktive Chimes-Gewinnung steigen gleichermaßen.',
    icon: '🎼',
    rarity: 'common',
    effects: { cpsMultiplier: 1.2, cpcMultiplier: 1.2 },
  },
  {
    id: 'common_meep_power_50',
    name: 'Meep Empowerment',
    description: 'Jeder Meep leistet mehr im Kampf.',
    icon: '💪',
    rarity: 'common',
    effects: { meepPowerMultiplier: 1.5 },
  },

  // ── Rare (6) ─────────────────────────────────────────────────────────────
  {
    id: 'rare_cps_70',
    name: 'Harmonic Cascade',
    description: 'Ein mächtiger Strom von Chimes ergießt sich jede Sekunde.',
    icon: '🌊',
    rarity: 'rare',
    effects: { cpsMultiplier: 1.7 },
  },
  {
    id: 'rare_cpc_100',
    name: 'Thunder Chime',
    description: 'Deine Klicks treffen wie Blitze.',
    icon: '⚡',
    rarity: 'rare',
    effects: { cpcMultiplier: 2.0 },
  },
  {
    id: 'rare_power_500',
    name: 'Battle Hymn',
    description: 'Jede Fähigkeitsstufe verleiht deutlich mehr Kampfkraft.',
    icon: '🛡️',
    rarity: 'rare',
    effects: { abilityPowerPerLevel: 500 },
  },
  {
    id: 'rare_building_cost_30',
    name: 'Master Builder',
    description: 'Gebäude kosten spürbar weniger Chimes.',
    icon: '🔨',
    rarity: 'rare',
    effects: { buildingCostMultiplier: 0.7 },
  },
  {
    id: 'rare_expedition_50',
    name: 'Fortune\'s Compass',
    description: 'Expeditionen kehren mit halber Beute mehr zurück.',
    icon: '🧭',
    rarity: 'rare',
    effects: { expeditionRewardMultiplier: 1.5 },
  },
  {
    id: 'rare_cps_power',
    name: 'Combat Rhythm',
    description: 'Passive Produktion und Kampfkraft steigen gemeinsam.',
    icon: '🥁',
    rarity: 'rare',
    effects: { cpsMultiplier: 1.4, abilityPowerPerLevel: 300 },
  },

  // ── Epic (4) ─────────────────────────────────────────────────────────────
  {
    id: 'epic_cps_150',
    name: 'Eternal Melody',
    description: 'Die Chimes fließen ohne Ende — eine ewige Komposition.',
    icon: '🌟',
    rarity: 'epic',
    effects: { cpsMultiplier: 2.5 },
  },
  {
    id: 'epic_cpc_200',
    name: 'Cosmic Click',
    description: 'Jeder Klick erschüttert das Universum.',
    icon: '💫',
    rarity: 'epic',
    effects: { cpcMultiplier: 3.0 },
  },
  {
    id: 'epic_power_1000',
    name: 'Warlord\'s Anthem',
    description: 'Deine Fähigkeiten entfalten ein gewaltiges Kampfpotenzial.',
    icon: '👑',
    rarity: 'epic',
    effects: { abilityPowerPerLevel: 1000 },
  },
  {
    id: 'epic_cps_cpc_80',
    name: 'Grand Crescendo',
    description: 'Alle Chimes-Quellen erreichen ihren absoluten Höhepunkt.',
    icon: '🎆',
    rarity: 'epic',
    effects: { cpsMultiplier: 1.8, cpcMultiplier: 1.8 },
  },
]
