import type { AugmentDefinition, AugmentRarity } from '../types'

export const RARITY_WEIGHTS: Record<AugmentRarity, number> = {
  common: 60,
  rare: 25,
  epic: 12,
  legendary: 3,
}

export const AUGMENTS: AugmentDefinition[] = [
  // ── Common ──────────────────────────────────────────────────────────────────
  {
    id: 'common_cps_30',
    name: 'Melodic Surge',
    description: 'Deine Chimes-Produktion fließt stärker.',
    effectLine: '+30% CPS',
    icon: '🎵',
    rarity: 'common',
    effects: { cpsMultiplier: 1.3 },
  },
  {
    id: 'common_cpc_50',
    name: 'Resonant Strike',
    description: 'Jeder Klick hallt weithin nach.',
    effectLine: '+50% CPC',
    icon: '🔔',
    rarity: 'common',
    effects: { cpcMultiplier: 1.5 },
  },
  {
    id: 'common_power_200',
    name: "Warrior's Beat",
    description: 'Deine Kampfkraft wächst mit jeder Fähigkeitsstufe.',
    effectLine: '+200 Power pro Fähigkeitsstufe',
    icon: '⚔️',
    rarity: 'common',
    effects: { abilityPowerPerLevel: 200 },
  },
  {
    id: 'common_building_cost_15',
    name: 'Frugal Harmony',
    description: 'Gebäude kosten weniger Chimes.',
    effectLine: '-15% Gebäudekosten',
    icon: '🏛️',
    rarity: 'common',
    effects: { buildingCostMultiplier: 0.85 },
  },
  {
    id: 'common_meep_cost_20',
    name: 'Meep Bargain',
    description: 'Meeps entstehen günstiger.',
    effectLine: '-20% Meep-Kosten',
    icon: '🐾',
    rarity: 'common',
    effects: { meepCostMultiplier: 0.8 },
  },
  {
    id: 'common_expedition_25',
    name: "Wanderer's Luck",
    description: 'Expeditionen bringen mehr zurück.',
    effectLine: '+25% Expeditions-Belohnung',
    icon: '🗺️',
    rarity: 'common',
    effects: { expeditionRewardMultiplier: 1.25 },
  },
  {
    id: 'common_cps_cpc_20',
    name: 'Balanced Chord',
    description: 'Passive und aktive Chimes-Gewinnung steigen gleichermaßen.',
    effectLine: '+20% CPS & CPC',
    icon: '🎼',
    rarity: 'common',
    effects: { cpsMultiplier: 1.2, cpcMultiplier: 1.2 },
  },
  {
    id: 'common_meep_power_50',
    name: 'Meep Empowerment',
    description: 'Jeder Meep leistet mehr im Kampf.',
    effectLine: '+50% Meep-Power',
    icon: '💪',
    rarity: 'common',
    effects: { meepPowerMultiplier: 1.5 },
  },
  {
    id: 'common_caffeine_rush',
    name: 'Caffeine Rush',
    description: 'Ein Koffeinschub beschleunigt die Produktion.',
    effectLine: '+10% CPS',
    icon: '☕',
    rarity: 'common',
    effects: { cpsMultiplier: 1.1 },
  },
  {
    id: 'common_steady_hands',
    name: 'Steady Hands',
    description: 'Ruhige Hände treffen besser.',
    effectLine: '+5% CPC',
    icon: '🤲',
    rarity: 'common',
    effects: { cpcMultiplier: 1.05 },
  },
  {
    id: 'common_lucky_penny',
    name: 'Lucky Penny',
    description: 'Ein Glückspfennig bringt mehr aus Expeditionen.',
    effectLine: '+8% Expeditions-Belohnung',
    icon: '🪙',
    rarity: 'common',
    effects: { expeditionRewardMultiplier: 1.08 },
  },

  // ── Rare ────────────────────────────────────────────────────────────────────
  {
    id: 'rare_cps_70',
    name: 'Harmonic Cascade',
    description: 'Ein mächtiger Strom von Chimes ergießt sich jede Sekunde.',
    effectLine: '+70% CPS',
    icon: '🌊',
    rarity: 'rare',
    effects: { cpsMultiplier: 1.7 },
  },
  {
    id: 'rare_cpc_100',
    name: 'Thunder Chime',
    description: 'Deine Klicks treffen wie Blitze.',
    effectLine: '+100% CPC',
    icon: '⚡',
    rarity: 'rare',
    effects: { cpcMultiplier: 2.0 },
  },
  {
    id: 'rare_power_500',
    name: 'Battle Hymn',
    description: 'Jede Fähigkeitsstufe verleiht deutlich mehr Kampfkraft.',
    effectLine: '+500 Power pro Fähigkeitsstufe',
    icon: '🛡️',
    rarity: 'rare',
    effects: { abilityPowerPerLevel: 500 },
  },
  {
    id: 'rare_building_cost_30',
    name: 'Master Builder',
    description: 'Gebäude kosten spürbar weniger Chimes.',
    effectLine: '-30% Gebäudekosten',
    icon: '🔨',
    rarity: 'rare',
    effects: { buildingCostMultiplier: 0.7 },
  },
  {
    id: 'rare_expedition_50',
    name: "Fortune's Compass",
    description: 'Expeditionen kehren mit halber Beute mehr zurück.',
    effectLine: '+50% Expeditions-Belohnung',
    icon: '🧭',
    rarity: 'rare',
    effects: { expeditionRewardMultiplier: 1.5 },
  },
  {
    id: 'rare_cps_power',
    name: 'Combat Rhythm',
    description: 'Passive Produktion und Kampfkraft steigen gemeinsam.',
    effectLine: '+40% CPS & +300 Power/Level',
    icon: '🥁',
    rarity: 'rare',
    effects: { cpsMultiplier: 1.4, abilityPowerPerLevel: 300 },
  },
  {
    id: 'rare_double_tap',
    name: 'Double Tap',
    description: 'Jeder 10. Klick zählt doppelt.',
    effectLine: 'Jeder 10. Klick zählt doppelt',
    icon: '✌️',
    rarity: 'rare',
    effects: {},
    specialEffect: { type: 'doubleTap', params: { interval: 10, multiplier: 2 } },
  },
  {
    id: 'rare_coin_magnet',
    name: 'Coin Magnet',
    description: 'Zieht automatisch Chimes aus der Nähe an.',
    effectLine: '+15% CPS (Passive Income)',
    icon: '🧲',
    rarity: 'rare',
    effects: { cpsMultiplier: 1.15 },
  },
  {
    id: 'rare_overclock',
    name: 'Overclock',
    description: 'CPS verdoppelt sich für 30s nach jedem Level-Aufstieg.',
    effectLine: 'CPS x2 für 30s nach Level-Up',
    icon: '⏱️',
    rarity: 'rare',
    effects: {},
    specialEffect: { type: 'overclock', params: { duration: 30000, multiplier: 2 } },
  },

  // ── Epic ────────────────────────────────────────────────────────────────────
  {
    id: 'epic_cps_150',
    name: 'Eternal Melody',
    description: 'Die Chimes fließen ohne Ende — eine ewige Komposition.',
    effectLine: '+150% CPS',
    icon: '🌟',
    rarity: 'epic',
    effects: { cpsMultiplier: 2.5 },
  },
  {
    id: 'epic_cpc_200',
    name: 'Cosmic Click',
    description: 'Jeder Klick erschüttert das Universum.',
    effectLine: '+200% CPC',
    icon: '💫',
    rarity: 'epic',
    effects: { cpcMultiplier: 3.0 },
  },
  {
    id: 'epic_power_1000',
    name: "Warlord's Anthem",
    description: 'Deine Fähigkeiten entfalten ein gewaltiges Kampfpotenzial.',
    effectLine: '+1000 Power pro Fähigkeitsstufe',
    icon: '👑',
    rarity: 'epic',
    effects: { abilityPowerPerLevel: 1000 },
  },
  {
    id: 'epic_cps_cpc_80',
    name: 'Grand Crescendo',
    description: 'Alle Chimes-Quellen erreichen ihren absoluten Höhepunkt.',
    effectLine: '+80% CPS & CPC',
    icon: '🎆',
    rarity: 'epic',
    effects: { cpsMultiplier: 1.8, cpcMultiplier: 1.8 },
  },
  {
    id: 'epic_time_warp',
    name: 'Time Warp',
    description: 'Die Zeit biegt sich — alle Cooldowns halbiert.',
    effectLine: 'Alle Cooldowns halbiert',
    icon: '⏳',
    rarity: 'epic',
    effects: { cooldownMultiplier: 0.5 },
  },
  {
    id: 'epic_chain_reaction',
    name: 'Chain Reaction',
    description: 'Klicks haben eine Chance, einen Kettenklick auszulösen.',
    effectLine: '20% Chance auf Bonus-Klick',
    icon: '💥',
    rarity: 'epic',
    effects: {},
    specialEffect: { type: 'chainReaction', params: { chance: 0.2 } },
  },
  {
    id: 'epic_void_drain',
    name: 'Void Drain',
    description: 'Die Leere zehrt an der Kraft deiner Gegner.',
    effectLine: 'Feinde verlieren 2% HP/s im Kampf',
    icon: '🕳️',
    rarity: 'epic',
    effects: { enemyMaxHPDrainPerSecond: 0.02 },
  },

  // ── Legendary ───────────────────────────────────────────────────────────────
  {
    id: 'legendary_big_bang',
    name: 'Big Bang',
    description: 'Einmaliger kosmischer Schlag gegen alle Feinde.',
    effectLine: 'Einmaliger 5x Power-Boost im Kampf',
    icon: '🌌',
    rarity: 'legendary',
    effects: {},
    specialEffect: { type: 'bigBang', params: { multiplier: 5 } },
  },
  {
    id: 'legendary_chronostasis',
    name: 'Chronostasis',
    description: 'Die Zeit verlangsamt sich für Gegner.',
    effectLine: 'Gegner 50% langsamer im Kampf',
    icon: '🕰️',
    rarity: 'legendary',
    effects: { enemySpeedMultiplier: 0.5 },
  },
  {
    id: 'legendary_infinite_loop',
    name: 'Infinite Loop',
    description: 'Jeder 50. Klick wiederholt die letzten 5 Klicks.',
    effectLine: 'Jeder 50. Klick wiederholt 5 Klicks',
    icon: '♾️',
    rarity: 'legendary',
    effects: {},
    specialEffect: { type: 'infiniteLoop', params: { interval: 50, replayCount: 5 } },
  },

  // ── Wildcard ────────────────────────────────────────────────────────────────
  {
    id: 'epic_gravity_flip',
    name: 'Gravity Flip',
    description: 'Die Schwerkraft dreht sich kurz um — danach fließen Chimes schneller.',
    effectLine: '+20% CPS + visueller Gag',
    icon: '🙃',
    rarity: 'epic',
    effects: { cpsMultiplier: 1.2 },
    specialEffect: { type: 'gravityFlip', params: {} },
  },
  {
    id: 'rare_bards_curse',
    name: "Bard's Curse",
    description: 'Weniger passive Chimes, dafür mächtigere Klicks.',
    effectLine: '-5% CPS, aber +50% CPC',
    icon: '🎭',
    rarity: 'rare',
    effects: { cpsMultiplier: 0.95, cpcMultiplier: 1.5 },
  },
  {
    id: 'legendary_quantum_luck',
    name: 'Quantum Luck',
    description: 'Jeder Bonus-Effekt hat eine Chance, verdoppelt oder annulliert zu werden.',
    effectLine: '10% Chance: Bonus x2 oder x0',
    icon: '🎲',
    rarity: 'legendary',
    effects: {},
    specialEffect: { type: 'quantumLuck', params: { chance: 0.1 } },
  },
  {
    id: 'epic_echo_chamber',
    name: 'Echo Chamber',
    description: 'Der letzte gewählte Augment-Effekt hallt 60s nach.',
    effectLine: 'Letztes Augment nochmal aktiv (60s)',
    icon: '🔊',
    rarity: 'epic',
    effects: {},
    specialEffect: { type: 'echoChamber', params: { duration: 60000 } },
  },
  {
    id: 'rare_keyboard_smash',
    name: 'Keyboard Smash',
    description: 'Zufällige Boni und Mali auf alle Stats.',
    effectLine: 'Random -5% bis +50% auf alle Stats',
    icon: '⌨️',
    rarity: 'rare',
    effects: {},
    specialEffect: { type: 'keyboardSmash', params: { min: -0.05, max: 0.5 } },
  },
]
