import type { AugmentDefinition, AugmentRarity } from '../types'

export const RARITY_WEIGHTS: Record<AugmentRarity, number> = {
  common: 60,
  rare: 25,
  epic: 12,
  legendary: 3,
}

export const AUGMENTS: AugmentDefinition[] = [
  // ── Common ──────────────────────────────────────────────────────────────────
  {
    id: 'common_cps_30',
    name: 'Melodic Surge',
    description: 'Your Chimes production flows stronger.',
    effectLine: '+30% CPS',
    icon: 'game-icons:harp',
    image: '/img/augments/augment1.png',
    rarity: 'common',
    effects: { cpsMultiplier: 1.3 },
  },
  {
    id: 'common_cpc_50',
    name: 'Resonant Strike',
    description: 'Every click echoes far and wide.',
    effectLine: '+50% CPC',
    icon: 'game-icons:bell',
    image: '/img/augments/augment2.png',
    rarity: 'common',
    effects: { cpcMultiplier: 1.5 },
  },
  {
    id: 'common_power_200',
    name: "Warrior's Beat",
    description: 'Your combat power grows with every ability level.',
    effectLine: '+200 Power per Ability Level',
    icon: 'game-icons:sword-in-stone',
    rarity: 'common',
    effects: { abilityPowerPerLevel: 200 },
  },
  {
    id: 'common_building_cost_15',
    name: 'Frugal Harmony',
    description: 'Buildings cost fewer Chimes.',
    effectLine: '-15% Building Costs',
    icon: 'game-icons:temple',
    image: '/img/augments/augment3.png',
    rarity: 'common',
    effects: { buildingCostMultiplier: 0.85 },
  },
  {
    id: 'common_meep_cost_20',
    name: 'Meep Bargain',
    description: 'Meeps are cheaper to create.',
    effectLine: '-20% Meep Costs',
    icon: 'game-icons:paw-print',
    rarity: 'common',
    effects: { meepCostMultiplier: 0.8 },
  },
  {
    id: 'common_expedition_25',
    name: "Wanderer's Luck",
    description: 'Expeditions bring back more.',
    effectLine: '+25% Expedition Reward',
    icon: 'game-icons:path-distance',
    rarity: 'common',
    effects: { expeditionRewardMultiplier: 1.25 },
  },
  {
    id: 'common_cps_cpc_20',
    name: 'Balanced Chord',
    description: 'Passive and active Chimes gain rise equally.',
    effectLine: '+20% CPS & CPC',
    icon: 'game-icons:music-spell',
    rarity: 'common',
    effects: { cpsMultiplier: 1.2, cpcMultiplier: 1.2 },
  },
  {
    id: 'common_meep_power_50',
    name: 'Meep Empowerment',
    description: 'Every Meep performs better in combat.',
    effectLine: '+50% Meep Power',
    icon: 'game-icons:biceps',
    rarity: 'common',
    effects: { meepPowerMultiplier: 1.5 },
  },
  {
    id: 'common_caffeine_rush',
    name: 'Caffeine Rush',
    description: 'A caffeine rush accelerates production.',
    effectLine: '+10% CPS',
    icon: 'game-icons:hot-beverage',
    rarity: 'common',
    effects: { cpsMultiplier: 1.1 },
  },
  {
    id: 'common_steady_hands',
    name: 'Steady Hands',
    description: 'Steady hands aim better.',
    effectLine: '+5% CPC',
    icon: 'game-icons:open-palm',
    rarity: 'common',
    effects: { cpcMultiplier: 1.05 },
  },
  {
    id: 'common_lucky_penny',
    name: 'Lucky Penny',
    description: 'A lucky coin brings more from expeditions.',
    effectLine: '+8% Expedition Reward',
    icon: 'game-icons:gold-coin',
    rarity: 'common',
    effects: { expeditionRewardMultiplier: 1.08 },
  },

  // ── Rare ────────────────────────────────────────────────────────────────────
  {
    id: 'rare_cps_70',
    name: 'Harmonic Cascade',
    description: 'A mighty torrent of Chimes pours forth every second.',
    effectLine: '+70% CPS',
    icon: 'game-icons:tidal-wave',
    image: '/img/augments/augment4.png',
    rarity: 'rare',
    effects: { cpsMultiplier: 1.7 },
  },
  {
    id: 'rare_cpc_100',
    name: 'Thunder Chime',
    description: 'Your clicks strike like lightning.',
    effectLine: '+100% CPC',
    icon: 'game-icons:lightning-arc',
    image: '/img/augments/augment5.png',
    rarity: 'rare',
    effects: { cpcMultiplier: 2.0 },
  },
  {
    id: 'rare_power_500',
    name: 'Battle Hymn',
    description: 'Each ability level grants noticeably more combat power.',
    effectLine: '+500 Power per Ability Level',
    icon: 'game-icons:kite-shield',
    image: '/img/roles/top.png',
    rarity: 'rare',
    effects: { abilityPowerPerLevel: 500 },
  },
  {
    id: 'rare_building_cost_30',
    name: 'Master Builder',
    description: 'Buildings cost noticeably fewer Chimes.',
    effectLine: '-30% Building Costs',
    icon: 'game-icons:hammer',
    rarity: 'rare',
    effects: { buildingCostMultiplier: 0.7 },
  },
  {
    id: 'rare_expedition_50',
    name: "Fortune's Compass",
    description: 'Expeditions return with even greater spoils.',
    effectLine: '+50% Expedition Reward',
    icon: 'game-icons:compass',
    rarity: 'rare',
    effects: { expeditionRewardMultiplier: 1.5 },
  },
  {
    id: 'rare_cps_power',
    name: 'Combat Rhythm',
    description: 'Passive production and combat power rise together.',
    effectLine: '+40% CPS & +300 Power/Level',
    icon: 'game-icons:drum',
    rarity: 'rare',
    effects: { cpsMultiplier: 1.4, abilityPowerPerLevel: 300 },
  },
  {
    id: 'rare_double_tap',
    name: 'Double Tap',
    description: 'Every 10th click counts twice.',
    effectLine: 'Every 10th Click Counts Twice',
    icon: '✌️',
    image: '/img/augments/augment6.png',
    rarity: 'rare',
    effects: {},
    specialEffect: { type: 'doubleTap', params: { interval: 10, multiplier: 2 } },
  },
  {
    id: 'rare_coin_magnet',
    name: 'Coin Magnet',
    description: 'Automatically draws in nearby Chimes.',
    effectLine: '+15% CPS (Passive Income)',
    icon: 'game-icons:horseshoe',
    rarity: 'rare',
    effects: { cpsMultiplier: 1.15 },
  },
  {
    id: 'rare_overclock',
    name: 'Overclock',
    description: 'CPS doubles for 30s after each level-up.',
    effectLine: 'CPS x2 for 30s after Level-Up',
    icon: 'game-icons:pocket-watch',
    rarity: 'rare',
    effects: {},
    specialEffect: { type: 'overclock', params: { duration: 30000, multiplier: 2 } },
  },

  // ── Epic ────────────────────────────────────────────────────────────────────
  {
    id: 'epic_cps_150',
    name: 'Eternal Melody',
    description: 'Chimes flow endlessly — an eternal composition.',
    effectLine: '+150% CPS',
    icon: 'game-icons:bright-explosion',
    image: '/img/augments/augment7.png',
    rarity: 'epic',
    effects: { cpsMultiplier: 2.5 },
  },
  {
    id: 'epic_cpc_200',
    name: 'Cosmic Click',
    description: 'Every click shakes the universe.',
    effectLine: '+200% CPC',
    icon: 'game-icons:planet-conquest',
    rarity: 'epic',
    effects: { cpcMultiplier: 3.0 },
  },
  {
    id: 'epic_power_1000',
    name: "Warlord's Anthem",
    description: 'Your abilities unleash tremendous combat potential.',
    effectLine: '+1000 Power per Ability Level',
    icon: 'game-icons:royal-crown',
    rarity: 'epic',
    effects: { abilityPowerPerLevel: 1000 },
  },
  {
    id: 'epic_cps_cpc_80',
    name: 'Grand Crescendo',
    description: 'All Chimes sources reach their absolute peak.',
    effectLine: '+80% CPS & CPC',
    icon: 'game-icons:fireworks',
    rarity: 'epic',
    effects: { cpsMultiplier: 1.8, cpcMultiplier: 1.8 },
  },
  {
    id: 'epic_time_warp',
    name: 'Time Warp',
    description: 'Time bends — all cooldowns halved.',
    effectLine: 'All Cooldowns Halved',
    icon: 'game-icons:time-trap',
    rarity: 'epic',
    effects: { cooldownMultiplier: 0.5 },
  },
  {
    id: 'epic_chain_reaction',
    name: 'Chain Reaction',
    description: 'Clicks have a chance to trigger a chain click.',
    effectLine: '20% Chance for Bonus Click',
    icon: 'game-icons:explosion',
    image: '/img/augments/augment8.png',
    rarity: 'epic',
    effects: {},
    specialEffect: { type: 'chainReaction', params: { chance: 0.2 } },
  },
  {
    id: 'epic_void_drain',
    name: 'Void Drain',
    description: "The void gnaws at your enemies' power.",
    effectLine: 'Enemies lose 2% HP/s in combat',
    icon: 'game-icons:void',
    rarity: 'epic',
    effects: { enemyMaxHPDrainPerSecond: 0.02 },
  },

  // ── Legendary ───────────────────────────────────────────────────────────────
  {
    id: 'legendary_big_bang',
    name: 'Big Bang',
    description: 'One-time cosmic strike against all enemies.',
    effectLine: 'One-time 5x Power Boost in combat',
    icon: 'game-icons:comet',
    image: '/img/augments/augment9.png',
    rarity: 'legendary',
    effects: {},
    specialEffect: { type: 'bigBang', params: { multiplier: 5 } },
  },
  {
    id: 'legendary_chronostasis',
    name: 'Chronostasis',
    description: 'Time slows for enemies.',
    effectLine: 'Enemies 50% slower in combat',
    icon: 'game-icons:ancient-ruins',
    rarity: 'legendary',
    effects: { enemySpeedMultiplier: 0.5 },
  },
  {
    id: 'legendary_infinite_loop',
    name: 'Infinite Loop',
    description: 'Every 50th click replays the last 5 clicks.',
    effectLine: 'Every 50th Click Replays 5 Clicks',
    icon: 'game-icons:infinity',
    image: '/img/augments/augment10.png',
    rarity: 'legendary',
    effects: {},
    specialEffect: { type: 'infiniteLoop', params: { interval: 50, replayCount: 5 } },
  },

  // ── Wildcard ────────────────────────────────────────────────────────────────
  {
    id: 'epic_gravity_flip',
    name: 'Gravity Flip',
    description: 'Gravity briefly flips — Chimes flow faster afterward.',
    effectLine: '+20% CPS + visual gag',
    icon: 'game-icons:gravity',
    rarity: 'epic',
    effects: { cpsMultiplier: 1.2 },
    specialEffect: { type: 'gravityFlip', params: {} },
  },
  {
    id: 'rare_bards_curse',
    name: "Bard's Curse",
    description: 'Less passive Chimes, but more powerful clicks.',
    effectLine: '-5% CPS, but +50% CPC',
    icon: 'game-icons:jester-hat',
    rarity: 'rare',
    effects: { cpsMultiplier: 0.95, cpcMultiplier: 1.5 },
  },
  {
    id: 'legendary_quantum_luck',
    name: 'Quantum Luck',
    description: 'Every bonus effect has a chance to be doubled or nullified.',
    effectLine: '10% Chance: Bonus x2 or x0',
    icon: 'game-icons:dice-six-faces-random',
    rarity: 'legendary',
    effects: {},
    specialEffect: { type: 'quantumLuck', params: { chance: 0.1 } },
  },
  {
    id: 'epic_echo_chamber',
    name: 'Echo Chamber',
    description: 'The last chosen Augment effect echoes for 60s.',
    effectLine: 'Last Augment active again (60s)',
    icon: 'game-icons:loudspeaker',
    rarity: 'epic',
    effects: {},
    specialEffect: { type: 'echoChamber', params: { duration: 60000 } },
  },
  {
    id: 'rare_keyboard_smash',
    name: 'Keyboard Smash',
    description: 'Random bonuses and penalties to all stats.',
    effectLine: 'Random -5% to +50% on all stats',
    icon: 'game-icons:keyboard',
    rarity: 'rare',
    effects: {},
    specialEffect: { type: 'keyboardSmash', params: { min: -0.05, max: 0.5 } },
  },
]

// The 10 image augments form the pool for the level-up selection
export const AUGMENT_POOL: AugmentDefinition[] = AUGMENTS.filter((a) => !!a.image)
