import type {
  ChampionRole,
  ChampionOrigin,
  TraitId,
  PlanetType,
  ChampionTierId,
} from '../types'

export interface ChampionDef {
  role: ChampionRole
  origin: ChampionOrigin
  traits: TraitId[]
  planetType: PlanetType
  materialCost: Record<string, number>
  // Champion Tier — the single tier per champion (Galaxy/Champion Tier system).
  // Maps to a star level (★1..★12) via CHAMPION_TIERS in championTiers.ts and drives the
  // Shop/Select tier grouping, the ★N card badge, the recruit cost (getChampionChimesPrice)
  // and which galaxy the champion spawns in.
  championTier: ChampionTierId
  // Number of skin splash images for this champion — equals the file count in
  // public/img/skins/<ChampionPascalCase>/. 0 = no skins bundled.
  skinCount: number
}

export const CHAMPION_DATA: Record<string, ChampionDef> = {
  // ── Rocky ──────────────────────────────────────────────────────────────────
  Malphite:         { role: 'top',     origin: 'Ixtal',         traits: ['guardian'],                     planetType: 'rocky',     materialCost: { nebula_quartz: 3 },                        championTier: 'lone_wanderer', skinCount: 10 },
  Taliyah:          { role: 'mid',     origin: 'Shurima',       traits: ['celestial', 'invoker'],         planetType: 'rocky',     materialCost: { nebula_quartz: 2, stardust: 1 },           championTier: 'void_sovereign', skinCount: 3 },
  Galio:            { role: 'mid',     origin: 'Demacia',       traits: ['guardian'],                     planetType: 'rocky',     materialCost: { nebula_quartz: 2, moon_crystal: 1 },       championTier: 'lone_wanderer', skinCount: 7 },
  Skarner:          { role: 'jungle',  origin: 'Shurima',       traits: ['dark_star'],                    planetType: 'rocky',     materialCost: { nebula_quartz: 2, stardust: 2 },           championTier: 'void_sovereign', skinCount: 4 },
  Rammus:           { role: 'jungle',  origin: 'Shurima',       traits: ['guardian'],                     planetType: 'rocky',     materialCost: { nebula_quartz: 2 },                        championTier: 'lone_wanderer', skinCount: 9 },
  Ornn:             { role: 'top',     origin: 'Freljord',  traits: ['guardian', 'jade'],             planetType: 'rocky',     materialCost: { nebula_quartz: 3, solar_essence: 1 },      championTier: 'void_sovereign', skinCount: 3 },
  Sion:             { role: 'top',     origin: 'Noxus',         traits: ['dark_star'],                    planetType: 'rocky',     materialCost: { nebula_quartz: 2, stardust: 1 },           championTier: 'rift_keeper', skinCount: 8 },
  Poppy:            { role: 'top',     origin: 'Demacia',       traits: ['guardian', 'jade'],             planetType: 'rocky',     materialCost: { nebula_quartz: 1, stardust: 2 },           championTier: 'lone_wanderer', skinCount: 10 },
  Gnar:             { role: 'top',     origin: 'Bandle',   traits: ['elderwood'],                    planetType: 'rocky',     materialCost: { nebula_quartz: 2, moon_crystal: 1 },       championTier: 'astral_warden', skinCount: 6 },
  Urgot:            { role: 'top',     origin: 'Zaun',          traits: ['challenger', 'reaper'],         planetType: 'rocky',     materialCost: { nebula_quartz: 2, solar_essence: 1 },      championTier: 'nebula_sage', skinCount: 5 },
  Yorick:           { role: 'top',     origin: 'Isles',  traits: ['phantom', 'reaper'],            planetType: 'rocky',     materialCost: { nebula_quartz: 2, void_shard: 1 },         championTier: 'astral_warden', skinCount: 6 },
  Darius:           { role: 'top',     origin: 'Noxus',         traits: ['challenger'],                   planetType: 'rocky',     materialCost: { nebula_quartz: 2, stardust: 1 },           championTier: 'lone_wanderer', skinCount: 5 },
  Garen:            { role: 'top',     origin: 'Demacia',       traits: ['jade'],                         planetType: 'rocky',     materialCost: { nebula_quartz: 1, stardust: 2 },           championTier: 'lone_wanderer', skinCount: 12 },
  Pantheon:         { role: 'support', origin: 'Targon',        traits: ['jade'],                         planetType: 'rocky',     materialCost: { nebula_quartz: 2, solar_essence: 1 },      championTier: 'rift_keeper', skinCount: 10 },
  Sett:             { role: 'top',     origin: 'Ionia',         traits: ['challenger'],                   planetType: 'rocky',     materialCost: { nebula_quartz: 2, stardust: 1 },           championTier: 'rift_keeper', skinCount: 7 },
  Rell:             { role: 'support', origin: 'Noxus',         traits: ['guardian', 'jade'],             planetType: 'rocky',     materialCost: { nebula_quartz: 2, moon_crystal: 1 },       championTier: 'cosmic_sovereign', skinCount: 3 },
  Trundle:          { role: 'jungle',  origin: 'Freljord',  traits: ['elderwood'],                    planetType: 'rocky',     materialCost: { nebula_quartz: 2, stardust: 1 },           championTier: 'astral_warden', skinCount: 5 },
  Volibear:         { role: 'top',     origin: 'Freljord',  traits: ['elderwood'],                    planetType: 'rocky',     materialCost: { nebula_quartz: 2, solar_essence: 1 },      championTier: 'rift_keeper', skinCount: 7 },
  Olaf:             { role: 'jungle',  origin: 'Freljord',  traits: ['challenger'],                   planetType: 'rocky',     materialCost: { nebula_quartz: 2, stardust: 1 },           championTier: 'nebula_sage', skinCount: 4 },
  Wukong:           { role: 'top',     origin: 'Ionia',         traits: ['duelist', 'jade'],              planetType: 'rocky',     materialCost: { nebula_quartz: 1, stardust: 2 },           championTier: 'nebula_sage', skinCount: 8 },
  Alistar:          { role: 'support', origin: 'Noxus',         traits: ['guardian'],                     planetType: 'rocky',     materialCost: { nebula_quartz: 2, stardust: 1 },           championTier: 'lone_wanderer', skinCount: 9 },
  Amumu:            { role: 'jungle',  origin: 'Shurima',       traits: ['phantom', 'elderwood'],         planetType: 'rocky',     materialCost: { nebula_quartz: 1, moon_crystal: 2 },       championTier: 'lone_wanderer', skinCount: 12 },

  // ── Ice ─────────────────────────────────────────────────────────────────────
  Lissandra:        { role: 'mid',     origin: 'Freljord',  traits: ['arcanist'],                     planetType: 'ice',       materialCost: { moon_crystal: 3 },                         championTier: 'astral_warden', skinCount: 9 },
  Anivia:           { role: 'mid',     origin: 'Freljord',  traits: ['elderwood'],                    planetType: 'ice',       materialCost: { moon_crystal: 2, nebula_quartz: 1 },       championTier: 'lone_wanderer', skinCount: 8 },
  'Nunu A. Willump':{ role: 'jungle',  origin: 'Freljord',  traits: ['moonlight', 'elderwood'],       planetType: 'ice',       materialCost: { moon_crystal: 2, stardust: 1 },            championTier: 'lone_wanderer', skinCount: 9 },
  Sejuani:          { role: 'jungle',  origin: 'Freljord',  traits: ['challenger', 'moonlight'],      planetType: 'ice',       materialCost: { moon_crystal: 2, nebula_quartz: 1 },       championTier: 'lone_wanderer', skinCount: 10 },
  Braum:            { role: 'support', origin: 'Freljord',  traits: ['guardian', 'jade'],             planetType: 'ice',       materialCost: { moon_crystal: 2, stardust: 1 },            championTier: 'nebula_sage', skinCount: 4 },
  Ashe:             { role: 'adc',     origin: 'Freljord',  traits: ['moonlight'],                    planetType: 'ice',       materialCost: { moon_crystal: 2, stardust: 1 },            championTier: 'lone_wanderer', skinCount: 10 },
  Tryndamere:       { role: 'top',     origin: 'Freljord',  traits: ['duelist', 'challenger'],        planetType: 'ice',       materialCost: { moon_crystal: 2, solar_essence: 1 },       championTier: 'rift_keeper', skinCount: 10 },
  Udyr:             { role: 'jungle',  origin: 'Freljord',  traits: ['elderwood'],                    planetType: 'ice',       materialCost: { moon_crystal: 2, nebula_quartz: 1 },       championTier: 'rift_keeper', skinCount: 9 },
  Gragas:           { role: 'jungle',  origin: 'Freljord',  traits: ['challenger'],                   planetType: 'ice',       materialCost: { moon_crystal: 2, stardust: 1 },            championTier: 'rift_keeper', skinCount: 12 },
  Vex:              { role: 'mid',     origin: 'Bandle',   traits: ['arcanist'],                     planetType: 'ice',       materialCost: { moon_crystal: 2, void_shard: 1 },          championTier: 'nebula_sage', skinCount: 3 },
  Aurora:           { role: 'mid',     origin: 'Bandle',   traits: ['celestial', 'moonlight'],       planetType: 'ice',       materialCost: { moon_crystal: 3, stardust: 1 },            championTier: 'void_sovereign', skinCount: 0 },
  Lillia:           { role: 'jungle',  origin: 'Ionia',         traits: ['elderwood'],                    planetType: 'ice',       materialCost: { moon_crystal: 2, stardust: 1 },            championTier: 'void_sovereign', skinCount: 2 },
  Quinn:            { role: 'top',     origin: 'Demacia',       traits: ['elderwood'],                    planetType: 'ice',       materialCost: { moon_crystal: 1, stardust: 2 },            championTier: 'void_sovereign', skinCount: 5 },
  Kennen:           { role: 'top',     origin: 'Ionia',         traits: ['astral'],                       planetType: 'ice',       materialCost: { moon_crystal: 2, solar_essence: 1 },       championTier: 'void_sovereign', skinCount: 7 },
  Shen:             { role: 'top',     origin: 'Ionia',         traits: ['guardian'],                     planetType: 'ice',       materialCost: { moon_crystal: 2, stardust: 1 },            championTier: 'nebula_sage', skinCount: 8 },
  Janna:            { role: 'support', origin: 'Zaun',          traits: ['celestial', 'enchanter'],       planetType: 'ice',       materialCost: { moon_crystal: 2, stardust: 1 },            championTier: 'rift_keeper', skinCount: 13 },
  Taric:            { role: 'support', origin: 'Targon',        traits: ['enchanter', 'jade'],            planetType: 'ice',       materialCost: { moon_crystal: 3, nebula_quartz: 1 },       championTier: 'rift_keeper', skinCount: 6 },

  // ── Gas Giant ───────────────────────────────────────────────────────────────
  'Aurelion Sol':   { role: 'mid',     origin: 'Targon',        traits: ['celestial', 'astral'],          planetType: 'gas-giant', materialCost: { stardust: 3, nebula_quartz: 1 },           championTier: 'void_sovereign', skinCount: 3 },
  Zoe:              { role: 'mid',     origin: 'Targon',        traits: ['celestial', 'astral'],          planetType: 'gas-giant', materialCost: { stardust: 2, moon_crystal: 2 },            championTier: 'cosmic_sovereign', skinCount: 6 },
  Xerath:           { role: 'mid',     origin: 'Shurima',       traits: ['invoker'],                      planetType: 'gas-giant', materialCost: { stardust: 3, solar_essence: 1 },           championTier: 'lone_wanderer', skinCount: 8 },
  "Vel'koz":        { role: 'mid',     origin: 'Void',      traits: ['arcanist', 'dark_star'],        planetType: 'gas-giant', materialCost: { stardust: 2, void_shard: 1 },              championTier: 'void_sovereign', skinCount: 6 },
  Ryze:             { role: 'mid',     origin: 'Shurima',       traits: ['arcanist', 'invoker'],          planetType: 'gas-giant', materialCost: { stardust: 2, nebula_quartz: 1 },           championTier: 'void_sovereign', skinCount: 11 },
  Zilean:           { role: 'support', origin: 'Shurima',       traits: ['celestial', 'moonlight'],       planetType: 'gas-giant', materialCost: { stardust: 3, dark_matter: 1 },             championTier: 'rift_keeper', skinCount: 7 },
  Viktor:           { role: 'mid',     origin: 'Zaun',          traits: ['arcanist', 'invoker'],          planetType: 'gas-giant', materialCost: { stardust: 2, nebula_quartz: 2 },           championTier: 'astral_warden', skinCount: 7 },
  Orianna:          { role: 'mid',     origin: 'Piltover',      traits: ['arcanist'],                     planetType: 'gas-giant', materialCost: { stardust: 2, moon_crystal: 1 },            championTier: 'rift_keeper', skinCount: 9 },
  Heimerdinger:     { role: 'mid',     origin: 'Piltover',      traits: ['astral'],                       planetType: 'gas-giant', materialCost: { stardust: 2, nebula_quartz: 1 },           championTier: 'rift_keeper', skinCount: 7 },
  Jayce:            { role: 'top',     origin: 'Piltover',      traits: ['jade'],                         planetType: 'gas-giant', materialCost: { stardust: 2, solar_essence: 1 },           championTier: 'astral_warden', skinCount: 7 },
  Blitzcrank:       { role: 'support', origin: 'Zaun',          traits: ['guardian'],                     planetType: 'gas-giant', materialCost: { stardust: 2, nebula_quartz: 1 },           championTier: 'lone_wanderer', skinCount: 9 },
  Rumble:           { role: 'top',     origin: 'Bandle',   traits: ['challenger'],                   planetType: 'gas-giant', materialCost: { stardust: 2, solar_essence: 1 },           championTier: 'void_sovereign', skinCount: 7 },
  Corki:            { role: 'mid',     origin: 'Bandle',   traits: ['astral'],                       planetType: 'gas-giant', materialCost: { stardust: 2, moon_crystal: 1 },            championTier: 'lone_wanderer', skinCount: 7 },
  Ziggs:            { role: 'mid',     origin: 'Bandle',   traits: ['arcanist'],                     planetType: 'gas-giant', materialCost: { stardust: 3, solar_essence: 1 },           championTier: 'cosmic_sovereign', skinCount: 8 },
  Hwei:             { role: 'mid',     origin: 'Ionia',         traits: ['enchanter', 'invoker'],         planetType: 'gas-giant', materialCost: { stardust: 2, moon_crystal: 1 },            championTier: 'void_sovereign', skinCount: 1 },
  Seraphine:        { role: 'support', origin: 'Piltover',      traits: ['enchanter', 'moonlight'],       planetType: 'gas-giant', materialCost: { stardust: 2, moon_crystal: 1 },            championTier: 'nebula_sage', skinCount: 2 },
  Sona:             { role: 'support', origin: 'Demacia',       traits: ['enchanter', 'invoker'],         planetType: 'gas-giant', materialCost: { stardust: 2, moon_crystal: 1 },            championTier: 'lone_wanderer', skinCount: 13 },
  Lux:              { role: 'support', origin: 'Demacia',       traits: ['celestial', 'jade'],            planetType: 'gas-giant', materialCost: { stardust: 3, moon_crystal: 1 },            championTier: 'lone_wanderer', skinCount: 19 },
  Karma:            { role: 'support', origin: 'Ionia',         traits: ['enchanter', 'invoker'],         planetType: 'gas-giant', materialCost: { stardust: 2, nebula_quartz: 1 },           championTier: 'nebula_sage', skinCount: 11 },
  Smolder:          { role: 'adc',     origin: 'Targon',        traits: ['moonlight', 'astral'],          planetType: 'gas-giant', materialCost: { stardust: 2, solar_essence: 1 },           championTier: 'void_sovereign', skinCount: 1 },

  // ── Lava ────────────────────────────────────────────────────────────────────
  Brand:            { role: 'support', origin: 'Freljord',  traits: ['arcanist'],                     planetType: 'lava',      materialCost: { solar_essence: 2, stardust: 2 },           championTier: 'lone_wanderer', skinCount: 9 },
  Shyvana:          { role: 'jungle',  origin: 'Demacia',       traits: ['elderwood'],                    planetType: 'lava',      materialCost: { solar_essence: 1, nebula_quartz: 2 },      championTier: 'astral_warden', skinCount: 8 },
  Annie:            { role: 'mid',     origin: 'Noxus',         traits: ['astral'],                       planetType: 'lava',      materialCost: { solar_essence: 1, stardust: 2 },           championTier: 'lone_wanderer', skinCount: 12 },
  Renekton:         { role: 'top',     origin: 'Shurima',       traits: ['challenger'],                   planetType: 'lava',      materialCost: { solar_essence: 2, stardust: 1 },           championTier: 'void_sovereign', skinCount: 8 },
  Aatrox:           { role: 'top',     origin: 'Shurima',       traits: ['challenger', 'dark_star'],      planetType: 'lava',      materialCost: { solar_essence: 2, void_shard: 1 },         championTier: 'astral_warden', skinCount: 4 },
  Kled:             { role: 'top',     origin: 'Noxus',         traits: ['challenger'],                   planetType: 'lava',      materialCost: { solar_essence: 1, nebula_quartz: 2 },      championTier: 'void_sovereign', skinCount: 4 },
  Warwick:          { role: 'jungle',  origin: 'Zaun',          traits: ['challenger', 'elderwood'],      planetType: 'lava',      materialCost: { solar_essence: 1, stardust: 2 },           championTier: 'lone_wanderer', skinCount: 13 },
  Singed:           { role: 'top',     origin: 'Zaun',          traits: ['arcanist', 'challenger'],       planetType: 'lava',      materialCost: { solar_essence: 2, nebula_quartz: 1 },      championTier: 'void_sovereign', skinCount: 10 },
  'Dr. Mundo':      { role: 'top',     origin: 'Zaun',          traits: ['challenger'],                   planetType: 'lava',      materialCost: { solar_essence: 1, stardust: 2 },           championTier: 'lone_wanderer', skinCount: 8 },
  Draven:           { role: 'adc',     origin: 'Noxus',         traits: ['challenger', 'dark_star'],      planetType: 'lava',      materialCost: { solar_essence: 2, stardust: 1 },           championTier: 'nebula_sage', skinCount: 10 },
  Samira:           { role: 'adc',     origin: 'Noxus',         traits: ['duelist', 'challenger'],        planetType: 'lava',      materialCost: { solar_essence: 2, stardust: 1 },           championTier: 'rift_keeper', skinCount: 4 },
  Riven:            { role: 'top',     origin: 'Noxus',         traits: ['duelist'],                      planetType: 'lava',      materialCost: { solar_essence: 1, nebula_quartz: 2 },      championTier: 'void_sovereign', skinCount: 14 },
  Ambessa:          { role: 'top',     origin: 'Noxus',         traits: ['challenger'],                   planetType: 'lava',      materialCost: { solar_essence: 2, nebula_quartz: 1 },      championTier: 'cosmic_sovereign', skinCount: 0 },
  Mel:              { role: 'mid',     origin: 'Noxus',         traits: ['enchanter'],                    planetType: 'lava',      materialCost: { solar_essence: 1, stardust: 2 },           championTier: 'cosmic_sovereign', skinCount: 0 },
  Swain:            { role: 'support', origin: 'Noxus',         traits: ['dark_star', 'invoker'],         planetType: 'lava',      materialCost: { solar_essence: 2, void_shard: 1 },         championTier: 'astral_warden', skinCount: 5 },
  Viego:            { role: 'jungle',  origin: 'Isles',  traits: ['phantom', 'dark_star', 'reaper'], planetType: 'lava',   materialCost: { solar_essence: 2, dark_matter: 1 },        championTier: 'cosmic_sovereign', skinCount: 5 },
  Mordekaiser:      { role: 'top',     origin: 'Noxus',         traits: ['phantom', 'dark_star'],         planetType: 'lava',      materialCost: { solar_essence: 2, void_shard: 1 },         championTier: 'lone_wanderer', skinCount: 8 },

  // ── Ocean ────────────────────────────────────────────────────────────────────
  Nami:             { role: 'support', origin: 'Bilgewater',    traits: ['enchanter', 'invoker'],         planetType: 'ocean',     materialCost: { moon_crystal: 2, stardust: 1 },            championTier: 'nebula_sage', skinCount: 9 },
  Nautilus:         { role: 'support', origin: 'Bilgewater',    traits: ['guardian'],                     planetType: 'ocean',     materialCost: { nebula_quartz: 2, moon_crystal: 1 },       championTier: 'void_sovereign', skinCount: 7 },
  Fizz:             { role: 'mid',     origin: 'Bilgewater',    traits: ['assassin'],                     planetType: 'ocean',     materialCost: { stardust: 2, moon_crystal: 1 },            championTier: 'lone_wanderer', skinCount: 10 },
  'Tahm Kench':     { role: 'top',     origin: 'Bilgewater',    traits: ['guardian'],                     planetType: 'ocean',     materialCost: { moon_crystal: 2, nebula_quartz: 1 },       championTier: 'cosmic_sovereign', skinCount: 4 },
  Pyke:             { role: 'support', origin: 'Bilgewater',    traits: ['assassin', 'reaper'],           planetType: 'ocean',     materialCost: { moon_crystal: 2, void_shard: 1 },          championTier: 'nebula_sage', skinCount: 9 },
  Nilah:            { role: 'adc',     origin: 'Bilgewater',    traits: ['duelist'],                      planetType: 'ocean',     materialCost: { moon_crystal: 2, stardust: 1 },            championTier: 'void_sovereign', skinCount: 3 },
  Illaoi:           { role: 'top',     origin: 'Bilgewater',    traits: ['invoker'],                      planetType: 'ocean',     materialCost: { nebula_quartz: 2, moon_crystal: 1 },       championTier: 'nebula_sage', skinCount: 6 },
  Gangplank:        { role: 'top',     origin: 'Bilgewater',    traits: ['challenger'],                   planetType: 'ocean',     materialCost: { moon_crystal: 2, stardust: 1 },            championTier: 'rift_keeper', skinCount: 10 },
  'Miss Fortune':   { role: 'adc',     origin: 'Bilgewater',    traits: ['reaper'],                       planetType: 'ocean',     materialCost: { stardust: 2, moon_crystal: 1 },            championTier: 'lone_wanderer', skinCount: 20 },
  'Twisted Fate':   { role: 'mid',     origin: 'Bilgewater',    traits: ['arcanist', 'astral'],           planetType: 'ocean',     materialCost: { moon_crystal: 1, stardust: 2 },            championTier: 'void_sovereign', skinCount: 11 },
  Graves:           { role: 'jungle',  origin: 'Bilgewater',    traits: ['duelist'],                      planetType: 'ocean',     materialCost: { moon_crystal: 2, nebula_quartz: 1 },       championTier: 'astral_warden', skinCount: 11 },
  Tristana:         { role: 'adc',     origin: 'Bandle',   traits: ['duelist', 'challenger'],        planetType: 'ocean',     materialCost: { stardust: 2, moon_crystal: 1 },            championTier: 'rift_keeper', skinCount: 14 },
  Zac:              { role: 'jungle',  origin: 'Zaun',          traits: ['challenger'],                   planetType: 'ocean',     materialCost: { moon_crystal: 2, nebula_quartz: 1 },       championTier: 'cosmic_sovereign', skinCount: 4 },
  Maokai:           { role: 'support', origin: 'Isles',  traits: ['phantom', 'elderwood'],         planetType: 'ocean',     materialCost: { moon_crystal: 2, stardust: 1 },            championTier: 'void_sovereign', skinCount: 8 },
  Neeko:            { role: 'mid',     origin: 'Ixtal',         traits: ['moonlight'],                    planetType: 'ocean',     materialCost: { moon_crystal: 2, stardust: 1 },            championTier: 'astral_warden', skinCount: 7 },
  Yuumi:            { role: 'support', origin: 'Bandle',   traits: ['enchanter'],                    planetType: 'ocean',     materialCost: { stardust: 2, moon_crystal: 1 },            championTier: 'rift_keeper', skinCount: 4 },
  Lulu:             { role: 'support', origin: 'Bandle',   traits: ['enchanter'],                    planetType: 'ocean',     materialCost: { moon_crystal: 2, stardust: 1 },            championTier: 'astral_warden', skinCount: 8 },
  Milio:            { role: 'support', origin: 'Ixtal',         traits: ['enchanter'],                    planetType: 'ocean',     materialCost: { stardust: 2, moon_crystal: 1 },            championTier: 'void_sovereign', skinCount: 3 },

  // ── Desert ───────────────────────────────────────────────────────────────────
  Azir:             { role: 'mid',     origin: 'Shurima',       traits: ['invoker', 'astral'],            planetType: 'desert',    materialCost: { solar_essence: 2, void_shard: 1 },         championTier: 'astral_warden', skinCount: 2 },
  Sivir:            { role: 'adc',     origin: 'Shurima',       traits: ['challenger'],                   planetType: 'desert',    materialCost: { stardust: 3, solar_essence: 1 },           championTier: 'lone_wanderer', skinCount: 14 },
  Nasus:            { role: 'top',     origin: 'Shurima',       traits: ['guardian', 'reaper'],           planetType: 'desert',    materialCost: { solar_essence: 2, stardust: 1 },           championTier: 'rift_keeper', skinCount: 11 },
  Rengar:           { role: 'jungle',  origin: 'Ixtal',         traits: ['assassin'],                     planetType: 'desert',    materialCost: { solar_essence: 1, stardust: 2 },           championTier: 'void_sovereign', skinCount: 6 },
  Naafiri:          { role: 'mid',     origin: 'Shurima',       traits: ['assassin', 'dark_star'],        planetType: 'desert',    materialCost: { solar_essence: 2, nebula_quartz: 1 },      championTier: 'cosmic_sovereign', skinCount: 2 },
  'Rek Sai':        { role: 'jungle',  origin: 'Void',      traits: ['dark_star'],                    planetType: 'desert',    materialCost: { solar_essence: 1, nebula_quartz: 2 },      championTier: 'void_sovereign', skinCount: 3 },
  Kassadin:         { role: 'mid',     origin: 'Void',      traits: ['arcanist'],                     planetType: 'desert',    materialCost: { void_shard: 2, solar_essence: 1 },         championTier: 'rift_keeper', skinCount: 10 },
  Malzahar:         { role: 'mid',     origin: 'Void',      traits: ['invoker'],                      planetType: 'desert',    materialCost: { void_shard: 2, stardust: 1 },              championTier: 'astral_warden', skinCount: 12 },
  'Cho Gath':       { role: 'top',     origin: 'Void',      traits: ['guardian', 'dark_star'],        planetType: 'desert',    materialCost: { void_shard: 2, nebula_quartz: 1 },         championTier: 'lone_wanderer', skinCount: 5 },
  'Kha Zix':        { role: 'jungle',  origin: 'Void',      traits: ['assassin'],                     planetType: 'desert',    materialCost: { void_shard: 1, solar_essence: 2 },         championTier: 'void_sovereign', skinCount: 6 },
  "Kog'maw":        { role: 'adc',     origin: 'Void',      traits: ['dark_star'],                    planetType: 'desert',    materialCost: { void_shard: 1, stardust: 2 },              championTier: 'astral_warden', skinCount: 13 },
  BelVeth:          { role: 'jungle',  origin: 'Void',      traits: ['dark_star'],                    planetType: 'desert',    materialCost: { void_shard: 2, dark_matter: 1 },           championTier: 'cosmic_sovereign', skinCount: 1 },
  'Xin Zhao':       { role: 'jungle',  origin: 'Demacia',       traits: ['jade'],                         planetType: 'desert',    materialCost: { solar_essence: 1, stardust: 2 },           championTier: 'rift_keeper', skinCount: 10 },
  'Jarvan IV':      { role: 'jungle',  origin: 'Demacia',       traits: ['jade'],                         planetType: 'desert',    materialCost: { solar_essence: 2, nebula_quartz: 1 },      championTier: 'rift_keeper', skinCount: 10 },
  Jax:              { role: 'top',     origin: 'Shurima',       traits: ['duelist'],                      planetType: 'desert',    materialCost: { solar_essence: 1, stardust: 2 },           championTier: 'lone_wanderer', skinCount: 15 },
  'Lee Sin':        { role: 'jungle',  origin: 'Ionia',         traits: ['duelist'],                      planetType: 'desert',    materialCost: { solar_essence: 2, stardust: 1 },           championTier: 'lone_wanderer', skinCount: 11 },
  'Master Yi':      { role: 'jungle',  origin: 'Ionia',         traits: ['duelist'],                      planetType: 'desert',    materialCost: { solar_essence: 1, stardust: 2 },           championTier: 'lone_wanderer', skinCount: 15 },
  Irelia:           { role: 'top',     origin: 'Ionia',         traits: ['duelist'],                      planetType: 'desert',    materialCost: { solar_essence: 2, moon_crystal: 1 },       championTier: 'nebula_sage', skinCount: 12 },
  "K'sante":        { role: 'top',     origin: 'Shurima',       traits: ['guardian'],                     planetType: 'desert',    materialCost: { solar_essence: 2, nebula_quartz: 1 },      championTier: 'cosmic_sovereign', skinCount: 1 },

  // ── Jungle ───────────────────────────────────────────────────────────────────
  Ivern:            { role: 'jungle',  origin: 'Ionia',         traits: ['enchanter', 'elderwood'],       planetType: 'jungle',    materialCost: { stardust: 2, nebula_quartz: 1 },           championTier: 'astral_warden', skinCount: 4 },
  Nidalee:          { role: 'jungle',  origin: 'Ixtal',         traits: ['elderwood'],                    planetType: 'jungle',    materialCost: { moon_crystal: 1, stardust: 2 },            championTier: 'nebula_sage', skinCount: 13 },
  Zyra:             { role: 'support', origin: 'Ixtal',         traits: ['invoker'],                      planetType: 'jungle',    materialCost: { stardust: 2, nebula_quartz: 1 },           championTier: 'astral_warden', skinCount: 9 },
  Elise:            { role: 'jungle',  origin: 'Isles',  traits: ['phantom', 'moonlight'],         planetType: 'jungle',    materialCost: { stardust: 2, void_shard: 1 },              championTier: 'astral_warden', skinCount: 7 },
  Teemo:            { role: 'top',     origin: 'Bandle',   traits: ['elderwood'],                    planetType: 'jungle',    materialCost: { stardust: 2, moon_crystal: 1 },            championTier: 'lone_wanderer', skinCount: 14 },
  Gwen:             { role: 'top',     origin: 'Isles',  traits: ['phantom'],                      planetType: 'jungle',    materialCost: { stardust: 2, moon_crystal: 1 },            championTier: 'astral_warden', skinCount: 4 },
  Briar:            { role: 'jungle',  origin: 'Noxus',         traits: ['challenger'],                   planetType: 'jungle',    materialCost: { stardust: 2, void_shard: 1 },              championTier: 'cosmic_sovereign', skinCount: 3 },
  FiddleSticks:     { role: 'jungle',  origin: 'Isles',  traits: ['phantom', 'reaper'],            planetType: 'jungle',    materialCost: { void_shard: 1, stardust: 2 },              championTier: 'lone_wanderer', skinCount: 10 },
  Shaco:            { role: 'jungle',  origin: 'Isles',  traits: ['assassin'],                     planetType: 'jungle',    materialCost: { stardust: 2, void_shard: 1 },              championTier: 'nebula_sage', skinCount: 14 },
  Hecarim:          { role: 'jungle',  origin: 'Isles',  traits: ['phantom', 'elderwood', 'reaper'], planetType: 'jungle', materialCost: { stardust: 2, nebula_quartz: 1 },           championTier: 'astral_warden', skinCount: 10 },
  Nocturne:         { role: 'jungle',  origin: 'Isles',  traits: ['phantom', 'dark_star'],         planetType: 'jungle',    materialCost: { void_shard: 1, stardust: 2 },              championTier: 'nebula_sage', skinCount: 8 },
  Kayn:             { role: 'jungle',  origin: 'Ionia',         traits: ['dark_star'],                    planetType: 'jungle',    materialCost: { stardust: 2, void_shard: 1 },              championTier: 'nebula_sage', skinCount: 7 },
  Evelynn:          { role: 'jungle',  origin: 'Isles',  traits: ['assassin', 'moonlight'],        planetType: 'jungle',    materialCost: { stardust: 2, void_shard: 1 },              championTier: 'lone_wanderer', skinCount: 8 },
  Ekko:             { role: 'jungle',  origin: 'Zaun',          traits: ['assassin', 'astral'],           planetType: 'jungle',    materialCost: { stardust: 2, nebula_quartz: 1 },           championTier: 'rift_keeper', skinCount: 7 },
  Vi:               { role: 'jungle',  origin: 'Zaun',          traits: ['challenger'],                   planetType: 'jungle',    materialCost: { stardust: 2, nebula_quartz: 1 },           championTier: 'rift_keeper', skinCount: 9 },
  Camille:          { role: 'top',     origin: 'Piltover',      traits: ['duelist'],                      planetType: 'jungle',    materialCost: { stardust: 2, solar_essence: 1 },           championTier: 'astral_warden', skinCount: 2 },
  Fiora:            { role: 'top',     origin: 'Demacia',       traits: ['duelist'],                      planetType: 'jungle',    materialCost: { stardust: 2, moon_crystal: 1 },            championTier: 'astral_warden', skinCount: 13 },
  Qiyana:           { role: 'mid',     origin: 'Ixtal',         traits: ['assassin'],                     planetType: 'jungle',    materialCost: { stardust: 2, nebula_quartz: 1 },           championTier: 'void_sovereign', skinCount: 6 },
  Akali:            { role: 'mid',     origin: 'Ionia',         traits: ['assassin'],                     planetType: 'jungle',    materialCost: { stardust: 2, solar_essence: 1 },           championTier: 'lone_wanderer', skinCount: 11 },
  Katarina:         { role: 'mid',     origin: 'Noxus',         traits: ['assassin'],                     planetType: 'jungle',    materialCost: { stardust: 2, solar_essence: 1 },           championTier: 'rift_keeper', skinCount: 15 },
  Talon:            { role: 'mid',     origin: 'Noxus',         traits: ['assassin'],                     planetType: 'jungle',    materialCost: { stardust: 2, void_shard: 1 },              championTier: 'nebula_sage', skinCount: 8 },

  // ── Ringed ───────────────────────────────────────────────────────────────────
  Soraka:           { role: 'support', origin: 'Targon',        traits: ['celestial', 'enchanter'],       planetType: 'ringed',    materialCost: { stardust: 2, dark_matter: 1 },             championTier: 'lone_wanderer', skinCount: 14 },
  Syndra:           { role: 'mid',     origin: 'Ionia',         traits: ['arcanist', 'invoker'],          planetType: 'ringed',    materialCost: { void_shard: 2, nebula_quartz: 1 },         championTier: 'nebula_sage', skinCount: 5 },
  Diana:            { role: 'jungle',  origin: 'Targon',        traits: ['moonlight'],                    planetType: 'ringed',    materialCost: { moon_crystal: 3, dark_matter: 1 },         championTier: 'lone_wanderer', skinCount: 2 },
  Leona:            { role: 'support', origin: 'Targon',        traits: ['guardian', 'jade'],             planetType: 'ringed',    materialCost: { solar_essence: 2, stardust: 1 },           championTier: 'lone_wanderer', skinCount: 15 },
  Kayle:            { role: 'top',     origin: 'Targon',        traits: ['celestial'],                    planetType: 'ringed',    materialCost: { solar_essence: 2, dark_matter: 1 },        championTier: 'astral_warden', skinCount: 12 },
  Morgana:          { role: 'support', origin: 'Targon',        traits: ['moonlight'],                    planetType: 'ringed',    materialCost: { void_shard: 2, dark_matter: 1 },           championTier: 'rift_keeper', skinCount: 12 },
  Thresh:           { role: 'support', origin: 'Isles',  traits: ['celestial', 'reaper'],          planetType: 'ringed',    materialCost: { void_shard: 2, moon_crystal: 1 },          championTier: 'astral_warden', skinCount: 11 },
  Kindred:          { role: 'jungle',  origin: 'Freljord',  traits: ['celestial', 'phantom', 'moonlight'], planetType: 'ringed', materialCost: { dark_matter: 1, stardust: 2 },          championTier: 'void_sovereign', skinCount: 5 },
  Karthus:          { role: 'jungle',  origin: 'Isles',  traits: ['phantom', 'reaper'],            planetType: 'ringed',    materialCost: { void_shard: 2, dark_matter: 1 },           championTier: 'nebula_sage', skinCount: 6 },
  Vladimir:         { role: 'mid',     origin: 'Noxus',         traits: ['dark_star'],                    planetType: 'ringed',    materialCost: { solar_essence: 2, void_shard: 1 },         championTier: 'nebula_sage', skinCount: 10 },
  Cassiopeia:       { role: 'mid',     origin: 'Noxus',         traits: ['invoker'],                      planetType: 'ringed',    materialCost: { void_shard: 2, solar_essence: 1 },         championTier: 'astral_warden', skinCount: 6 },
  Leblanc:          { role: 'mid',     origin: 'Noxus',         traits: ['arcanist'],                     planetType: 'ringed',    materialCost: { dark_matter: 1, stardust: 2 },             championTier: 'rift_keeper', skinCount: 12 },
  Ahri:             { role: 'mid',     origin: 'Ionia',         traits: ['astral'],                       planetType: 'ringed',    materialCost: { stardust: 2, moon_crystal: 1 },            championTier: 'lone_wanderer', skinCount: 10 },
  Veigar:           { role: 'mid',     origin: 'Bandle',   traits: ['arcanist'],                     planetType: 'ringed',    materialCost: { dark_matter: 1, void_shard: 1 },           championTier: 'lone_wanderer', skinCount: 14 },
  Aphelios:         { role: 'adc',     origin: 'Targon',        traits: ['moonlight'],                    planetType: 'ringed',    materialCost: { dark_matter: 1, moon_crystal: 2 },         championTier: 'nebula_sage', skinCount: 1 },
  Jhin:             { role: 'adc',     origin: 'Ionia',         traits: ['arcanist', 'reaper'],           planetType: 'ringed',    materialCost: { dark_matter: 1, stardust: 2 },             championTier: 'nebula_sage', skinCount: 9 },
  Varus:            { role: 'adc',     origin: 'Ionia',         traits: ['dark_star'],                    planetType: 'ringed',    materialCost: { void_shard: 1, stardust: 2 },              championTier: 'astral_warden', skinCount: 11 },
  "Kai'sa":         { role: 'adc',     origin: 'Void',      traits: ['assassin', 'dark_star'],        planetType: 'ringed',    materialCost: { void_shard: 1, stardust: 2 },              championTier: 'lone_wanderer', skinCount: 10 },
  Ezreal:           { role: 'adc',     origin: 'Piltover',      traits: ['astral'],                       planetType: 'ringed',    materialCost: { stardust: 2, nebula_quartz: 1 },           championTier: 'lone_wanderer', skinCount: 17 },
  Lucian:           { role: 'adc',     origin: 'Demacia',       traits: ['reaper'],                       planetType: 'ringed',    materialCost: { solar_essence: 1, stardust: 2 },           championTier: 'rift_keeper', skinCount: 11 },
  Jinx:             { role: 'adc',     origin: 'Zaun',          traits: ['challenger'],                   planetType: 'ringed',    materialCost: { stardust: 3, solar_essence: 1 },           championTier: 'nebula_sage', skinCount: 10 },
  Caitlyn:          { role: 'adc',     origin: 'Piltover',      traits: ['duelist'],                      planetType: 'ringed',    materialCost: { stardust: 2, nebula_quartz: 1 },           championTier: 'lone_wanderer', skinCount: 8 },
  Vayne:            { role: 'top',     origin: 'Demacia',       traits: ['assassin', 'moonlight'],        planetType: 'ringed',    materialCost: { stardust: 2, void_shard: 1 },              championTier: 'nebula_sage', skinCount: 12 },
  Kalista:          { role: 'adc',     origin: 'Isles',  traits: ['phantom', 'reaper'],            planetType: 'ringed',    materialCost: { void_shard: 2, dark_matter: 1 },           championTier: 'astral_warden', skinCount: 5 },
  Xayah:            { role: 'adc',     origin: 'Ionia',         traits: ['celestial'],                    planetType: 'ringed',    materialCost: { stardust: 2, moon_crystal: 1 },            championTier: 'astral_warden', skinCount: 2 },
  Rakan:            { role: 'support', origin: 'Ionia',         traits: ['celestial', 'enchanter'],       planetType: 'ringed',    materialCost: { stardust: 2, moon_crystal: 1 },            championTier: 'void_sovereign', skinCount: 3 },
  Senna:            { role: 'support', origin: 'Demacia',       traits: ['reaper'],                       planetType: 'ringed',    materialCost: { void_shard: 1, stardust: 2 },              championTier: 'nebula_sage', skinCount: 5 },
  'Renata Glasc':   { role: 'support', origin: 'Zaun',          traits: ['enchanter'],                    planetType: 'ringed',    materialCost: { dark_matter: 1, nebula_quartz: 2 },        championTier: 'cosmic_sovereign', skinCount: 3 },
  Zeri:             { role: 'adc',     origin: 'Zaun',          traits: ['duelist', 'astral'],            planetType: 'ringed',    materialCost: { stardust: 2, solar_essence: 1 },           championTier: 'cosmic_sovereign', skinCount: 1 },
  Akshan:           { role: 'mid',     origin: 'Shurima',       traits: ['assassin', 'jade'],             planetType: 'ringed',    materialCost: { stardust: 2, solar_essence: 1 },           championTier: 'nebula_sage', skinCount: 0 },
  Yasuo:            { role: 'mid',     origin: 'Ionia',         traits: ['duelist'],                      planetType: 'ringed',    materialCost: { stardust: 2, nebula_quartz: 1 },           championTier: 'lone_wanderer', skinCount: 14 },
  Yone:             { role: 'mid',     origin: 'Ionia',         traits: ['duelist', 'moonlight'],         planetType: 'ringed',    materialCost: { void_shard: 1, stardust: 2 },              championTier: 'nebula_sage', skinCount: 5 },
  Zed:              { role: 'mid',     origin: 'Ionia',         traits: ['assassin'],                     planetType: 'ringed',    materialCost: { void_shard: 2, stardust: 1 },              championTier: 'lone_wanderer', skinCount: 9 },
  Sylas:            { role: 'mid',     origin: 'Demacia',       traits: ['arcanist', 'challenger'],       planetType: 'ringed',    materialCost: { nebula_quartz: 2, void_shard: 1 },         championTier: 'rift_keeper', skinCount: 7 },
  Twitch:           { role: 'adc',     origin: 'Zaun',          traits: ['assassin', 'reaper'],           planetType: 'ringed',    materialCost: { void_shard: 1, stardust: 2 },              championTier: 'rift_keeper', skinCount: 8 },
}

export function getChampionNames(): string[] {
  return Object.keys(CHAMPION_DATA)
}
