import type { PlanetType } from '../types'

export interface ChampionHomePlanetConfig {
  championName: string
  planetType: PlanetType
  materialCost: Record<string, number>
}

export const CHAMPION_HOME_PLANETS: ChampionHomePlanetConfig[] = [
  // ── Rocky ──────────────────────────────────────────────
  { championName: 'Malphite', planetType: 'rocky', materialCost: { nebula_quartz: 3 } },
  { championName: 'Taliyah', planetType: 'rocky', materialCost: { nebula_quartz: 2, stardust: 1 } },
  { championName: 'Galio', planetType: 'rocky', materialCost: { nebula_quartz: 2, moon_crystal: 1 } },
  { championName: 'Skarner', planetType: 'rocky', materialCost: { nebula_quartz: 2, stardust: 2 } },
  { championName: 'Rammus', planetType: 'rocky', materialCost: { nebula_quartz: 2 } },
  { championName: 'Ornn', planetType: 'rocky', materialCost: { nebula_quartz: 3, solar_essence: 1 } },
  { championName: 'Sion', planetType: 'rocky', materialCost: { nebula_quartz: 2, stardust: 1 } },
  { championName: 'Poppy', planetType: 'rocky', materialCost: { nebula_quartz: 1, stardust: 2 } },
  { championName: 'Gnar', planetType: 'rocky', materialCost: { nebula_quartz: 2, moon_crystal: 1 } },
  { championName: 'Urgot', planetType: 'rocky', materialCost: { nebula_quartz: 2, solar_essence: 1 } },
  { championName: 'Yorick', planetType: 'rocky', materialCost: { nebula_quartz: 2, void_shard: 1 } },
  { championName: 'Darius', planetType: 'rocky', materialCost: { nebula_quartz: 2, stardust: 1 } },
  { championName: 'Garen', planetType: 'rocky', materialCost: { nebula_quartz: 1, stardust: 2 } },

  { championName: 'Pantheon', planetType: 'rocky', materialCost: { nebula_quartz: 2, solar_essence: 1 } },
  { championName: 'Sett', planetType: 'rocky', materialCost: { nebula_quartz: 2, stardust: 1 } },
  { championName: 'Rell', planetType: 'rocky', materialCost: { nebula_quartz: 2, moon_crystal: 1 } },
  { championName: 'Trundle', planetType: 'rocky', materialCost: { nebula_quartz: 2, stardust: 1 } },
  { championName: 'Volibear', planetType: 'rocky', materialCost: { nebula_quartz: 2, solar_essence: 1 } },
  { championName: 'Olaf', planetType: 'rocky', materialCost: { nebula_quartz: 2, stardust: 1 } },
  { championName: 'Wukong', planetType: 'rocky', materialCost: { nebula_quartz: 1, stardust: 2 } },
  { championName: 'Alistar', planetType: 'rocky', materialCost: { nebula_quartz: 2, stardust: 1 } },
  { championName: 'Amumu', planetType: 'rocky', materialCost: { nebula_quartz: 1, moon_crystal: 2 } },

  // ── Ice ────────────────────────────────────────────────
  { championName: 'Lissandra', planetType: 'ice', materialCost: { moon_crystal: 3 } },
  { championName: 'Anivia', planetType: 'ice', materialCost: { moon_crystal: 2, nebula_quartz: 1 } },
  { championName: 'Nunu A. Willump', planetType: 'ice', materialCost: { moon_crystal: 2, stardust: 1 } },
  { championName: 'Sejuani', planetType: 'ice', materialCost: { moon_crystal: 2, nebula_quartz: 1 } },
  { championName: 'Braum', planetType: 'ice', materialCost: { moon_crystal: 2, stardust: 1 } },
  { championName: 'Ashe', planetType: 'ice', materialCost: { moon_crystal: 2, stardust: 1 } },
  { championName: 'Tryndamere', planetType: 'ice', materialCost: { moon_crystal: 2, solar_essence: 1 } },
  { championName: 'Udyr', planetType: 'ice', materialCost: { moon_crystal: 2, nebula_quartz: 1 } },
  { championName: 'Gragas', planetType: 'ice', materialCost: { moon_crystal: 2, stardust: 1 } },
  { championName: 'Vex', planetType: 'ice', materialCost: { moon_crystal: 2, void_shard: 1 } },
  { championName: 'Aurora', planetType: 'ice', materialCost: { moon_crystal: 3, stardust: 1 } },
  { championName: 'Lillia', planetType: 'ice', materialCost: { moon_crystal: 2, stardust: 1 } },
  { championName: 'Quinn', planetType: 'ice', materialCost: { moon_crystal: 1, stardust: 2 } },
  { championName: 'Kennen', planetType: 'ice', materialCost: { moon_crystal: 2, solar_essence: 1 } },
  { championName: 'Shen', planetType: 'ice', materialCost: { moon_crystal: 2, stardust: 1 } },
  { championName: 'Janna', planetType: 'ice', materialCost: { moon_crystal: 2, stardust: 1 } },
  { championName: 'Taric', planetType: 'ice', materialCost: { moon_crystal: 3, nebula_quartz: 1 } },

  // ── Gas Giant ──────────────────────────────────────────
  { championName: 'Aurelion Sol', planetType: 'gas-giant', materialCost: { stardust: 3, nebula_quartz: 1 } },
  { championName: 'Zoe', planetType: 'gas-giant', materialCost: { stardust: 2, moon_crystal: 2 } },
  { championName: 'Xerath', planetType: 'gas-giant', materialCost: { stardust: 3, solar_essence: 1 } },
  { championName: 'Vel\'koz', planetType: 'gas-giant', materialCost: { stardust: 2, void_shard: 1 } },
  { championName: 'Ryze', planetType: 'gas-giant', materialCost: { stardust: 2, nebula_quartz: 1 } },
  { championName: 'Zilean', planetType: 'gas-giant', materialCost: { stardust: 3, dark_matter: 1 } },
  { championName: 'Viktor', planetType: 'gas-giant', materialCost: { stardust: 2, nebula_quartz: 2 } },
  { championName: 'Orianna', planetType: 'gas-giant', materialCost: { stardust: 2, moon_crystal: 1 } },
  { championName: 'Heimerdinger', planetType: 'gas-giant', materialCost: { stardust: 2, nebula_quartz: 1 } },
  { championName: 'Jayce', planetType: 'gas-giant', materialCost: { stardust: 2, solar_essence: 1 } },
  { championName: 'Blitzcrank', planetType: 'gas-giant', materialCost: { stardust: 2, nebula_quartz: 1 } },
  { championName: 'Rumble', planetType: 'gas-giant', materialCost: { stardust: 2, solar_essence: 1 } },
  { championName: 'Corki', planetType: 'gas-giant', materialCost: { stardust: 2, moon_crystal: 1 } },
  { championName: 'Ziggs', planetType: 'gas-giant', materialCost: { stardust: 3, solar_essence: 1 } },
  { championName: 'Hwei', planetType: 'gas-giant', materialCost: { stardust: 2, moon_crystal: 1 } },
  { championName: 'Seraphine', planetType: 'gas-giant', materialCost: { stardust: 2, moon_crystal: 1 } },
  { championName: 'Sona', planetType: 'gas-giant', materialCost: { stardust: 2, moon_crystal: 1 } },
  { championName: 'Lux', planetType: 'gas-giant', materialCost: { stardust: 3, moon_crystal: 1 } },
  { championName: 'Karma', planetType: 'gas-giant', materialCost: { stardust: 2, nebula_quartz: 1 } },
  { championName: 'Smolder', planetType: 'gas-giant', materialCost: { stardust: 2, solar_essence: 1 } },

  // ── Lava ───────────────────────────────────────────────
  { championName: 'Brand', planetType: 'lava', materialCost: { solar_essence: 2, stardust: 2 } },
  { championName: 'Shyvana', planetType: 'lava', materialCost: { solar_essence: 1, nebula_quartz: 2 } },
  { championName: 'Annie', planetType: 'lava', materialCost: { solar_essence: 1, stardust: 2 } },

  { championName: 'Renekton', planetType: 'lava', materialCost: { solar_essence: 2, stardust: 1 } },
  { championName: 'Aatrox', planetType: 'lava', materialCost: { solar_essence: 2, void_shard: 1 } },
  { championName: 'Kled', planetType: 'lava', materialCost: { solar_essence: 1, nebula_quartz: 2 } },
  { championName: 'Warwick', planetType: 'lava', materialCost: { solar_essence: 1, stardust: 2 } },
  { championName: 'Singed', planetType: 'lava', materialCost: { solar_essence: 2, nebula_quartz: 1 } },
  { championName: 'Dr. Mundo', planetType: 'lava', materialCost: { solar_essence: 1, stardust: 2 } },
  { championName: 'Draven', planetType: 'lava', materialCost: { solar_essence: 2, stardust: 1 } },
  { championName: 'Samira', planetType: 'lava', materialCost: { solar_essence: 2, stardust: 1 } },
  { championName: 'Riven', planetType: 'lava', materialCost: { solar_essence: 1, nebula_quartz: 2 } },
  { championName: 'Ambessa', planetType: 'lava', materialCost: { solar_essence: 2, nebula_quartz: 1 } },
  { championName: 'Mel', planetType: 'lava', materialCost: { solar_essence: 1, stardust: 2 } },
  { championName: 'Swain', planetType: 'lava', materialCost: { solar_essence: 2, void_shard: 1 } },
  { championName: 'Viego', planetType: 'lava', materialCost: { solar_essence: 2, dark_matter: 1 } },
  { championName: 'Mordekaiser', planetType: 'lava', materialCost: { solar_essence: 2, void_shard: 1 } },

  // ── Ocean ──────────────────────────────────────────────
  { championName: 'Nami', planetType: 'ocean', materialCost: { moon_crystal: 2, stardust: 1 } },
  { championName: 'Nautilus', planetType: 'ocean', materialCost: { nebula_quartz: 2, moon_crystal: 1 } },
  { championName: 'Fizz', planetType: 'ocean', materialCost: { stardust: 2, moon_crystal: 1 } },
  { championName: 'Tahm Kench', planetType: 'ocean', materialCost: { moon_crystal: 2, nebula_quartz: 1 } },
  { championName: 'Pyke', planetType: 'ocean', materialCost: { moon_crystal: 2, void_shard: 1 } },
  { championName: 'Nilah', planetType: 'ocean', materialCost: { moon_crystal: 2, stardust: 1 } },
  { championName: 'Illaoi', planetType: 'ocean', materialCost: { nebula_quartz: 2, moon_crystal: 1 } },
  { championName: 'Gangplank', planetType: 'ocean', materialCost: { moon_crystal: 2, stardust: 1 } },
  { championName: 'Miss Fortune', planetType: 'ocean', materialCost: { stardust: 2, moon_crystal: 1 } },
  { championName: 'Twisted Fate', planetType: 'ocean', materialCost: { moon_crystal: 1, stardust: 2 } },
  { championName: 'Graves', planetType: 'ocean', materialCost: { moon_crystal: 2, nebula_quartz: 1 } },
  { championName: 'Tristana', planetType: 'ocean', materialCost: { stardust: 2, moon_crystal: 1 } },
  { championName: 'Zac', planetType: 'ocean', materialCost: { moon_crystal: 2, nebula_quartz: 1 } },
  { championName: 'Maokai', planetType: 'ocean', materialCost: { moon_crystal: 2, stardust: 1 } },
  { championName: 'Neeko', planetType: 'ocean', materialCost: { moon_crystal: 2, stardust: 1 } },
  { championName: 'Yuumi', planetType: 'ocean', materialCost: { stardust: 2, moon_crystal: 1 } },
  { championName: 'Lulu', planetType: 'ocean', materialCost: { moon_crystal: 2, stardust: 1 } },
  { championName: 'Milio', planetType: 'ocean', materialCost: { stardust: 2, moon_crystal: 1 } },

  // ── Desert ─────────────────────────────────────────────
  { championName: 'Azir', planetType: 'desert', materialCost: { solar_essence: 2, void_shard: 1 } },
  { championName: 'Sivir', planetType: 'desert', materialCost: { stardust: 3, solar_essence: 1 } },
  { championName: 'Nasus', planetType: 'desert', materialCost: { solar_essence: 2, stardust: 1 } },
  { championName: 'Rengar', planetType: 'desert', materialCost: { solar_essence: 1, stardust: 2 } },
  { championName: 'Naafiri', planetType: 'desert', materialCost: { solar_essence: 2, nebula_quartz: 1 } },
  { championName: 'Rek Sai', planetType: 'desert', materialCost: { solar_essence: 1, nebula_quartz: 2 } },
  { championName: 'Kassadin', planetType: 'desert', materialCost: { void_shard: 2, solar_essence: 1 } },
  { championName: 'Malzahar', planetType: 'desert', materialCost: { void_shard: 2, stardust: 1 } },
  { championName: 'Cho Gath', planetType: 'desert', materialCost: { void_shard: 2, nebula_quartz: 1 } },
  { championName: 'Kha Zix', planetType: 'desert', materialCost: { void_shard: 1, solar_essence: 2 } },
  { championName: 'Kog\'maw', planetType: 'desert', materialCost: { void_shard: 1, stardust: 2 } },
  { championName: 'BelVeth', planetType: 'desert', materialCost: { void_shard: 2, dark_matter: 1 } },
  { championName: 'Xin Zhao', planetType: 'desert', materialCost: { solar_essence: 1, stardust: 2 } },
  { championName: 'Jarvan IV', planetType: 'desert', materialCost: { solar_essence: 2, nebula_quartz: 1 } },
  { championName: 'Jax', planetType: 'desert', materialCost: { solar_essence: 1, stardust: 2 } },
  { championName: 'Lee Sin', planetType: 'desert', materialCost: { solar_essence: 2, stardust: 1 } },
  { championName: 'Master Yi', planetType: 'desert', materialCost: { solar_essence: 1, stardust: 2 } },
  { championName: 'Irelia', planetType: 'desert', materialCost: { solar_essence: 2, moon_crystal: 1 } },
  { championName: 'K\'sante', planetType: 'desert', materialCost: { solar_essence: 2, nebula_quartz: 1 } },

  // ── Jungle ─────────────────────────────────────────────
  { championName: 'Ivern', planetType: 'jungle', materialCost: { stardust: 2, nebula_quartz: 1 } },
  { championName: 'Nidalee', planetType: 'jungle', materialCost: { moon_crystal: 1, stardust: 2 } },
  { championName: 'Zyra', planetType: 'jungle', materialCost: { stardust: 2, nebula_quartz: 1 } },
  { championName: 'Elise', planetType: 'jungle', materialCost: { stardust: 2, void_shard: 1 } },
  { championName: 'Teemo', planetType: 'jungle', materialCost: { stardust: 2, moon_crystal: 1 } },
  { championName: 'Gwen', planetType: 'jungle', materialCost: { stardust: 2, moon_crystal: 1 } },
  { championName: 'Briar', planetType: 'jungle', materialCost: { stardust: 2, void_shard: 1 } },
  { championName: 'FiddleSticks', planetType: 'jungle', materialCost: { void_shard: 1, stardust: 2 } },
  { championName: 'Shaco', planetType: 'jungle', materialCost: { stardust: 2, void_shard: 1 } },
  { championName: 'Hecarim', planetType: 'jungle', materialCost: { stardust: 2, nebula_quartz: 1 } },
  { championName: 'Nocturne', planetType: 'jungle', materialCost: { void_shard: 1, stardust: 2 } },
  { championName: 'Kayn', planetType: 'jungle', materialCost: { stardust: 2, void_shard: 1 } },
  { championName: 'Evelynn', planetType: 'jungle', materialCost: { stardust: 2, void_shard: 1 } },
  { championName: 'Ekko', planetType: 'jungle', materialCost: { stardust: 2, nebula_quartz: 1 } },
  { championName: 'Vi', planetType: 'jungle', materialCost: { stardust: 2, nebula_quartz: 1 } },
  { championName: 'Camille', planetType: 'jungle', materialCost: { stardust: 2, solar_essence: 1 } },
  { championName: 'Fiora', planetType: 'jungle', materialCost: { stardust: 2, moon_crystal: 1 } },
  { championName: 'Qiyana', planetType: 'jungle', materialCost: { stardust: 2, nebula_quartz: 1 } },
  { championName: 'Akali', planetType: 'jungle', materialCost: { stardust: 2, solar_essence: 1 } },
  { championName: 'Katarina', planetType: 'jungle', materialCost: { stardust: 2, solar_essence: 1 } },
  { championName: 'Talon', planetType: 'jungle', materialCost: { stardust: 2, void_shard: 1 } },

  // ── Ringed ─────────────────────────────────────────────
  { championName: 'Soraka', planetType: 'ringed', materialCost: { stardust: 2, dark_matter: 1 } },
  { championName: 'Syndra', planetType: 'ringed', materialCost: { void_shard: 2, nebula_quartz: 1 } },
  { championName: 'Diana', planetType: 'ringed', materialCost: { moon_crystal: 3, dark_matter: 1 } },
  { championName: 'Leona', planetType: 'ringed', materialCost: { solar_essence: 2, stardust: 1 } },
  { championName: 'Kayle', planetType: 'ringed', materialCost: { solar_essence: 2, dark_matter: 1 } },
  { championName: 'Morgana', planetType: 'ringed', materialCost: { void_shard: 2, dark_matter: 1 } },
  { championName: 'Thresh', planetType: 'ringed', materialCost: { void_shard: 2, moon_crystal: 1 } },
  { championName: 'Kindred', planetType: 'ringed', materialCost: { dark_matter: 1, stardust: 2 } },
  { championName: 'Karthus', planetType: 'ringed', materialCost: { void_shard: 2, dark_matter: 1 } },
  { championName: 'Vladimir', planetType: 'ringed', materialCost: { solar_essence: 2, void_shard: 1 } },
  { championName: 'Cassiopeia', planetType: 'ringed', materialCost: { void_shard: 2, solar_essence: 1 } },
  { championName: 'Leblanc', planetType: 'ringed', materialCost: { dark_matter: 1, stardust: 2 } },
  { championName: 'Ahri', planetType: 'ringed', materialCost: { stardust: 2, moon_crystal: 1 } },
  { championName: 'Veigar', planetType: 'ringed', materialCost: { dark_matter: 1, void_shard: 1 } },
  { championName: 'Aphelios', planetType: 'ringed', materialCost: { dark_matter: 1, moon_crystal: 2 } },
  { championName: 'Jhin', planetType: 'ringed', materialCost: { dark_matter: 1, stardust: 2 } },
  { championName: 'Varus', planetType: 'ringed', materialCost: { void_shard: 1, stardust: 2 } },
  { championName: 'Kai\'sa', planetType: 'ringed', materialCost: { void_shard: 1, stardust: 2 } },
  { championName: 'Ezreal', planetType: 'ringed', materialCost: { stardust: 2, nebula_quartz: 1 } },
  { championName: 'Lucian', planetType: 'ringed', materialCost: { solar_essence: 1, stardust: 2 } },
  { championName: 'Jinx', planetType: 'ringed', materialCost: { stardust: 3, solar_essence: 1 } },
  { championName: 'Caitlyn', planetType: 'ringed', materialCost: { stardust: 2, nebula_quartz: 1 } },
  { championName: 'Vayne', planetType: 'ringed', materialCost: { stardust: 2, void_shard: 1 } },
  { championName: 'Kalista', planetType: 'ringed', materialCost: { void_shard: 2, dark_matter: 1 } },
  { championName: 'Xayah', planetType: 'ringed', materialCost: { stardust: 2, moon_crystal: 1 } },
  { championName: 'Rakan', planetType: 'ringed', materialCost: { stardust: 2, moon_crystal: 1 } },
  { championName: 'Senna', planetType: 'ringed', materialCost: { void_shard: 1, stardust: 2 } },
  { championName: 'Renata Glasc', planetType: 'ringed', materialCost: { dark_matter: 1, nebula_quartz: 2 } },
  { championName: 'Zeri', planetType: 'ringed', materialCost: { stardust: 2, solar_essence: 1 } },
  { championName: 'Akshan', planetType: 'ringed', materialCost: { stardust: 2, solar_essence: 1 } },
  { championName: 'Yasuo', planetType: 'ringed', materialCost: { stardust: 2, nebula_quartz: 1 } },
  { championName: 'Yone', planetType: 'ringed', materialCost: { void_shard: 1, stardust: 2 } },
  { championName: 'Zed', planetType: 'ringed', materialCost: { void_shard: 2, stardust: 1 } },
  { championName: 'Sylas', planetType: 'ringed', materialCost: { nebula_quartz: 2, void_shard: 1 } },
  { championName: 'Twitch', planetType: 'ringed', materialCost: { void_shard: 1, stardust: 2 } },
]

const homePlanetMap = new Map<string, ChampionHomePlanetConfig>()
for (const config of CHAMPION_HOME_PLANETS) {
  if (!homePlanetMap.has(config.championName)) {
    homePlanetMap.set(config.championName, config)
  }
}

export function getHomePlanetConfig(championName: string): ChampionHomePlanetConfig | undefined {
  return homePlanetMap.get(championName)
}
