import type { TraitDefinition, TraitId } from '../types'

// 15 TFT-inspired trait definitions with 4 activation thresholds each
export const TRAIT_DEFINITIONS: TraitDefinition[] = [
  {
    id: 'celestial',
    name: 'Celestial',
    icon: 'game-icons:ringed-planet',
    color: '#a0c8ff',
    thresholds: [
      { count: 2, bonus: 'CPS +8%', effects: [{ type: 'cps', multiplier: 1.08 }] },
      { count: 4, bonus: 'CPS +18%', effects: [{ type: 'cps', multiplier: 1.18 }] },
      { count: 6, bonus: 'CPS +30%', effects: [{ type: 'cps', multiplier: 1.3 }] },
      { count: 8, bonus: 'CPS +45%', effects: [{ type: 'cps', multiplier: 1.45 }] },
    ],
  },
  {
    id: 'arcanist',
    name: 'Arcanist',
    icon: 'game-icons:magic-swirl',
    color: '#b060e0',
    thresholds: [
      { count: 2, bonus: 'DPS +10%', effects: [{ type: 'dps', multiplier: 1.1 }] },
      { count: 4, bonus: 'DPS +22%', effects: [{ type: 'dps', multiplier: 1.22 }] },
      { count: 6, bonus: 'DPS +35%', effects: [{ type: 'dps', multiplier: 1.35 }] },
      { count: 8, bonus: 'DPS +50%', effects: [{ type: 'dps', multiplier: 1.5 }] },
    ],
  },
  {
    id: 'assassin',
    name: 'Assassin',
    icon: 'game-icons:crescent-blade',
    color: '#c83030',
    thresholds: [
      { count: 2, bonus: 'DPS +15%', effects: [{ type: 'dps', multiplier: 1.15 }] },
      { count: 4, bonus: 'DPS +28%', effects: [{ type: 'dps', multiplier: 1.28 }] },
      { count: 6, bonus: 'DPS +45%', effects: [{ type: 'dps', multiplier: 1.45 }] },
      { count: 8, bonus: 'DPS +65%', effects: [{ type: 'dps', multiplier: 1.65 }] },
    ],
  },
  {
    id: 'enchanter',
    name: 'Enchanter',
    icon: 'game-icons:fairy-wand',
    color: '#40d080',
    thresholds: [
      { count: 2, bonus: 'Power +10%', effects: [{ type: 'power', multiplier: 1.1 }] },
      { count: 4, bonus: 'Power +20%', effects: [{ type: 'power', multiplier: 1.2 }] },
      { count: 6, bonus: 'Power +35%', effects: [{ type: 'power', multiplier: 1.35 }] },
      { count: 8, bonus: 'Power +50%', effects: [{ type: 'power', multiplier: 1.5 }] },
    ],
  },
  {
    id: 'duelist',
    name: 'Duelist',
    icon: 'game-icons:crossed-swords',
    color: '#e8b040',
    thresholds: [
      { count: 2, bonus: 'DPS +12%', effects: [{ type: 'dps', multiplier: 1.12 }] },
      { count: 4, bonus: 'DPS +25%', effects: [{ type: 'dps', multiplier: 1.25 }] },
      { count: 6, bonus: 'DPS +40%', effects: [{ type: 'dps', multiplier: 1.4 }] },
      { count: 8, bonus: 'DPS +58%', effects: [{ type: 'dps', multiplier: 1.58 }] },
    ],
  },
  {
    id: 'guardian',
    name: 'Guardian',
    icon: 'game-icons:shield',
    color: '#5080d0',
    thresholds: [
      { count: 2, bonus: 'Power +8%', effects: [{ type: 'power', multiplier: 1.08 }] },
      { count: 4, bonus: 'Power +18%', effects: [{ type: 'power', multiplier: 1.18 }] },
      { count: 6, bonus: 'Power +30%', effects: [{ type: 'power', multiplier: 1.3 }] },
      { count: 8, bonus: 'Power +45%', effects: [{ type: 'power', multiplier: 1.45 }] },
    ],
  },
  {
    id: 'challenger',
    name: 'Challenger',
    icon: 'game-icons:trophy',
    color: '#ff8020',
    thresholds: [
      { count: 2, bonus: 'Power +10%', effects: [{ type: 'power', multiplier: 1.1 }] },
      { count: 4, bonus: 'Power +22%', effects: [{ type: 'power', multiplier: 1.22 }] },
      { count: 6, bonus: 'Power +38%', effects: [{ type: 'power', multiplier: 1.38 }] },
      { count: 8, bonus: 'Power +58%', effects: [{ type: 'power', multiplier: 1.58 }] },
    ],
  },
  {
    id: 'phantom',
    name: 'Phantom',
    icon: 'game-icons:ghost',
    color: '#9060c0',
    thresholds: [
      { count: 2, bonus: 'CPS +10%', effects: [{ type: 'cps', multiplier: 1.1 }] },
      { count: 4, bonus: 'CPS +22%', effects: [{ type: 'cps', multiplier: 1.22 }] },
      { count: 6, bonus: 'CPS +35%', effects: [{ type: 'cps', multiplier: 1.35 }] },
      { count: 8, bonus: 'CPS +52%', effects: [{ type: 'cps', multiplier: 1.52 }] },
    ],
  },
  {
    id: 'moonlight',
    name: 'Moonlight',
    icon: 'game-icons:moon',
    color: '#7090d8',
    thresholds: [
      { count: 2, bonus: 'CPS +8%', effects: [{ type: 'cps', multiplier: 1.08 }] },
      { count: 4, bonus: 'CPS +16%', effects: [{ type: 'cps', multiplier: 1.16 }] },
      { count: 6, bonus: 'CPS +27%', effects: [{ type: 'cps', multiplier: 1.27 }] },
      { count: 8, bonus: 'CPS +42%', effects: [{ type: 'cps', multiplier: 1.42 }] },
    ],
  },
  {
    id: 'dark_star',
    name: 'Dark Star',
    icon: 'game-icons:black-hole-bolas',
    color: '#7040b0',
    thresholds: [
      { count: 2, bonus: 'Power +12%', effects: [{ type: 'power', multiplier: 1.12 }] },
      { count: 4, bonus: 'Power +25%', effects: [{ type: 'power', multiplier: 1.25 }] },
      { count: 6, bonus: 'Power +42%', effects: [{ type: 'power', multiplier: 1.42 }] },
      { count: 8, bonus: 'Power +62%', effects: [{ type: 'power', multiplier: 1.62 }] },
    ],
  },
  {
    id: 'elderwood',
    name: 'Elderwood',
    icon: 'game-icons:oak-leaf',
    color: '#508040',
    thresholds: [
      { count: 2, bonus: 'CPS +10%', effects: [{ type: 'cps', multiplier: 1.1 }] },
      { count: 4, bonus: 'CPS +20%', effects: [{ type: 'cps', multiplier: 1.2 }] },
      { count: 6, bonus: 'CPS +32%', effects: [{ type: 'cps', multiplier: 1.32 }] },
      { count: 8, bonus: 'CPS +48%', effects: [{ type: 'cps', multiplier: 1.48 }] },
    ],
  },
  {
    id: 'reaper',
    name: 'Reaper',
    icon: 'game-icons:skull-crossed-bones',
    color: '#806040',
    thresholds: [
      { count: 2, bonus: 'DPS +10%', effects: [{ type: 'dps', multiplier: 1.1 }] },
      { count: 4, bonus: 'DPS +22%', effects: [{ type: 'dps', multiplier: 1.22 }] },
      { count: 6, bonus: 'DPS +38%', effects: [{ type: 'dps', multiplier: 1.38 }] },
      { count: 8, bonus: 'DPS +58%', effects: [{ type: 'dps', multiplier: 1.58 }] },
    ],
  },
  {
    id: 'invoker',
    name: 'Invoker',
    icon: 'game-icons:spell-book',
    color: '#60c0c0',
    thresholds: [
      { count: 2, bonus: 'CPS +8%', effects: [{ type: 'cps', multiplier: 1.08 }] },
      { count: 4, bonus: 'CPS +8%, Power +12%', effects: [{ type: 'cps', multiplier: 1.08 }, { type: 'power', multiplier: 1.12 }] },
      { count: 6, bonus: 'CPS +20%, Power +18%', effects: [{ type: 'cps', multiplier: 1.2 }, { type: 'power', multiplier: 1.18 }] },
      { count: 8, bonus: 'CPS +30%, Power +30%', effects: [{ type: 'cps', multiplier: 1.3 }, { type: 'power', multiplier: 1.3 }] },
    ],
  },
  {
    id: 'jade',
    name: 'Jade',
    icon: 'game-icons:gem-pendant',
    color: '#30a060',
    thresholds: [
      { count: 2, bonus: 'CPS +8%', effects: [{ type: 'cps', multiplier: 1.08 }] },
      { count: 4, bonus: 'CPS +16%', effects: [{ type: 'cps', multiplier: 1.16 }] },
      { count: 6, bonus: 'CPS +28%', effects: [{ type: 'cps', multiplier: 1.28 }] },
      { count: 8, bonus: 'CPS +42%', effects: [{ type: 'cps', multiplier: 1.42 }] },
    ],
  },
  {
    id: 'astral',
    name: 'Astral',
    icon: 'game-icons:star-formation',
    color: '#f0c040',
    thresholds: [
      { count: 2, bonus: 'Power +8%', effects: [{ type: 'power', multiplier: 1.08 }] },
      { count: 4, bonus: 'Power +16%', effects: [{ type: 'power', multiplier: 1.16 }] },
      { count: 6, bonus: 'Power +28%', effects: [{ type: 'power', multiplier: 1.28 }] },
      { count: 8, bonus: 'Power +42%', effects: [{ type: 'power', multiplier: 1.42 }] },
    ],
  },
]

// Fast lookup by id
export const TRAIT_BY_ID: Record<TraitId, TraitDefinition> = Object.fromEntries(
  TRAIT_DEFINITIONS.map((t) => [t.id, t]),
) as Record<TraitId, TraitDefinition>

// Champion → traits mapping (origins remain in championOrigins.ts)
// Each champion can have 1–3 traits; assignment is thematic
export const CHAMPION_TRAITS: Record<string, TraitId[]> = {
  // ── Celestial ────────────────────────────────────────────────────────────
  'Aurelion Sol': ['celestial', 'astral'],
  Bard: ['celestial'],
  Zilean: ['celestial', 'moonlight'],
  Zoe: ['celestial', 'astral'],
  Soraka: ['celestial', 'enchanter'],
  Lux: ['celestial', 'jade'],
  Kayle: ['celestial'],
  Thresh: ['celestial', 'reaper'],
  Kindred: ['celestial', 'phantom', 'moonlight'],
  Xayah: ['celestial'],
  Rakan: ['celestial', 'enchanter'],
  Taliyah: ['celestial', 'invoker'],
  Janna: ['celestial', 'enchanter'],
  Aurora: ['celestial', 'moonlight'],

  // ── Arcanist ─────────────────────────────────────────────────────────────
  Viktor: ['arcanist', 'invoker'],
  "Vel'koz": ['arcanist', 'dark_star'],
  Orianna: ['arcanist'],
  Syndra: ['arcanist', 'invoker'],
  Veigar: ['arcanist'],
  Vex: ['arcanist'],
  Ziggs: ['arcanist'],
  Kassadin: ['arcanist'],
  Leblanc: ['arcanist'],
  Lissandra: ['arcanist'],
  'Twisted Fate': ['arcanist', 'astral'],
  Ryze: ['arcanist', 'invoker'],
  Brand: ['arcanist'],
  Jhin: ['arcanist', 'reaper'],
  Singed: ['arcanist', 'challenger'],
  Sylas: ['arcanist', 'challenger'],

  // ── Assassin ─────────────────────────────────────────────────────────────
  Akali: ['assassin'],
  Katarina: ['assassin'],
  Talon: ['assassin'],
  Zed: ['assassin'],
  Evelynn: ['assassin', 'moonlight'],
  'Kha Zix': ['assassin'],
  Rengar: ['assassin'],
  Shaco: ['assassin'],
  Pyke: ['assassin', 'reaper'],
  Naafiri: ['assassin', 'dark_star'],
  Fizz: ['assassin'],
  Qiyana: ['assassin'],
  Akshan: ['assassin', 'jade'],
  "Kai'sa": ['assassin', 'dark_star'],

  // ── Enchanter ────────────────────────────────────────────────────────────
  Lulu: ['enchanter'],
  Sona: ['enchanter', 'invoker'],
  Nami: ['enchanter', 'invoker'],
  Yuumi: ['enchanter'],
  Karma: ['enchanter', 'invoker'],
  Milio: ['enchanter'],
  Seraphine: ['enchanter', 'moonlight'],
  Ivern: ['enchanter', 'elderwood'],
  Taric: ['enchanter', 'jade'],
  'Renata Glasc': ['enchanter'],
  Hwei: ['enchanter', 'invoker'],
  Mel: ['enchanter'],

  // ── Duelist ──────────────────────────────────────────────────────────────
  Fiora: ['duelist'],
  Camille: ['duelist'],
  Irelia: ['duelist'],
  Riven: ['duelist'],
  Yasuo: ['duelist'],
  Yone: ['duelist', 'moonlight'],
  Jax: ['duelist'],
  'Master Yi': ['duelist'],
  Nilah: ['duelist'],
  'Lee Sin': ['duelist'],
  Samira: ['duelist', 'challenger'],
  Tryndamere: ['duelist', 'challenger'],
  Wukong: ['duelist', 'jade'],
  Zeri: ['duelist', 'astral'],
  Graves: ['duelist'],
  Tristana: ['duelist', 'challenger'],
  Caitlyn: ['duelist'],

  // ── Guardian ─────────────────────────────────────────────────────────────
  Malphite: ['guardian'],
  Leona: ['guardian', 'jade'],
  Nautilus: ['guardian'],
  Braum: ['guardian', 'jade'],
  Alistar: ['guardian'],
  Ornn: ['guardian', 'jade'],
  'Tahm Kench': ['guardian'],
  Rammus: ['guardian'],
  Shen: ['guardian'],
  Galio: ['guardian'],
  "K'sante": ['guardian'],
  Poppy: ['guardian', 'jade'],
  Blitzcrank: ['guardian'],
  Rell: ['guardian', 'jade'],
  'Cho Gath': ['guardian', 'dark_star'],
  Nasus: ['guardian', 'reaper'],

  // ── Challenger ───────────────────────────────────────────────────────────
  Draven: ['challenger', 'dark_star'],
  Jinx: ['challenger'],
  Darius: ['challenger'],
  Urgot: ['challenger', 'reaper'],
  Vi: ['challenger'],
  Olaf: ['challenger'],
  Aatrox: ['challenger', 'dark_star'],
  Kled: ['challenger'],
  Ambessa: ['challenger'],
  Briar: ['challenger'],
  Warwick: ['challenger', 'elderwood'],
  Renekton: ['challenger'],
  Sett: ['challenger'],
  Gangplank: ['challenger'],
  'Dr. Mundo': ['challenger'],
  Gragas: ['challenger'],
  Sejuani: ['challenger', 'moonlight'],
  Zac: ['challenger'],
  Sivir: ['challenger'],
  Rumble: ['challenger'],

  // ── Phantom ──────────────────────────────────────────────────────────────
  Hecarim: ['phantom', 'elderwood', 'reaper'],
  Mordekaiser: ['phantom', 'dark_star'],
  Karthus: ['phantom', 'reaper'],
  Nocturne: ['phantom', 'dark_star'],
  Maokai: ['phantom', 'elderwood'],
  Yorick: ['phantom', 'reaper'],
  Gwen: ['phantom'],
  Viego: ['phantom', 'dark_star', 'reaper'],
  Elise: ['phantom', 'moonlight'],
  Kalista: ['phantom', 'reaper'],
  FiddleSticks: ['phantom', 'reaper'],
  Amumu: ['phantom', 'elderwood'],

  // ── Moonlight ────────────────────────────────────────────────────────────
  Diana: ['moonlight'],
  Aphelios: ['moonlight'],
  Morgana: ['moonlight'],
  'Nunu A. Willump': ['moonlight', 'elderwood'],
  Neeko: ['moonlight'],
  Vayne: ['assassin', 'moonlight'],
  Ashe: ['moonlight'],
  Smolder: ['moonlight', 'astral'],

  // ── Dark Star ────────────────────────────────────────────────────────────
  Varus: ['dark_star'],
  Kayn: ['dark_star'],
  BelVeth: ['dark_star'],
  Sion: ['dark_star'],
  'Kog\'maw': ['dark_star'],
  'Rek Sai': ['dark_star'],
  Vladimir: ['dark_star'],
  Skarner: ['dark_star'],
  Swain: ['dark_star', 'invoker'],

  // ── Elderwood ────────────────────────────────────────────────────────────
  Gnar: ['elderwood'],
  Lillia: ['elderwood'],
  Anivia: ['elderwood'],
  Udyr: ['elderwood'],
  Nidalee: ['elderwood'],
  Volibear: ['elderwood'],
  Quinn: ['elderwood'],
  Shyvana: ['elderwood'],
  Teemo: ['elderwood'],
  Trundle: ['elderwood'],

  // ── Reaper ───────────────────────────────────────────────────────────────
  Senna: ['reaper'],
  Lucian: ['reaper'],
  'Miss Fortune': ['reaper'],
  Twitch: ['assassin', 'reaper'],

  // ── Invoker ──────────────────────────────────────────────────────────────
  Malzahar: ['invoker'],
  Cassiopeia: ['invoker'],
  Xerath: ['invoker'],
  Azir: ['invoker', 'astral'],
  Zyra: ['invoker'],
  Illaoi: ['invoker'],

  // ── Jade ─────────────────────────────────────────────────────────────────
  'Jarvan IV': ['jade'],
  'Xin Zhao': ['jade'],
  Garen: ['jade'],
  Jayce: ['jade'],
  Pantheon: ['jade'],

  // ── Astral ───────────────────────────────────────────────────────────────
  Ahri: ['astral'],
  Kennen: ['astral'],
  Annie: ['astral'],
  Corki: ['astral'],
  Heimerdinger: ['astral'],
  Ekko: ['assassin', 'astral'],
  Ezreal: ['astral'],
}
