import type {
  ChampionRole,
  ChampionOrigin,
  TraitId,
  PlanetType,
  ChampionTierId,
} from '../types'

export interface ChampionDef {
  role: ChampionRole
  origin: ChampionOrigin
  traits: TraitId[]
  planetType: PlanetType
  materialCost: Record<string, number>
  // Champion Tier — the single tier per champion (Galaxy/Champion Tier system).
  // Maps to a star level (★1..★12) via CHAMPION_TIERS in championTiers.ts and drives the
  // Shop/Select tier grouping, the ★N card badge, the recruit cost (getChampionChimesPrice)
  // and which galaxy the champion spawns in.
  championTier: ChampionTierId
}

export const CHAMPION_DATA: Record<string, ChampionDef> = {
  // ── Rocky ──────────────────────────────────────────────────────────────────
  Malphite:         { role: 'top',     origin: 'Ixtal',         traits: ['guardian'],                     planetType: 'rocky',     materialCost: { nebula_quartz: 3 },                        championTier: 'lone_wanderer'     },
  Taliyah:          { role: 'mid',     origin: 'Shurima',       traits: ['celestial', 'invoker'],         planetType: 'rocky',     materialCost: { nebula_quartz: 2, stardust: 1 },           championTier: 'void_sovereign'      },
  Galio:            { role: 'mid',     origin: 'Demacia',       traits: ['guardian'],                     planetType: 'rocky',     materialCost: { nebula_quartz: 2, moon_crystal: 1 },       championTier: 'lone_wanderer'    },
  Skarner:          { role: 'jungle',  origin: 'Shurima',       traits: ['dark_star'],                    planetType: 'rocky',     materialCost: { nebula_quartz: 2, stardust: 2 },           championTier: 'void_sovereign'       },
  Rammus:           { role: 'jungle',  origin: 'Shurima',       traits: ['guardian'],                     planetType: 'rocky',     materialCost: { nebula_quartz: 2 },                        championTier: 'lone_wanderer' },
  Ornn:             { role: 'top',     origin: 'The Freljord',  traits: ['guardian', 'jade'],             planetType: 'rocky',     materialCost: { nebula_quartz: 3, solar_essence: 1 },      championTier: 'void_sovereign'       },
  Sion:             { role: 'top',     origin: 'Noxus',         traits: ['dark_star'],                    planetType: 'rocky',     materialCost: { nebula_quartz: 2, stardust: 1 },           championTier: 'rift_keeper'   },
  Poppy:            { role: 'top',     origin: 'Demacia',       traits: ['guardian', 'jade'],             planetType: 'rocky',     materialCost: { nebula_quartz: 1, stardust: 2 },           championTier: 'lone_wanderer'     },
  Gnar:             { role: 'top',     origin: 'Bandle City',   traits: ['elderwood'],                    planetType: 'rocky',     materialCost: { nebula_quartz: 2, moon_crystal: 1 },       championTier: 'astral_warden'      },
  Urgot:            { role: 'top',     origin: 'Zaun',          traits: ['challenger', 'reaper'],         planetType: 'rocky',     materialCost: { nebula_quartz: 2, solar_essence: 1 },      championTier: 'nebula_sage'      },
  Yorick:           { role: 'top',     origin: 'Shadow Isles',  traits: ['phantom', 'reaper'],            planetType: 'rocky',     materialCost: { nebula_quartz: 2, void_shard: 1 },         championTier: 'astral_warden'     },
  Darius:           { role: 'top',     origin: 'Noxus',         traits: ['challenger'],                   planetType: 'rocky',     materialCost: { nebula_quartz: 2, stardust: 1 },           championTier: 'lone_wanderer'    },
  Garen:            { role: 'top',     origin: 'Demacia',       traits: ['jade'],                         planetType: 'rocky',     materialCost: { nebula_quartz: 1, stardust: 2 },           championTier: 'lone_wanderer'    },
  Pantheon:         { role: 'support', origin: 'Targon',        traits: ['jade'],                         planetType: 'rocky',     materialCost: { nebula_quartz: 2, solar_essence: 1 },      championTier: 'rift_keeper'   },
  Sett:             { role: 'top',     origin: 'Ionia',         traits: ['challenger'],                   planetType: 'rocky',     materialCost: { nebula_quartz: 2, stardust: 1 },           championTier: 'rift_keeper'   },
  Rell:             { role: 'support', origin: 'Noxus',         traits: ['guardian', 'jade'],             planetType: 'rocky',     materialCost: { nebula_quartz: 2, moon_crystal: 1 },       championTier: 'cosmic_sovereign'     },
  Trundle:          { role: 'jungle',  origin: 'The Freljord',  traits: ['elderwood'],                    planetType: 'rocky',     materialCost: { nebula_quartz: 2, stardust: 1 },           championTier: 'astral_warden'     },
  Volibear:         { role: 'top',     origin: 'The Freljord',  traits: ['elderwood'],                    planetType: 'rocky',     materialCost: { nebula_quartz: 2, solar_essence: 1 },      championTier: 'rift_keeper' },
  Olaf:             { role: 'jungle',  origin: 'The Freljord',  traits: ['challenger'],                   planetType: 'rocky',     materialCost: { nebula_quartz: 2, stardust: 1 },           championTier: 'nebula_sage'     },
  Wukong:           { role: 'top',     origin: 'Ionia',         traits: ['duelist', 'jade'],              planetType: 'rocky',     materialCost: { nebula_quartz: 1, stardust: 2 },           championTier: 'nebula_sage'      },
  Alistar:          { role: 'support', origin: 'Noxus',         traits: ['guardian'],                     planetType: 'rocky',     materialCost: { nebula_quartz: 2, stardust: 1 },           championTier: 'lone_wanderer' },
  Amumu:            { role: 'jungle',  origin: 'Shurima',       traits: ['phantom', 'elderwood'],         planetType: 'rocky',     materialCost: { nebula_quartz: 1, moon_crystal: 2 },       championTier: 'lone_wanderer'    },

  // ── Ice ─────────────────────────────────────────────────────────────────────
  Lissandra:        { role: 'mid',     origin: 'The Freljord',  traits: ['arcanist'],                     planetType: 'ice',       materialCost: { moon_crystal: 3 },                         championTier: 'astral_warden'       },
  Anivia:           { role: 'mid',     origin: 'The Freljord',  traits: ['elderwood'],                    planetType: 'ice',       materialCost: { moon_crystal: 2, nebula_quartz: 1 },       championTier: 'lone_wanderer'     },
  'Nunu A. Willump':{ role: 'jungle',  origin: 'The Freljord',  traits: ['moonlight', 'elderwood'],       planetType: 'ice',       materialCost: { moon_crystal: 2, stardust: 1 },            championTier: 'lone_wanderer'    },
  Sejuani:          { role: 'jungle',  origin: 'The Freljord',  traits: ['challenger', 'moonlight'],      planetType: 'ice',       materialCost: { moon_crystal: 2, nebula_quartz: 1 },       championTier: 'lone_wanderer'    },
  Braum:            { role: 'support', origin: 'The Freljord',  traits: ['guardian', 'jade'],             planetType: 'ice',       materialCost: { moon_crystal: 2, stardust: 1 },            championTier: 'nebula_sage'      },
  Ashe:             { role: 'adc',     origin: 'The Freljord',  traits: ['moonlight'],                    planetType: 'ice',       materialCost: { moon_crystal: 2, stardust: 1 },            championTier: 'lone_wanderer'    },
  Tryndamere:       { role: 'top',     origin: 'The Freljord',  traits: ['duelist', 'challenger'],        planetType: 'ice',       materialCost: { moon_crystal: 2, solar_essence: 1 },       championTier: 'rift_keeper' },
  Udyr:             { role: 'jungle',  origin: 'The Freljord',  traits: ['elderwood'],                    planetType: 'ice',       materialCost: { moon_crystal: 2, nebula_quartz: 1 },       championTier: 'rift_keeper' },
  Gragas:           { role: 'jungle',  origin: 'The Freljord',  traits: ['challenger'],                   planetType: 'ice',       materialCost: { moon_crystal: 2, stardust: 1 },            championTier: 'rift_keeper'      },
  Vex:              { role: 'mid',     origin: 'Bandle City',   traits: ['arcanist'],                     planetType: 'ice',       materialCost: { moon_crystal: 2, void_shard: 1 },          championTier: 'nebula_sage'       },
  Aurora:           { role: 'mid',     origin: 'Bandle City',   traits: ['celestial', 'moonlight'],       planetType: 'ice',       materialCost: { moon_crystal: 3, stardust: 1 },            championTier: 'void_sovereign'     },
  Lillia:           { role: 'jungle',  origin: 'Ionia',         traits: ['elderwood'],                    planetType: 'ice',       materialCost: { moon_crystal: 2, stardust: 1 },            championTier: 'void_sovereign'       },
  Quinn:            { role: 'top',     origin: 'Demacia',       traits: ['elderwood'],                    planetType: 'ice',       materialCost: { moon_crystal: 1, stardust: 2 },            championTier: 'void_sovereign'       },
  Kennen:           { role: 'top',     origin: 'Ionia',         traits: ['astral'],                       planetType: 'ice',       materialCost: { moon_crystal: 2, solar_essence: 1 },       championTier: 'void_sovereign'       },
  Shen:             { role: 'top',     origin: 'Ionia',         traits: ['guardian'],                     planetType: 'ice',       materialCost: { moon_crystal: 2, stardust: 1 },            championTier: 'nebula_sage'      },
  Janna:            { role: 'support', origin: 'Zaun',          traits: ['celestial', 'enchanter'],       planetType: 'ice',       materialCost: { moon_crystal: 2, stardust: 1 },            championTier: 'rift_keeper'   },
  Taric:            { role: 'support', origin: 'Targon',        traits: ['enchanter', 'jade'],            planetType: 'ice',       materialCost: { moon_crystal: 3, nebula_quartz: 1 },       championTier: 'rift_keeper' },

  // ── Gas Giant ───────────────────────────────────────────────────────────────
  'Aurelion Sol':   { role: 'mid',     origin: 'Targon',        traits: ['celestial', 'astral'],          planetType: 'gas-giant', materialCost: { stardust: 3, nebula_quartz: 1 },           championTier: 'void_sovereign'      },
  Zoe:              { role: 'mid',     origin: 'Targon',        traits: ['celestial', 'astral'],          planetType: 'gas-giant', materialCost: { stardust: 2, moon_crystal: 2 },            championTier: 'cosmic_sovereign'       },
  Xerath:           { role: 'mid',     origin: 'Shurima',       traits: ['invoker'],                      planetType: 'gas-giant', materialCost: { stardust: 3, solar_essence: 1 },           championTier: 'lone_wanderer' },
  "Vel'koz":        { role: 'mid',     origin: 'The Void',      traits: ['arcanist', 'dark_star'],        planetType: 'gas-giant', materialCost: { stardust: 2, void_shard: 1 },              championTier: 'void_sovereign'       },
  Ryze:             { role: 'mid',     origin: 'Shurima',       traits: ['arcanist', 'invoker'],          planetType: 'gas-giant', materialCost: { stardust: 2, nebula_quartz: 1 },           championTier: 'void_sovereign'      },
  Zilean:           { role: 'support', origin: 'Shurima',       traits: ['celestial', 'moonlight'],       planetType: 'gas-giant', materialCost: { stardust: 3, dark_matter: 1 },             championTier: 'rift_keeper' },
  Viktor:           { role: 'mid',     origin: 'Zaun',          traits: ['arcanist', 'invoker'],          planetType: 'gas-giant', materialCost: { stardust: 2, nebula_quartz: 2 },           championTier: 'astral_warden'      },
  Orianna:          { role: 'mid',     origin: 'Piltover',      traits: ['arcanist'],                     planetType: 'gas-giant', materialCost: { stardust: 2, moon_crystal: 1 },            championTier: 'rift_keeper'      },
  Heimerdinger:     { role: 'mid',     origin: 'Piltover',      traits: ['astral'],                       planetType: 'gas-giant', materialCost: { stardust: 2, nebula_quartz: 1 },           championTier: 'rift_keeper'      },
  Jayce:            { role: 'top',     origin: 'Piltover',      traits: ['jade'],                         planetType: 'gas-giant', materialCost: { stardust: 2, solar_essence: 1 },           championTier: 'astral_warden'       },
  Blitzcrank:       { role: 'support', origin: 'Zaun',          traits: ['guardian'],                     planetType: 'gas-giant', materialCost: { stardust: 2, nebula_quartz: 1 },           championTier: 'lone_wanderer' },
  Rumble:           { role: 'top',     origin: 'Bandle City',   traits: ['challenger'],                   planetType: 'gas-giant', materialCost: { stardust: 2, solar_essence: 1 },           championTier: 'void_sovereign'       },
  Corki:            { role: 'mid',     origin: 'Bandle City',   traits: ['astral'],                       planetType: 'gas-giant', materialCost: { stardust: 2, moon_crystal: 1 },            championTier: 'lone_wanderer'    },
  Ziggs:            { role: 'mid',     origin: 'Bandle City',   traits: ['arcanist'],                     planetType: 'gas-giant', materialCost: { stardust: 3, solar_essence: 1 },           championTier: 'cosmic_sovereign'       },
  Hwei:             { role: 'mid',     origin: 'Ionia',         traits: ['enchanter', 'invoker'],         planetType: 'gas-giant', materialCost: { stardust: 2, moon_crystal: 1 },            championTier: 'void_sovereign'     },
  Seraphine:        { role: 'support', origin: 'Piltover',      traits: ['enchanter', 'moonlight'],       planetType: 'gas-giant', materialCost: { stardust: 2, moon_crystal: 1 },            championTier: 'nebula_sage'     },
  Sona:             { role: 'support', origin: 'Demacia',       traits: ['enchanter', 'invoker'],         planetType: 'gas-giant', materialCost: { stardust: 2, moon_crystal: 1 },            championTier: 'lone_wanderer'    },
  Lux:              { role: 'support', origin: 'Demacia',       traits: ['celestial', 'jade'],            planetType: 'gas-giant', materialCost: { stardust: 3, moon_crystal: 1 },            championTier: 'lone_wanderer'   },
  Karma:            { role: 'support', origin: 'Ionia',         traits: ['enchanter', 'invoker'],         planetType: 'gas-giant', materialCost: { stardust: 2, nebula_quartz: 1 },           championTier: 'nebula_sage'      },
  Smolder:          { role: 'adc',     origin: 'Targon',        traits: ['moonlight', 'astral'],          planetType: 'gas-giant', materialCost: { stardust: 2, solar_essence: 1 },           championTier: 'void_sovereign'     },

  // ── Lava ────────────────────────────────────────────────────────────────────
  Brand:            { role: 'support', origin: 'The Freljord',  traits: ['arcanist'],                     planetType: 'lava',      materialCost: { solar_essence: 2, stardust: 2 },           championTier: 'lone_wanderer'   },
  Shyvana:          { role: 'jungle',  origin: 'Demacia',       traits: ['elderwood'],                    planetType: 'lava',      materialCost: { solar_essence: 1, nebula_quartz: 2 },      championTier: 'astral_warden'    },
  Annie:            { role: 'mid',     origin: 'Noxus',         traits: ['astral'],                       planetType: 'lava',      materialCost: { solar_essence: 1, stardust: 2 },           championTier: 'lone_wanderer'    },
  Renekton:         { role: 'top',     origin: 'Shurima',       traits: ['challenger'],                   planetType: 'lava',      materialCost: { solar_essence: 2, stardust: 1 },           championTier: 'void_sovereign'       },
  Aatrox:           { role: 'top',     origin: 'Shurima',       traits: ['challenger', 'dark_star'],      planetType: 'lava',      materialCost: { solar_essence: 2, void_shard: 1 },         championTier: 'astral_warden'       },
  Kled:             { role: 'top',     origin: 'Noxus',         traits: ['challenger'],                   planetType: 'lava',      materialCost: { solar_essence: 1, nebula_quartz: 2 },      championTier: 'void_sovereign'       },
  Warwick:          { role: 'jungle',  origin: 'Zaun',          traits: ['challenger', 'elderwood'],      planetType: 'lava',      materialCost: { solar_essence: 1, stardust: 2 },           championTier: 'lone_wanderer'   },
  Singed:           { role: 'top',     origin: 'Zaun',          traits: ['arcanist', 'challenger'],       planetType: 'lava',      materialCost: { solar_essence: 2, nebula_quartz: 1 },      championTier: 'void_sovereign'       },
  'Dr. Mundo':      { role: 'top',     origin: 'Zaun',          traits: ['challenger'],                   planetType: 'lava',      materialCost: { solar_essence: 1, stardust: 2 },           championTier: 'lone_wanderer'    },
  Draven:           { role: 'adc',     origin: 'Noxus',         traits: ['challenger', 'dark_star'],      planetType: 'lava',      materialCost: { solar_essence: 2, stardust: 1 },           championTier: 'nebula_sage'         },
  Samira:           { role: 'adc',     origin: 'Noxus',         traits: ['duelist', 'challenger'],        planetType: 'lava',      materialCost: { solar_essence: 2, stardust: 1 },           championTier: 'rift_keeper'      },
  Riven:            { role: 'top',     origin: 'Noxus',         traits: ['duelist'],                      planetType: 'lava',      materialCost: { solar_essence: 1, nebula_quartz: 2 },      championTier: 'void_sovereign'        },
  Ambessa:          { role: 'top',     origin: 'Noxus',         traits: ['challenger'],                   planetType: 'lava',      materialCost: { solar_essence: 2, nebula_quartz: 1 },      championTier: 'cosmic_sovereign'  },
  Mel:              { role: 'mid',     origin: 'Noxus',         traits: ['enchanter'],                    planetType: 'lava',      materialCost: { solar_essence: 1, stardust: 2 },           championTier: 'cosmic_sovereign'  },
  Swain:            { role: 'support', origin: 'Noxus',         traits: ['dark_star', 'invoker'],         planetType: 'lava',      materialCost: { solar_essence: 2, void_shard: 1 },         championTier: 'astral_warden'     },
  Viego:            { role: 'jungle',  origin: 'Shadow Isles',  traits: ['phantom', 'dark_star', 'reaper'], planetType: 'lava',   materialCost: { solar_essence: 2, dark_matter: 1 },        championTier: 'cosmic_sovereign'    },
  Mordekaiser:      { role: 'top',     origin: 'Noxus',         traits: ['phantom', 'dark_star'],         planetType: 'lava',      materialCost: { solar_essence: 2, void_shard: 1 },         championTier: 'lone_wanderer' },

  // ── Ocean ────────────────────────────────────────────────────────────────────
  Nami:             { role: 'support', origin: 'Bilgewater',    traits: ['enchanter', 'invoker'],         planetType: 'ocean',     materialCost: { moon_crystal: 2, stardust: 1 },            championTier: 'nebula_sage'      },
  Nautilus:         { role: 'support', origin: 'Bilgewater',    traits: ['guardian'],                     planetType: 'ocean',     materialCost: { nebula_quartz: 2, moon_crystal: 1 },       championTier: 'void_sovereign'        },
  Fizz:             { role: 'mid',     origin: 'Bilgewater',    traits: ['assassin'],                     planetType: 'ocean',     materialCost: { stardust: 2, moon_crystal: 1 },            championTier: 'lone_wanderer' },
  'Tahm Kench':     { role: 'top',     origin: 'Bilgewater',    traits: ['guardian'],                     planetType: 'ocean',     materialCost: { moon_crystal: 2, nebula_quartz: 1 },       championTier: 'cosmic_sovereign'    },
  Pyke:             { role: 'support', origin: 'Bilgewater',    traits: ['assassin', 'reaper'],           planetType: 'ocean',     materialCost: { moon_crystal: 2, void_shard: 1 },          championTier: 'nebula_sage'     },
  Nilah:            { role: 'adc',     origin: 'Bilgewater',    traits: ['duelist'],                      planetType: 'ocean',     materialCost: { moon_crystal: 2, stardust: 1 },            championTier: 'void_sovereign'    },
  Illaoi:           { role: 'top',     origin: 'Bilgewater',    traits: ['invoker'],                      planetType: 'ocean',     materialCost: { nebula_quartz: 2, moon_crystal: 1 },       championTier: 'nebula_sage'      },
  Gangplank:        { role: 'top',     origin: 'Bilgewater',    traits: ['challenger'],                   planetType: 'ocean',     materialCost: { moon_crystal: 2, stardust: 1 },            championTier: 'rift_keeper'      },
  'Miss Fortune':   { role: 'adc',     origin: 'Bilgewater',    traits: ['reaper'],                       planetType: 'ocean',     materialCost: { stardust: 2, moon_crystal: 1 },            championTier: 'lone_wanderer'     },
  'Twisted Fate':   { role: 'mid',     origin: 'Bilgewater',    traits: ['arcanist', 'astral'],           planetType: 'ocean',     materialCost: { moon_crystal: 1, stardust: 2 },            championTier: 'void_sovereign'       },
  Graves:           { role: 'jungle',  origin: 'Bilgewater',    traits: ['duelist'],                      planetType: 'ocean',     materialCost: { moon_crystal: 2, nebula_quartz: 1 },       championTier: 'astral_warden'      },
  Tristana:         { role: 'adc',     origin: 'Bandle City',   traits: ['duelist', 'challenger'],        planetType: 'ocean',     materialCost: { stardust: 2, moon_crystal: 1 },            championTier: 'rift_keeper' },
  Zac:              { role: 'jungle',  origin: 'Zaun',          traits: ['challenger'],                   planetType: 'ocean',     materialCost: { moon_crystal: 2, nebula_quartz: 1 },       championTier: 'cosmic_sovereign'    },
  Maokai:           { role: 'support', origin: 'Shadow Isles',  traits: ['phantom', 'elderwood'],         planetType: 'ocean',     materialCost: { moon_crystal: 2, stardust: 1 },            championTier: 'void_sovereign'       },
  Neeko:            { role: 'mid',     origin: 'Ixtal',         traits: ['moonlight'],                    planetType: 'ocean',     materialCost: { moon_crystal: 2, stardust: 1 },            championTier: 'astral_warden'       },
  Yuumi:            { role: 'support', origin: 'Bandle City',   traits: ['enchanter'],                    planetType: 'ocean',     materialCost: { stardust: 2, moon_crystal: 1 },            championTier: 'rift_keeper'     },
  Lulu:             { role: 'support', origin: 'Bandle City',   traits: ['enchanter'],                    planetType: 'ocean',     materialCost: { moon_crystal: 2, stardust: 1 },            championTier: 'astral_warden'       },
  Milio:            { role: 'support', origin: 'Ixtal',         traits: ['enchanter'],                    planetType: 'ocean',     materialCost: { stardust: 2, moon_crystal: 1 },            championTier: 'void_sovereign'       },

  // ── Desert ───────────────────────────────────────────────────────────────────
  Azir:             { role: 'mid',     origin: 'Shurima',       traits: ['invoker', 'astral'],            planetType: 'desert',    materialCost: { solar_essence: 2, void_shard: 1 },         championTier: 'astral_warden'       },
  Sivir:            { role: 'adc',     origin: 'Shurima',       traits: ['challenger'],                   planetType: 'desert',    materialCost: { stardust: 3, solar_essence: 1 },           championTier: 'lone_wanderer'    },
  Nasus:            { role: 'top',     origin: 'Shurima',       traits: ['guardian', 'reaper'],           planetType: 'desert',    materialCost: { solar_essence: 2, stardust: 1 },           championTier: 'rift_keeper'   },
  Rengar:           { role: 'jungle',  origin: 'Ixtal',         traits: ['assassin'],                     planetType: 'desert',    materialCost: { solar_essence: 1, stardust: 2 },           championTier: 'void_sovereign'        },
  Naafiri:          { role: 'mid',     origin: 'Shurima',       traits: ['assassin', 'dark_star'],        planetType: 'desert',    materialCost: { solar_essence: 2, nebula_quartz: 1 },      championTier: 'cosmic_sovereign'  },
  'Rek Sai':        { role: 'jungle',  origin: 'The Void',      traits: ['dark_star'],                    planetType: 'desert',    materialCost: { solar_essence: 1, nebula_quartz: 2 },      championTier: 'void_sovereign'        },
  Kassadin:         { role: 'mid',     origin: 'The Void',      traits: ['arcanist'],                     planetType: 'desert',    materialCost: { void_shard: 2, solar_essence: 1 },         championTier: 'rift_keeper'      },
  Malzahar:         { role: 'mid',     origin: 'The Void',      traits: ['invoker'],                      planetType: 'desert',    materialCost: { void_shard: 2, stardust: 1 },              championTier: 'astral_warden'       },
  'Cho Gath':       { role: 'top',     origin: 'The Void',      traits: ['guardian', 'dark_star'],        planetType: 'desert',    materialCost: { void_shard: 2, nebula_quartz: 1 },         championTier: 'lone_wanderer' },
  'Kha Zix':        { role: 'jungle',  origin: 'The Void',      traits: ['assassin'],                     planetType: 'desert',    materialCost: { void_shard: 1, solar_essence: 2 },         championTier: 'void_sovereign'       },
  "Kog'maw":        { role: 'adc',     origin: 'The Void',      traits: ['dark_star'],                    planetType: 'desert',    materialCost: { void_shard: 1, stardust: 2 },              championTier: 'astral_warden'        },
  BelVeth:          { role: 'jungle',  origin: 'The Void',      traits: ['dark_star'],                    planetType: 'desert',    materialCost: { void_shard: 2, dark_matter: 1 },           championTier: 'cosmic_sovereign'  },
  'Xin Zhao':       { role: 'jungle',  origin: 'Demacia',       traits: ['jade'],                         planetType: 'desert',    materialCost: { solar_essence: 1, stardust: 2 },           championTier: 'rift_keeper' },
  'Jarvan IV':      { role: 'jungle',  origin: 'Demacia',       traits: ['jade'],                         planetType: 'desert',    materialCost: { solar_essence: 2, nebula_quartz: 1 },      championTier: 'rift_keeper'      },
  Jax:              { role: 'top',     origin: 'Shurima',       traits: ['duelist'],                      planetType: 'desert',    materialCost: { solar_essence: 1, stardust: 2 },           championTier: 'lone_wanderer' },
  'Lee Sin':        { role: 'jungle',  origin: 'Ionia',         traits: ['duelist'],                      planetType: 'desert',    materialCost: { solar_essence: 2, stardust: 1 },           championTier: 'lone_wanderer' },
  'Master Yi':      { role: 'jungle',  origin: 'Ionia',         traits: ['duelist'],                      planetType: 'desert',    materialCost: { solar_essence: 1, stardust: 2 },           championTier: 'lone_wanderer'    },
  Irelia:           { role: 'top',     origin: 'Ionia',         traits: ['duelist'],                      planetType: 'desert',    materialCost: { solar_essence: 2, moon_crystal: 1 },       championTier: 'nebula_sage'      },
  "K'sante":        { role: 'top',     origin: 'Shurima',       traits: ['guardian'],                     planetType: 'desert',    materialCost: { solar_essence: 2, nebula_quartz: 1 },      championTier: 'cosmic_sovereign'  },

  // ── Jungle ───────────────────────────────────────────────────────────────────
  Ivern:            { role: 'jungle',  origin: 'Ionia',         traits: ['enchanter', 'elderwood'],       planetType: 'jungle',    materialCost: { stardust: 2, nebula_quartz: 1 },           championTier: 'astral_warden'       },
  Nidalee:          { role: 'jungle',  origin: 'Ixtal',         traits: ['elderwood'],                    planetType: 'jungle',    materialCost: { moon_crystal: 1, stardust: 2 },            championTier: 'nebula_sage'      },
  Zyra:             { role: 'support', origin: 'Ixtal',         traits: ['invoker'],                      planetType: 'jungle',    materialCost: { stardust: 2, nebula_quartz: 1 },           championTier: 'astral_warden'     },
  Elise:            { role: 'jungle',  origin: 'Shadow Isles',  traits: ['phantom', 'moonlight'],         planetType: 'jungle',    materialCost: { stardust: 2, void_shard: 1 },              championTier: 'astral_warden'       },
  Teemo:            { role: 'top',     origin: 'Bandle City',   traits: ['elderwood'],                    planetType: 'jungle',    materialCost: { stardust: 2, moon_crystal: 1 },            championTier: 'lone_wanderer'   },
  Gwen:             { role: 'top',     origin: 'Shadow Isles',  traits: ['phantom'],                      planetType: 'jungle',    materialCost: { stardust: 2, moon_crystal: 1 },            championTier: 'astral_warden'       },
  Briar:            { role: 'jungle',  origin: 'Noxus',         traits: ['challenger'],                   planetType: 'jungle',    materialCost: { stardust: 2, void_shard: 1 },              championTier: 'cosmic_sovereign'  },
  FiddleSticks:     { role: 'jungle',  origin: 'Shadow Isles',  traits: ['phantom', 'reaper'],            planetType: 'jungle',    materialCost: { void_shard: 1, stardust: 2 },              championTier: 'lone_wanderer' },
  Shaco:            { role: 'jungle',  origin: 'Shadow Isles',  traits: ['assassin'],                     planetType: 'jungle',    materialCost: { stardust: 2, void_shard: 1 },              championTier: 'nebula_sage'     },
  Hecarim:          { role: 'jungle',  origin: 'Shadow Isles',  traits: ['phantom', 'elderwood', 'reaper'], planetType: 'jungle', materialCost: { stardust: 2, nebula_quartz: 1 },           championTier: 'astral_warden'       },
  Nocturne:         { role: 'jungle',  origin: 'Shadow Isles',  traits: ['phantom', 'dark_star'],         planetType: 'jungle',    materialCost: { void_shard: 1, stardust: 2 },              championTier: 'nebula_sage'     },
  Kayn:             { role: 'jungle',  origin: 'Ionia',         traits: ['dark_star'],                    planetType: 'jungle',    materialCost: { stardust: 2, void_shard: 1 },              championTier: 'nebula_sage'      },
  Evelynn:          { role: 'jungle',  origin: 'Shadow Isles',  traits: ['assassin', 'moonlight'],        planetType: 'jungle',    materialCost: { stardust: 2, void_shard: 1 },              championTier: 'lone_wanderer' },
  Ekko:             { role: 'jungle',  origin: 'Zaun',          traits: ['assassin', 'astral'],           planetType: 'jungle',    materialCost: { stardust: 2, nebula_quartz: 1 },           championTier: 'rift_keeper'      },
  Vi:               { role: 'jungle',  origin: 'Zaun',          traits: ['challenger'],                   planetType: 'jungle',    materialCost: { stardust: 2, nebula_quartz: 1 },           championTier: 'rift_keeper' },
  Camille:          { role: 'top',     origin: 'Piltover',      traits: ['duelist'],                      planetType: 'jungle',    materialCost: { stardust: 2, solar_essence: 1 },           championTier: 'astral_warden'       },
  Fiora:            { role: 'top',     origin: 'Demacia',       traits: ['duelist'],                      planetType: 'jungle',    materialCost: { stardust: 2, moon_crystal: 1 },            championTier: 'astral_warden'       },
  Qiyana:           { role: 'mid',     origin: 'Ixtal',         traits: ['assassin'],                     planetType: 'jungle',    materialCost: { stardust: 2, nebula_quartz: 1 },           championTier: 'void_sovereign'       },
  Akali:            { role: 'mid',     origin: 'Ionia',         traits: ['assassin'],                     planetType: 'jungle',    materialCost: { stardust: 2, solar_essence: 1 },           championTier: 'lone_wanderer'     },
  Katarina:         { role: 'mid',     origin: 'Noxus',         traits: ['assassin'],                     planetType: 'jungle',    materialCost: { stardust: 2, solar_essence: 1 },           championTier: 'rift_keeper'      },
  Talon:            { role: 'mid',     origin: 'Noxus',         traits: ['assassin'],                     planetType: 'jungle',    materialCost: { stardust: 2, void_shard: 1 },              championTier: 'nebula_sage'       },

  // ── Ringed ───────────────────────────────────────────────────────────────────
  Soraka:           { role: 'support', origin: 'Targon',        traits: ['celestial', 'enchanter'],       planetType: 'ringed',    materialCost: { stardust: 2, dark_matter: 1 },             championTier: 'lone_wanderer'   },
  Syndra:           { role: 'mid',     origin: 'Ionia',         traits: ['arcanist', 'invoker'],          planetType: 'ringed',    materialCost: { void_shard: 2, nebula_quartz: 1 },         championTier: 'nebula_sage'       },
  Diana:            { role: 'jungle',  origin: 'Targon',        traits: ['moonlight'],                    planetType: 'ringed',    materialCost: { moon_crystal: 3, dark_matter: 1 },         championTier: 'lone_wanderer'    },
  Leona:            { role: 'support', origin: 'Targon',        traits: ['guardian', 'jade'],             planetType: 'ringed',    materialCost: { solar_essence: 2, stardust: 1 },           championTier: 'lone_wanderer'    },
  Kayle:            { role: 'top',     origin: 'Targon',        traits: ['celestial'],                    planetType: 'ringed',    materialCost: { solar_essence: 2, dark_matter: 1 },        championTier: 'astral_warden'       },
  Morgana:          { role: 'support', origin: 'Targon',        traits: ['moonlight'],                    planetType: 'ringed',    materialCost: { void_shard: 2, dark_matter: 1 },           championTier: 'rift_keeper'   },
  Thresh:           { role: 'support', origin: 'Shadow Isles',  traits: ['celestial', 'reaper'],          planetType: 'ringed',    materialCost: { void_shard: 2, moon_crystal: 1 },          championTier: 'astral_warden'     },
  Kindred:          { role: 'jungle',  origin: 'The Freljord',  traits: ['celestial', 'phantom', 'moonlight'], planetType: 'ringed', materialCost: { dark_matter: 1, stardust: 2 },          championTier: 'void_sovereign'       },
  Karthus:          { role: 'jungle',  origin: 'Shadow Isles',  traits: ['phantom', 'reaper'],            planetType: 'ringed',    materialCost: { void_shard: 2, dark_matter: 1 },           championTier: 'nebula_sage'      },
  Vladimir:         { role: 'mid',     origin: 'Noxus',         traits: ['dark_star'],                    planetType: 'ringed',    materialCost: { solar_essence: 2, void_shard: 1 },         championTier: 'nebula_sage'      },
  Cassiopeia:       { role: 'mid',     origin: 'Noxus',         traits: ['invoker'],                      planetType: 'ringed',    materialCost: { void_shard: 2, solar_essence: 1 },         championTier: 'astral_warden'       },
  Leblanc:          { role: 'mid',     origin: 'Noxus',         traits: ['arcanist'],                     planetType: 'ringed',    materialCost: { dark_matter: 1, stardust: 2 },             championTier: 'rift_keeper'      },
  Ahri:             { role: 'mid',     origin: 'Ionia',         traits: ['astral'],                       planetType: 'ringed',    materialCost: { stardust: 2, moon_crystal: 1 },            championTier: 'lone_wanderer'    },
  Veigar:           { role: 'mid',     origin: 'Bandle City',   traits: ['arcanist'],                     planetType: 'ringed',    materialCost: { dark_matter: 1, void_shard: 1 },           championTier: 'lone_wanderer' },
  Aphelios:         { role: 'adc',     origin: 'Targon',        traits: ['moonlight'],                    planetType: 'ringed',    materialCost: { dark_matter: 1, moon_crystal: 2 },         championTier: 'nebula_sage'         },
  Jhin:             { role: 'adc',     origin: 'Ionia',         traits: ['arcanist', 'reaper'],           planetType: 'ringed',    materialCost: { dark_matter: 1, stardust: 2 },             championTier: 'nebula_sage'         },
  Varus:            { role: 'adc',     origin: 'Ionia',         traits: ['dark_star'],                    planetType: 'ringed',    materialCost: { void_shard: 1, stardust: 2 },              championTier: 'astral_warden'      },
  "Kai'sa":         { role: 'adc',     origin: 'The Void',      traits: ['assassin', 'dark_star'],        planetType: 'ringed',    materialCost: { void_shard: 1, stardust: 2 },              championTier: 'lone_wanderer' },
  Ezreal:           { role: 'adc',     origin: 'Piltover',      traits: ['astral'],                       planetType: 'ringed',    materialCost: { stardust: 2, nebula_quartz: 1 },           championTier: 'lone_wanderer' },
  Lucian:           { role: 'adc',     origin: 'Demacia',       traits: ['reaper'],                       planetType: 'ringed',    materialCost: { solar_essence: 1, stardust: 2 },           championTier: 'rift_keeper'   },
  Jinx:             { role: 'adc',     origin: 'Zaun',          traits: ['challenger'],                   planetType: 'ringed',    materialCost: { stardust: 3, solar_essence: 1 },           championTier: 'nebula_sage'       },
  Caitlyn:          { role: 'adc',     origin: 'Piltover',      traits: ['duelist'],                      planetType: 'ringed',    materialCost: { stardust: 2, nebula_quartz: 1 },           championTier: 'lone_wanderer'    },
  Vayne:            { role: 'top',     origin: 'Demacia',       traits: ['assassin', 'moonlight'],        planetType: 'ringed',    materialCost: { stardust: 2, void_shard: 1 },              championTier: 'nebula_sage'      },
  Kalista:          { role: 'adc',     origin: 'Shadow Isles',  traits: ['phantom', 'reaper'],            planetType: 'ringed',    materialCost: { void_shard: 2, dark_matter: 1 },           championTier: 'astral_warden'        },
  Xayah:            { role: 'adc',     origin: 'Ionia',         traits: ['celestial'],                    planetType: 'ringed',    materialCost: { stardust: 2, moon_crystal: 1 },            championTier: 'astral_warden'      },
  Rakan:            { role: 'support', origin: 'Ionia',         traits: ['celestial', 'enchanter'],       planetType: 'ringed',    materialCost: { stardust: 2, moon_crystal: 1 },            championTier: 'void_sovereign'        },
  Senna:            { role: 'support', origin: 'Demacia',       traits: ['reaper'],                       planetType: 'ringed',    materialCost: { void_shard: 1, stardust: 2 },              championTier: 'nebula_sage'     },
  'Renata Glasc':   { role: 'support', origin: 'Zaun',          traits: ['enchanter'],                    planetType: 'ringed',    materialCost: { dark_matter: 1, nebula_quartz: 2 },        championTier: 'cosmic_sovereign'  },
  Zeri:             { role: 'adc',     origin: 'Zaun',          traits: ['duelist', 'astral'],            planetType: 'ringed',    materialCost: { stardust: 2, solar_essence: 1 },           championTier: 'cosmic_sovereign'  },
  Akshan:           { role: 'mid',     origin: 'Shurima',       traits: ['assassin', 'jade'],             planetType: 'ringed',    materialCost: { stardust: 2, solar_essence: 1 },           championTier: 'nebula_sage'        },
  Yasuo:            { role: 'mid',     origin: 'Ionia',         traits: ['duelist'],                      planetType: 'ringed',    materialCost: { stardust: 2, nebula_quartz: 1 },           championTier: 'lone_wanderer' },
  Yone:             { role: 'mid',     origin: 'Ionia',         traits: ['duelist', 'moonlight'],         planetType: 'ringed',    materialCost: { void_shard: 1, stardust: 2 },              championTier: 'nebula_sage'      },
  Zed:              { role: 'mid',     origin: 'Ionia',         traits: ['assassin'],                     planetType: 'ringed',    materialCost: { void_shard: 2, stardust: 1 },              championTier: 'lone_wanderer' },
  Sylas:            { role: 'mid',     origin: 'Demacia',       traits: ['arcanist', 'challenger'],       planetType: 'ringed',    materialCost: { nebula_quartz: 2, void_shard: 1 },         championTier: 'rift_keeper'       },
  Twitch:           { role: 'adc',     origin: 'Zaun',          traits: ['assassin', 'reaper'],           planetType: 'ringed',    materialCost: { void_shard: 1, stardust: 2 },              championTier: 'rift_keeper'       },
}

export function getChampionNames(): string[] {
  return Object.keys(CHAMPION_DATA)
}
