import type { ChampionRole } from '../types'

export const CHAMPION_ROLES: Record<string, ChampionRole[]> = {
  Aatrox: ['top'],
  Ahri: ['mid'],
  Akali: ['mid', 'top'],
  Akshan: ['mid', 'top'],
  Alistar: ['support'],
  Ambessa: ['top'],
  Amumu: ['jungle', 'support'],
  Anivia: ['mid'],
  Annie: ['mid', 'support'],
  Aphelios: ['adc'],
  Ashe: ['adc', 'support'],
  'Aurelion Sol': ['mid'],
  Aurora: ['mid', 'top'],
  Azir: ['mid'],
  BelVeth: ['jungle'],
  Blitzcrank: ['support'],
  Brand: ['support', 'mid'],
  Braum: ['support'],
  Briar: ['jungle'],
  Caitlyn: ['adc'],
  Camille: ['top'],
  Cassiopeia: ['mid'],
  'Cho Gath': ['top', 'mid'],
  Corki: ['mid'],
  Darius: ['top'],
  Diana: ['jungle', 'mid'],
  'Dr. Mundo': ['top', 'jungle'],
  Draven: ['adc'],
  Ekko: ['jungle', 'mid'],
  Elise: ['jungle'],
  Evelynn: ['jungle'],
  Ezreal: ['adc'],
  FiddleSticks: ['jungle', 'support'],
  Fiora: ['top'],
  Fizz: ['mid'],
  Galio: ['mid', 'support'],
  Gangplank: ['top', 'mid'],
  Garen: ['top'],
  Gnar: ['top'],
  Gragas: ['jungle', 'top'],
  Graves: ['jungle'],
  Gwen: ['top'],
  Hecarim: ['jungle'],
  Heimerdinger: ['mid', 'top'],
  Hwei: ['mid', 'support'],
  Illaoi: ['top'],
  Irelia: ['top', 'mid'],
  Ivern: ['jungle'],
  Janna: ['support'],
  'Jarvan IV': ['jungle'],
  Jax: ['top', 'jungle'],
  Jayce: ['top', 'mid'],
  Jhin: ['adc'],
  Jinx: ['adc'],
  "K'sante": ['top'],
  "Kai'sa": ['adc'],
  Kalista: ['adc'],
  Karma: ['support', 'mid'],
  Karthus: ['jungle', 'mid'],
  Kassadin: ['mid'],
  Katarina: ['mid'],
  Kayle: ['top'],
  Kayn: ['jungle'],
  Kennen: ['top'],
  'Kha Zix': ['jungle'],
  Kindred: ['jungle'],
  Kled: ['top'],
  "Kog'maw": ['adc'],
  Leblanc: ['mid'],
  'Lee Sin': ['jungle'],
  Leona: ['support'],
  Lillia: ['jungle'],
  Lissandra: ['mid'],
  Lucian: ['adc', 'mid'],
  Lulu: ['support'],
  Lux: ['support', 'mid'],
  Malphite: ['top', 'support'],
  Malzahar: ['mid'],
  Maokai: ['support', 'jungle'],
  'Master Yi': ['jungle'],
  Mel: ['mid'],
  Milio: ['support'],
  'Miss Fortune': ['adc'],
  Mordekaiser: ['top'],
  Morgana: ['support', 'mid'],
  Naafiri: ['mid', 'jungle'],
  Nami: ['support'],
  Nasus: ['top'],
  Nautilus: ['support'],
  Neeko: ['mid', 'support'],
  Nidalee: ['jungle'],
  Nilah: ['adc'],
  Nocturne: ['jungle'],
  'Nunu A. Willump': ['jungle'],
  Olaf: ['jungle', 'top'],
  Orianna: ['mid'],
  Ornn: ['top'],
  Pantheon: ['support', 'mid'],
  Poppy: ['top', 'jungle'],
  Pyke: ['support'],
  Qiyana: ['mid', 'jungle'],
  Quinn: ['top'],
  Rakan: ['support'],
  Rammus: ['jungle'],
  'Rek Sai': ['jungle'],
  Rell: ['support'],
  'Renata Glasc': ['support'],
  Renekton: ['top'],
  Rengar: ['jungle', 'top'],
  Riven: ['top'],
  Rumble: ['top', 'mid'],
  Ryze: ['mid'],
  Samira: ['adc'],
  Sejuani: ['jungle'],
  Senna: ['support', 'adc'],
  Seraphine: ['support', 'mid'],
  Sett: ['top', 'support'],
  Shaco: ['jungle', 'support'],
  Shen: ['top'],
  Shyvana: ['jungle'],
  Singed: ['top'],
  Sion: ['top'],
  Sivir: ['adc'],
  Skarner: ['jungle'],
  Smolder: ['adc', 'mid'],
  Sona: ['support'],
  Soraka: ['support'],
  Swain: ['support', 'mid'],
  Sylas: ['mid'],
  Syndra: ['mid'],
  'Tahm Kench': ['top', 'support'],
  Taliyah: ['mid', 'jungle'],
  Talon: ['mid', 'jungle'],
  Taric: ['support'],
  Teemo: ['top'],
  Thresh: ['support'],
  Tristana: ['adc', 'mid'],
  Trundle: ['jungle', 'top'],
  Tryndamere: ['top'],
  'Twisted Fate': ['mid'],
  Twitch: ['adc'],
  Udyr: ['jungle', 'top'],
  Urgot: ['top'],
  Varus: ['adc', 'mid'],
  Vayne: ['top', 'adc'],
  Veigar: ['mid'],
  "Vel'koz": ['mid', 'support'],
  Vex: ['mid'],
  Vi: ['jungle'],
  Viego: ['jungle'],
  Viktor: ['mid'],
  Vladimir: ['mid', 'top'],
  Volibear: ['top', 'jungle'],
  Warwick: ['jungle', 'top'],
  Wukong: ['top', 'jungle'],
  Xayah: ['adc'],
  Xerath: ['mid', 'support'],
  'Xin Zhao': ['jungle'],
  Yasuo: ['mid', 'top'],
  Yone: ['mid', 'top'],
  Yorick: ['top'],
  Yuumi: ['support'],
  Zac: ['jungle'],
  Zed: ['mid'],
  Zeri: ['adc'],
  Ziggs: ['mid', 'adc'],
  Zilean: ['support', 'mid'],
  Zoe: ['mid'],
  Zyra: ['support', 'mid'],
}

export function getChampionRoles(name: string): ChampionRole[] {
  return CHAMPION_ROLES[name] ?? []
}
