import type { ChampionRole } from '../types'

export const CHAMPION_ROLES: Record<string, ChampionRole> = {
  Aatrox: 'top',
  Ahri: 'mid',
  Akali: 'mid',
  Akshan: 'mid',
  Alistar: 'support',
  Ambessa: 'top',
  Amumu: 'jungle',
  Anivia: 'mid',
  Annie: 'mid',
  Aphelios: 'adc',
  Ashe: 'adc',
  'Aurelion Sol': 'mid',
  Aurora: 'mid',
  Azir: 'mid',
  BelVeth: 'jungle',
  Blitzcrank: 'support',
  Brand: 'support',
  Braum: 'support',
  Briar: 'jungle',
  Caitlyn: 'adc',
  Camille: 'top',
  Cassiopeia: 'mid',
  'Cho Gath': 'top',
  Corki: 'mid',
  Darius: 'top',
  Diana: 'jungle',
  'Dr. Mundo': 'top',
  Draven: 'adc',
  Ekko: 'jungle',
  Elise: 'jungle',
  Evelynn: 'jungle',
  Ezreal: 'adc',
  FiddleSticks: 'jungle',
  Fiora: 'top',
  Fizz: 'mid',
  Galio: 'mid',
  Gangplank: 'top',
  Garen: 'top',
  Gnar: 'top',
  Gragas: 'jungle',
  Graves: 'jungle',
  Gwen: 'top',
  Hecarim: 'jungle',
  Heimerdinger: 'mid',
  Hwei: 'mid',
  Illaoi: 'top',
  Irelia: 'top',
  Ivern: 'jungle',
  Janna: 'support',
  'Jarvan IV': 'jungle',
  Jax: 'top',
  Jayce: 'top',
  Jhin: 'adc',
  Jinx: 'adc',
  "K'sante": 'top',
  "Kai'sa": 'adc',
  Kalista: 'adc',
  Karma: 'support',
  Karthus: 'jungle',
  Kassadin: 'mid',
  Katarina: 'mid',
  Kayle: 'top',
  Kayn: 'jungle',
  Kennen: 'top',
  'Kha Zix': 'jungle',
  Kindred: 'jungle',
  Kled: 'top',
  "Kog'maw": 'adc',
  Leblanc: 'mid',
  'Lee Sin': 'jungle',
  Leona: 'support',
  Lillia: 'jungle',
  Lissandra: 'mid',
  Lucian: 'adc',
  Lulu: 'support',
  Lux: 'support',
  Malphite: 'top',
  Malzahar: 'mid',
  Maokai: 'support',
  'Master Yi': 'jungle',
  Mel: 'mid',
  Milio: 'support',
  'Miss Fortune': 'adc',
  Mordekaiser: 'top',
  Morgana: 'support',
  Naafiri: 'mid',
  Nami: 'support',
  Nasus: 'top',
  Nautilus: 'support',
  Neeko: 'mid',
  Nidalee: 'jungle',
  Nilah: 'adc',
  Nocturne: 'jungle',
  'Nunu A. Willump': 'jungle',
  Olaf: 'jungle',
  Orianna: 'mid',
  Ornn: 'top',
  Pantheon: 'support',
  Poppy: 'top',
  Pyke: 'support',
  Qiyana: 'mid',
  Quinn: 'top',
  Rakan: 'support',
  Rammus: 'jungle',
  'Rek Sai': 'jungle',
  Rell: 'support',
  'Renata Glasc': 'support',
  Renekton: 'top',
  Rengar: 'jungle',
  Riven: 'top',
  Rumble: 'top',
  Ryze: 'mid',
  Samira: 'adc',
  Sejuani: 'jungle',
  Senna: 'support',
  Seraphine: 'support',
  Sett: 'top',
  Shaco: 'jungle',
  Shen: 'top',
  Shyvana: 'jungle',
  Singed: 'top',
  Sion: 'top',
  Sivir: 'adc',
  Skarner: 'jungle',
  Smolder: 'adc',
  Sona: 'support',
  Soraka: 'support',
  Swain: 'support',
  Sylas: 'mid',
  Syndra: 'mid',
  'Tahm Kench': 'top',
  Taliyah: 'mid',
  Talon: 'mid',
  Taric: 'support',
  Teemo: 'top',
  Thresh: 'support',
  Tristana: 'adc',
  Trundle: 'jungle',
  Tryndamere: 'top',
  'Twisted Fate': 'mid',
  Twitch: 'adc',
  Udyr: 'jungle',
  Urgot: 'top',
  Varus: 'adc',
  Vayne: 'top',
  Veigar: 'mid',
  "Vel'koz": 'mid',
  Vex: 'mid',
  Vi: 'jungle',
  Viego: 'jungle',
  Viktor: 'mid',
  Vladimir: 'mid',
  Volibear: 'top',
  Warwick: 'jungle',
  Wukong: 'top',
  Xayah: 'adc',
  Xerath: 'mid',
  'Xin Zhao': 'jungle',
  Yasuo: 'mid',
  Yone: 'mid',
  Yorick: 'top',
  Yuumi: 'support',
  Zac: 'jungle',
  Zed: 'mid',
  Zeri: 'adc',
  Ziggs: 'mid',
  Zilean: 'support',
  Zoe: 'mid',
  Zyra: 'support',
}

export function getChampionRoles(name: string): ChampionRole[] {
  const role = CHAMPION_ROLES[name]
  return role ? [role] : []
}
