// AUTO-GENERATED from public/img/skins/ — folder name → skin file basenames.
// Regenerate when skin images are added/removed (see scripts in repo history).
// Keys are the PascalCase folder names; resolve a champion name to its folder
// with toSkinFolder() from '@/utils/championSkins'.

export const CHAMPION_SKINS: Readonly<Record<string, readonly string[]>> = {
  Aatrox: ['OriginalSkin', 'JusticarSkin', 'MechaSkin', 'VictoriousSkin'],
  Ahri: ['OriginalSkin', 'ArcadeSkin', 'ArcanaSkin', 'CovenSkin', 'DynastySkin', 'ElderwoodSkin', 'KDASkin', 'MidnightSkin', 'PopstarSkin', 'StarGuardianSkin'],
  Akali: ['OriginalSkin', 'All-starSkin', 'BloodMoonSkin', 'CrimsonSkin', 'HeadhunterSkin', 'InfernalSkin', 'KDASkin', 'NurseSkin', 'PROJECTSkin', 'SilverfangSkin', 'StingerSkin'],
  Alistar: ['OriginalSkin', 'BlackSkin', 'ConquerorSkin', 'GoldenSkin', 'HextechSkin', 'InfernalSkin', 'LonghornSkin', 'MatadorSkin', 'UnchainedSkin'],
  Amumu: ['OriginalSkin', 'Almost-PromKingSkin', 'EmumuSkin', 'HeartacheSkin', 'HextechSkin', 'LittleKnightSkin', 'PharaohSkin', 'PorcelainSkin', 'PumpkinPrinceSkin', 'Re-GiftedSkin', 'SadRobotSkin', 'VancouverSkin'],
  Anivia: ['OriginalSkin', 'BirdofPreySkin', 'BlackfrostSkin', 'FestivalQueenSkin', 'HextechSkin', 'NoxusHunterSkin', 'PapercraftSkin', 'TeamSpiritSkin'],
  Annie: ['OriginalSkin', 'AnnieinWonderlandSkin', 'FrankenTibbersSkin', 'FrostfireSkin', 'GothSkin', 'HextechSkin', 'LunarBeastSkin', 'PromQueenSkin', 'RedRidingSkin', 'ReverseSkin', 'SuperGalaxySkin', 'SweetheartSkin'],
  Aphelios: ['LunarBeastSkin'],
  Ashe: ['OriginalSkin', 'AmethystSkin', 'CrystalisMotusSkin', 'FaeDragonSkin', 'FreljordSkin', 'InfernalSkin', 'PROJECTSkin', 'SherwoodForestSkin', 'WoadSkin', 'Worlds2017Skin'],
  AurelionSol: ['OriginalSkin', 'AshenLordSkin', 'StormDragonSkin'],
  Azir: ['ElderwoodSkin', 'GravelordSkin'],
  BelVeth: ['CosmicMatriarchSkin'],
  Blitzcrank: ['OriginalSkin', 'BoomBoomSkin', 'DefinitelyNotSkin', 'GoalkeeperSkin', 'iBlitzcrankSkin', 'PiltoverCustomsSkin', 'RiotSkin', 'RustySkin', 'ZenithGamesSkin'],
  Brand: ['OriginalSkin', 'ApocalypticSkin', 'ArclightSkin', 'CryocoreSkin', 'EternalDragonSkin', 'PrestigeDebonairSkin', 'SpiritFireSkin', 'VandalSkin', 'ZombieSkin'],
  Braum: ['CrimeCitySkin', 'DragonslayerSkin', 'ElTigreSkin', 'SantaSkin'],
  Briar: ['OriginalSkin', 'PrimordianSkin', 'StreetDemonsSkin'],
  Caitlyn: ['OriginalSkin', 'ArcticWarfareSkin', 'HeadhunterSkin', 'OfficerSkin', 'PrestigeArcadeSkin', 'ResistanceSkin', 'SafariSkin', 'SheriffSkin'],
  Camille: ['OriginalSkin', 'ProgramSkin'],
  Cassiopeia: ['OriginalSkin', 'DesperadaSkin', 'EternumSkin', 'JadeFangSkin', 'MythicSkin', 'SirenSkin'],
  ChoGath: ['OriginalSkin', 'GentlemanSkin', 'JurassicSkin', 'LochNessSkin', 'NightmareSkin'],
  Corki: ['ArcadeSkin', 'AstronautSkin', 'HotRodSkin', 'IceTobogganSkin', 'RedBaronSkin', 'UFOSkin', 'UrfriderSkin'],
  Darius: ['OriginalSkin', 'DreadnovaSkin', 'LordSkin', 'LunarBeastSkin', 'WoadKingSkin'],
  Diana: ['BattleQueenSkin', 'PrestigeBattleQueenSkin'],
  Draven: ['OriginalSkin', 'DebonairSkin', 'FrightNightSkin', 'GladiatorSkin', 'LaIlusiC3B3nSkin', 'MechaKingdomsSkin', 'PrimetimeSkin', 'RuinedSkin', 'SantaSkin', 'SoulReaverSkin'],
  DrMundo: ['OriginalSkin', 'CorporateMundoSkin', 'ExecutionerMundoSkin', 'FrozenPrinceMundoSkin', 'Mr.MundoverseSkin', 'MundoMundoSkin', 'StreetDemonsSkin', 'ToxicSkin'],
  Ekko: ['OriginalSkin', 'FirelightSkin', 'PROJECTSkin', 'PulsefireSkin', 'SandstormSkin', 'StarGuardianSkin', 'TrickorTreatSkin'],
  Elise: ['OriginalSkin', 'BewitchingSkin', 'BloodMoonSkin', 'DeathBlossomSkin', 'SuperGalaxySkin', 'VictoriousSkin', 'WitheredRoseSkin'],
  Evelynn: ['OriginalSkin', 'BloodMoonSkin', 'KDASkin', 'MasqueradeSkin', 'PrestigeHighNoonSkin', 'PrestigeKDASkin', 'ShadowSkin', 'SoulFighterSkin'],
  Ezreal: ['OriginalSkin', 'ArcadeSkin', 'BattleAcademiaSkin', 'DebonairSkin', 'ExplorerSkin', 'FaerieCourtSkin', 'FrostedSkin', 'HEARTSTEELSkin', 'HeavenscaleSkin', 'NottinghamSkin', 'PorcelainProtectorSkin', 'PrestigeHeavenscaleSkin', 'PrestigePsyOpsSkin', 'PsyOpsSkin', 'PulsefireSkin', 'StarGuardianSkin', 'StrikerSkin'],
  FiddleSticks: ['OriginalSkin', 'BanditoSkin', 'DarkCandySkin', 'FiddleMeTimbersSkin', 'PraetorianSkin', 'PumpkinheadSkin', 'RisenSkin', 'SpectralSkin', 'SurprisePartySkin', 'UnionJackSkin'],
  Fiora: ['OriginalSkin', 'BattleQueenSkin', 'DragonmancerSkin', 'FaerieCourtSkin', 'HeadmistressSkin', 'HeartpiercerSkin', 'iGSkin', 'LunarBeastSkin', 'NightravenSkin', 'PoolPartySkin', 'PROJECTSkin', 'RoyalGuardSkin', 'SoaringSwordSkin'],
  Fizz: ['OriginalSkin', 'AtlanteanSkin', 'CottontailSkin', 'FishermanSkin', 'LittleDevilSkin', 'OmegaSquadSkin', 'PrestigeFuzzSkin', 'SuperGalaxySkin', 'TundraSkin', 'VoidSkin'],
  Galio: ['OriginalSkin', 'BirdioSkin', 'CommandoSkin', 'DebonairSkin', 'EnchantedSkin', 'GatekeeperSkin', 'HextechSkin'],
  Gangplank: ['OriginalSkin', 'CaptainSkin', 'DreadnovaSkin', 'GangplanktheBetrayerSkin', 'MinutemanSkin', 'SailorSkin', 'SpecialForcesSkin', 'SpookySkin', 'SultanSkin', 'ToySoldierSkin'],
  Garen: ['OriginalSkin', 'CommandoSkin', 'DemaciaViceSkin', 'DesertTrooperSkin', 'DreadknightSkin', 'God-KingSkin', 'MechaKingdomsSkin', 'PrestigeMechaKingdomsSkin', 'RuggedSkin', 'SanguineSkin', 'SteelLegionSkin', 'WarringKingdomsSkin'],
  Gnar: ['OriginalSkin', 'DinoSkin', 'ElderwoodSkin', 'GentlemanSkin', 'LaIlusiC3B3nSkin', 'SuperGalaxySkin'],
  Gragas: ['OriginalSkin', 'ArcticOpsSkin', 'Gragas,Esq.Skin', 'Gragas2CEsq.Skin', 'HighNoonSkin', 'HillbillySkin', 'OktoberfestSkin', 'SantaSkin', 'ScubaSkin', 'SpaceGrooveSkin', 'VandalSkin', 'WardenSkin'],
  Graves: ['OriginalSkin', 'BattleProfessorSkin', 'CrimeCitySkin', 'HiredGunSkin', 'JailbreakSkin', 'PoolPartySkin', 'PorcelainSkin', 'PraetorianSkin', 'RiotSkin', 'SnowDaySkin', 'VictoriousSkin'],
  Gwen: ['OriginalSkin', 'BattleQueenSkin', 'CafeCutiesSkin', 'SoulFighterSkin'],
  Hecarim: ['OriginalSkin', 'ArcadeSkin', 'ArcanaSkin', 'BloodKnightSkin', 'ElderwoodSkin', 'HeadlessSkin', 'HighNoonSkin', 'LancerZeroSkin', 'ReaperSkin', 'WinterblessedSkin'],
  Heimerdinger: ['OriginalSkin', 'AlienInvaderSkin', 'BlastZoneSkin', 'DragonTrainerSkin', 'HazmatSkin', 'PiltoverCustomsSkin', 'SnowmerdingerSkin'],
  Hwei: ['WinterblessedSkin'],
  Illaoi: ['OriginalSkin', 'BattleBearSkin', 'CosmicInvokerSkin', 'ResistanceSkin', 'SnowMoonSkin', 'VoidBringerSkin'],
  Irelia: ['OriginalSkin', 'AviatorSkin', 'FrostbladeSkin', 'HighNoonSkin', 'iGSkin', 'InfiltratorSkin', 'NightbladeSkin', 'OrderoftheLotusSkin', 'PorcelainSkin', 'PrestigePROJECTSkin', 'PROJECTSkin', 'SentinelSkin'],
  Ivern: ['OriginalSkin', 'AstronautSkin', 'DunkmasterSkin', 'OldGodSkin'],
  Janna: ['OriginalSkin', 'BattleQueenSkin', 'BewitchingSkin', 'CyberHaloSkin', 'ForecastSkin', 'FrostQueenSkin', 'HeavenscaleSkin', 'HextechSkin', 'PrestigeCyberHaloSkin', 'SacredSwordSkin', 'StarGuardianSkin', 'TempestSkin', 'VictoriousSkin'],
  JarvanIV: ['OriginalSkin', 'CommandoSkin', 'DarkforgeSkin', 'DarkStarSkin', 'DragonslayerSkin', 'HextechSkin', 'LunarBeastSkin', 'NightbringerSkin', 'VictoriousSkin', 'WarringKingdomsSkin'],
  Jax: ['OriginalSkin', 'AnglerSkin', 'ConquerorSkin', 'EmpyreanSkin', 'GodStaffSkin', 'JaximusSkin', 'MechaKingdomsSkin', 'NemesisSkin', 'NeoPAXSkin', 'PAXSkin', 'PrestigeConquerorSkin', 'PROJECTSkin', 'TempleSkin', 'TheMightySkin', 'VandalSkin'],
  Jayce: ['OriginalSkin', 'ArcaneSkin', 'DebonairSkin', 'ForsakenSkin', 'FullMetalSkin', 'ResistanceSkin', 'ZenithGamesSkin'],
  Jhin: ['OriginalSkin', 'BloodMoonSkin', 'DarkCosmicErasureSkin', 'DarkCosmicSkin', 'EmpyreanSkin', 'HighNoonSkin', 'PROJECTSkin', 'ShanHaiScrollsSkin', 'SoulFighterSkin'],
  Jinx: ['OriginalSkin', 'AmbitiousElfSkin', 'ArcaneSkin', 'BattleCatSkin', 'CafeCutiesSkin', 'FirecrackerSkin', 'OdysseySkin', 'PrestigeBattleCatSkin', 'PROJECTSkin', 'StarGuardianSkin'],
  Kaisa: ['OriginalSkin', 'ArcadeSkin', 'BulletAngelSkin', 'HeavenscaleSkin', 'iGSkin', 'InkshadowSkin', 'KDASkin', 'LagoonDragonSkin', 'PrestigeKDASkin', 'StarGuardianSkin'],
  Kalista: ['OriginalSkin', 'BloodMoonSkin', 'FaerieCourtSkin', 'MarauderSkin', 'Worlds2015Skin'],
  Karma: ['OriginalSkin', 'ConquerorSkin', 'DarkStarSkin', 'FaerieQueenSkin', 'OdysseySkin', 'OrderoftheLotusSkin', 'RuinedSkin', 'SakuraSkin', 'SunGoddessSkin', 'TraditionalSkin', 'WinterWonderSkin'],
  Karthus: ['OriginalSkin', 'ElderwoodSkin', 'GrimReaperSkin', 'KarthusLightsbaneSkin', 'PhantomSkin', 'StatueofKarthusSkin'],
  Kassadin: ['OriginalSkin', 'CosmicReaverSkin', 'CountSkin', 'DeepOneSkin', 'DragonmancerSkin', 'FestivalSkin', 'HarbingerSkin', 'HextechSkin', 'Pre-VoidSkin', 'ShockbladeSkin'],
  Katarina: ['OriginalSkin', 'BattleAcademiaSkin', 'BattleQueenSkin', 'BilgewaterSkin', 'DeathSwornSkin', 'FaerieCourtSkin', 'HighCommandSkin', 'HighNoonSkin', 'KittyCatSkin', 'MercenarySkin', 'PrestigeFaerieCourtSkin', 'PROJECTSkin', 'RedCardSkin', 'SandstormSkin', 'WarringKingdomsSkin'],
  Kayle: ['AetherWingSkin', 'BattlebornSkin', 'EmpyreanSkin', 'ImmortalJourneySkin', 'JudgmentSkin', 'PentakillSkin', 'PsyOpsSkin', 'RiotSkin', 'SilverSkin', 'TranscendedSkin', 'UnmaskedSkin', 'ViridianSkin'],
  Kayn: ['OriginalSkin', 'HEARTSTEELSkin', 'NightbringerSkin', 'OdysseySkin', 'PrestigeNightbringerSkin', 'SnowMoonSkin', 'SoulhunterSkin'],
  Kennen: ['OriginalSkin', 'ArcticOpsSkin', 'BloodMoonSkin', 'DeadlySkin', 'KarateSkin', 'KennenM.D.Skin', 'SwampMasterSkin'],
  KhaZix: ['DarkStarSkin', 'DeathBlossomSkin', 'GuardianoftheSandsSkin', 'MechaSkin', 'OdysseySkin', 'Worlds2018Skin'],
  Kindred: ['OriginalSkin', 'PorcelainSkin', 'PrestigePorcelainSkin', 'ShadowfireSkin', 'SuperGalaxySkin'],
  Kled: ['OriginalSkin', 'CountKledulaSkin', 'MarauderSkin', 'SirSkin'],
  Kogmaw: ['OriginalSkin', 'ArcanistSkin', 'BattlecastSkin', 'CaterpillarSkin', 'DeepSeaSkin', 'HextechSkin', 'JurassicSkin', 'LionDanceSkin', 'MonarchSkin', 'ReindeerSkin', 'ShanHaiScrollsSkin', 'SonoranSkin', 'VictoriousSkin'],
  Ksante: ['HEARTSTEELSkin'],
  Leblanc: ['OriginalSkin', 'BewitchingSkin', 'CovenSkin', 'ElderwoodSkin', 'iGSkin', 'MistletoeSkin', 'PrestigeCovenSkin', 'PrestigiousSkin', 'ProgramSkin', 'RavenbornSkin', 'WickedSkin', 'Worlds2020Skin'],
  LeeSin: ['OriginalSkin', 'AcolyteSkin', 'DivineHeavenscaleSkin', 'DragonFistSkin', 'KnockoutSkin', 'MuayThaiSkin', 'NightbringerSkin', 'PoolPartySkin', 'PrestigeNightbringerSkin', 'TraditionalSkin', 'ZenithGamesSkin'],
  Leona: ['OriginalSkin', 'BattleAcademiaSkin', 'BattleLionSkin', 'CrystalisMotusSkin', 'DebonairSkin', 'DefenderSkin', 'HighNoonSkin', 'IronSolariSkin', 'LunarEclipseSkin', 'MechaKingdomsSkin', 'PrestigeBattleAcademiaSkin', 'PrestigeBattleLionSkin', 'PROJECTSkin', 'SolarEclipseSkin', 'ValkyrieSkin'],
  Lillia: ['OriginalSkin', 'FaerieCourtSkin'],
  Lissandra: ['OriginalSkin', 'BladeQueenSkin', 'BloodstoneSkin', 'CovenSkin', 'DarkCosmicSkin', 'PorcelainSkin', 'PrestigePorcelainSkin', 'ProgramSkin', 'SpaceGrooveSkin'],
  Lucian: ['OriginalSkin', 'ArcanaSkin', 'DemaciaViceSkin', 'HeartseekerSkin', 'HighNoonSkin', 'HiredGunSkin', 'PrestigePulsefireSkin', 'PulsefireSkin', 'StrikePaladinSkin', 'VictoriousSkin', 'WinterblessedSkin'],
  Lulu: ['BittersweetSkin', 'CafeCutiesSkin', 'DragonTrainerSkin', 'PrestigeSpaceGrooveSkin', 'SpaceGrooveSkin', 'StarGuardianSkin', 'WickedSkin', 'WinterWonderSkin'],
  Lux: ['OriginalSkin', 'BattleAcademiaSkin', 'CommandoSkin', 'CosmicSkin', 'DarkCosmicSkin', 'ElementalistSkin', 'EmpyreanSkin', 'FaerieCourtSkin', 'ImperialSkin', 'LunarEmpressSkin', 'PorcelainSkin', 'PrestigeBattleAcademiaSkin', 'PrestigePorcelainSkin', 'SorceressSkin', 'SoulFighterSkin', 'SpaceGrooveSkin', 'SpellthiefSkin', 'StarGuardianSkin', 'SteelLegionSkin'],
  Malphite: ['OriginalSkin', 'CoralReefSkin', 'DarkStarSkin', 'GlacialSkin', 'LunarGuardianSkin', 'MarbleSkin', 'ObsidianSkin', 'OdysseySkin', 'OldGodSkin', 'ShamrockSkin'],
  Malzahar: ['OriginalSkin', 'BattleBossSkin', 'BeezaharSkin', 'DjinnSkin', 'EmpyreanSkin', 'HextechSkin', 'OverlordSkin', 'ShadowPrinceSkin', 'SnowDaySkin', 'ThreeHonorsSkin', 'VizierSkin', 'WorldbreakerSkin'],
  Maokai: ['OriginalSkin', 'AstronautSkin', 'CharredSkin', 'FestiveSkin', 'HauntedSkin', 'TotemicSkin', 'VictoriousSkin', 'WorldbreakerSkin'],
  MasterYi: ['OriginalSkin', 'AssassinSkin', 'ChosenSkin', 'CosmicBladeSkin', 'DebonairSkin', 'EternalSwordYiSkin', 'HeadhunterSkin', 'HeavenscaleSkin', 'InkshadowSkin', 'IoniaSkin', 'PrestigeSpiritBlossomSkin', 'PROJECTYiSkin', 'PsyOpsSkin', 'SamuraiYiSkin', 'SnowManYiSkin'],
  Milio: ['OriginalSkin', 'FaerieCourtSkin', 'RainShepherdSkin'],
  MissFortune: ['OriginalSkin', 'ArcadeSkin', 'BattleBunnySkin', 'BattleQueenSkin', 'BewitchingSkin', 'BrokenCovenantSkin', 'CandyCaneSkin', 'CaptainFortuneSkin', 'CowgirlSkin', 'CrimeCitySkin', 'GunGoddessSkin', 'PoolPartySkin', 'PorcelainSkin', 'PrestigeBewitchingSkin', 'PrestigeBrokenCovenantSkin', 'RoadWarriorSkin', 'RuinedSkin', 'SecretAgentSkin', 'StarGuardianSkin', 'WaterlooSkin'],
  Mordekaiser: ['OriginalSkin', 'AshenGraveknightSkin', 'DarkStarSkin', 'DragonKnightSkin', 'InfernalSkin', 'LordSkin', 'PentakillSkin', 'PROJECTSkin'],
  Morgana: ['OriginalSkin', 'BewitchingSkin', 'BlackthornSkin', 'BladeMistressSkin', 'DawnbringerSkin', 'ExiledSkin', 'GhostBrideSkin', 'MajesticEmpressSkin', 'PrestigeBewitchingSkin', 'SinfulSucculenceSkin', 'SnowMoonSkin', 'VictoriousSkin'],
  Naafiri: ['PROJECTSkin', 'SoulFighterSkin'],
  Nami: ['OriginalSkin', 'CosmicDestinySkin', 'DeepSeaSkin', 'KoiSkin', 'PrestigeSpaceGrooveSkin', 'ProgramSkin', 'RiverSpiritSkin', 'SpaceGrooveSkin', 'SplendidStaffSkin'],
  Nasus: ['OriginalSkin', 'ArmoredTitanSkin', 'BattlecastSkin', 'DreadknightSkin', 'GalacticSkin', 'InfernalSkin', 'LunarGuardianSkin', 'NightbringerSkin', 'PharaohSkin', 'RiotK-9Skin', 'SpaceGrooveSkin'],
  Nautilus: ['OriginalSkin', 'AbyssalSkin', 'AstroNautilusSkin', 'ConquerorSkin', 'CosmicPaladinSkin', 'CrystalisIndomitusSkin', 'SubterraneanSkin'],
  Neeko: ['OriginalSkin', 'BewitchingSkin', 'PrestigeStarGuardianSkin', 'ShanHaiScrollsSkin', 'StarGuardianSkin', 'StreetDemonsSkin', 'WinterWonderSkin'],
  Nidalee: ['OriginalSkin', 'BewitchingSkin', 'ChallengerSkin', 'CosmicHuntressSkin', 'DawnbringerSkin', 'FrenchMaidSkin', 'HeadhunterSkin', 'LaIlusiC3B3nSkin', 'LeopardSkin', 'PharaohSkin', 'SnowBunnySkin', 'SuperGalaxySkin', 'WarringKingdomsSkin'],
  Nilah: ['OriginalSkin', 'CovenSkin', 'StarGuardianSkin'],
  Nocturne: ['OriginalSkin', 'BrokenCovenantSkin', 'EternumSkin', 'FrozenTerrorSkin', 'HauntingSkin', 'HextechSkin', 'RavagerSkin', 'VoidSkin'],
  NunuAWillump: ['OriginalSkin', 'CosmicPaladinsSkin', 'DemolisherSkin', 'GrungySkin', 'NunuBotSkin', 'PapercraftSkin', 'SasquatchSkin', 'SpaceGrooveSkin', 'WorkshopSkin'],
  Olaf: ['OriginalSkin', 'BrolafSkin', 'ForsakenSkin', 'GlacialSkin'],
  Orianna: ['OriginalSkin', 'BladecraftSkin', 'DarkStarSkin', 'GothicSkin', 'HeartseekerSkin', 'OrbeeannaSkin', 'SewnChaosSkin', 'VictoriousSkin', 'WinterWonderSkin'],
  Ornn: ['OriginalSkin', 'SpaceGrooveSkin', 'ThunderLordSkin'],
  Pantheon: ['OriginalSkin', 'AshenConquerorSkin', 'DragonslayerSkin', 'FullMetalSkin', 'GlaiveWarriorSkin', 'MyrmidonSkin', 'PerseusSkin', 'PrestigeAscendedSkin', 'RuinedSkin', 'RuthlessSkin'],
  Poppy: ['OriginalSkin', 'BattleRegaliaSkin', 'BlacksmithSkin', 'CafeCutiesSkin', 'LollipoppySkin', 'NoxusSkin', 'RagdollSkin', 'ScarletHammerSkin', 'SnowFawnSkin', 'StarGuardianSkin'],
  Pyke: ['OriginalSkin', 'AshenKnightSkin', 'BloodMoonSkin', 'EmpyreanSkin', 'PrestigeSoulFighterSkin', 'PROJECTSkin', 'PsyOpsSkin', 'SentinelSkin', 'SoulFighterSkin'],
  Qiyana: ['OriginalSkin', 'BattleBossSkin', 'BattleQueenSkin', 'LaIlusiC3B3nSkin', 'PrestigeTrueDamageSkin', 'TrueDamageSkin'],
  Quinn: ['OriginalSkin', 'HeartseekerSkin', 'PhoenixSkin', 'WardenSkin', 'WoadScoutSkin'],
  Rakan: ['DragonmancerSkin', 'iGSkin', 'PrestigeDragonmancerSkin'],
  Rammus: ['OriginalSkin', 'ChromeSkin', 'DurianDefenderSkin', 'FreljordSkin', 'FullMetalSkin', 'HextechSkin', 'KingSkin', 'MoltenSkin', 'NinjaSkin'],
  RekSai: ['OriginalSkin', 'ElderwoodSkin', 'EternumSkin'],
  Rell: ['OriginalSkin', 'HighNoonSkin', 'StarGuardianSkin'],
  RenataGlasc: ['OriginalSkin', 'AdmiralGlascSkin', 'LaIlusiC3B3nSkin'],
  Renekton: ['OriginalSkin', 'BloodfurySkin', 'GalacticSkin', 'HextechSkin', 'OutbackSkin', 'PoolPartySkin', 'PROJECTSkin', 'RuneWarsSkin'],
  Rengar: ['OriginalSkin', 'HeadhunterSkin', 'MechaSkin', 'NightHunterSkin', 'SentinelSkin', 'StreetDemonsSkin'],
  Riven: ['OriginalSkin', 'BattleBunnyPrimeSkin', 'BattleBunnySkin', 'BrokenCovenantSkin', 'CrimsonEliteSkin', 'DawnbringerSkin', 'DragonbladeSkin', 'PrestigeValiantSwordSkin', 'PrimalAmbushSkin', 'PulsefireSkin', 'RedeemedSkin', 'SentinelSkin', 'ValiantSwordSkin', 'Worlds2012Skin'],
  Rumble: ['OriginalSkin', 'BadlandsBaronSkin', 'BilgeratSkin', 'CafeCutiesSkin', 'RumbleintheJungleSkin', 'SpaceGrooveSkin', 'SuperGalaxySkin'],
  Ryze: ['OriginalSkin', 'ArcanaSkin', 'DarkCrystalSkin', 'PirateSkin', 'ProfessorSkin', 'TribalSkin', 'TriumphantSkin', 'UncleSkin', 'Worlds2019Skin', 'YoungSkin', 'ZombieSkin'],
  Samira: ['HighNoonSkin', 'PsyOpsSkin', 'SoulFighterSkin', 'SpaceGrooveSkin'],
  Sejuani: ['OriginalSkin', 'BearCavalrySkin', 'DarkriderSkin', 'FirecrackerSkin', 'HextechSkin', 'PoroRiderSkin', 'PROJECTSkin', 'SabretuskSkin', 'SolarEclipseSkin', 'TraditionalSkin'],
  Senna: ['OriginalSkin', 'HighNoonSkin', 'PrestigeTrueDamageSkin', 'TrueDamageSkin', 'WinterblessedSkin'],
  Seraphine: ['OriginalSkin', 'KDAALLOUTSuperstarSkin'],
  Sett: ['OriginalSkin', 'FirecrackerSkin', 'HEARTSTEELSkin', 'MechaKingdomsSkin', 'ObsidianDragonSkin', 'PrestigeObsidianDragonSkin', 'SoulFighterSkin'],
  Shaco: ['OriginalSkin', 'ArcanistSkin', 'AsylumSkin', 'CrimeCityNightmareSkin', 'DarkStarSkin', 'FrightNightSkin', 'MadHatterSkin', 'MaskedSkin', 'NutcrackoSkin', 'PrestigeSoulFighterSkin', 'RoyalSkin', 'SoulFighterSkin', 'WinterblessedSkin', 'WorkshopSkin'],
  Shen: ['OriginalSkin', 'AshenGuardianSkin', 'BloodMoonSkin', 'FrozenSkin', 'PsyOpsSkin', 'SurgeonSkin', 'WarlordSkin', 'YellowJacketSkin'],
  Shyvana: ['OriginalSkin', 'BoneclawSkin', 'DarkflameSkin', 'IceDrakeSkin', 'IronscaleSkin', 'RuinedSkin', 'SuperGalaxySkin', 'Worlds2014Skin'],
  Singed: ['OriginalSkin', 'AstronautSkin', 'AugmentedSkin', 'BeekeeperSkin', 'HextechSkin', 'MadScientistSkin', 'ResistanceSkin', 'RiotSquadSkin', 'SnowDaySkin', 'SurferSkin'],
  Sion: ['OriginalSkin', 'BarbarianSkin', 'BlackfrostSkin', 'CosmicPaladinSkin', 'HextechSkin', 'LumberjackSkin', 'MechaZeroSkin', 'WarmongerSkin'],
  Sivir: ['OriginalSkin', 'BanditSkin', 'BloodMoonSkin', 'HuntressSkin', 'NeoPAXSkin', 'OdysseySkin', 'PAXSkin', 'PizzaDeliverySkin', 'PrimalAmbushSkin', 'SnowstormSkin', 'SolarEclipseSkin', 'SpectacularSkin', 'VictoriousSkin', 'WarriorPrincessSkin'],
  Skarner: ['OriginalSkin', 'BattlecastAlphaSkin', 'EarthruneSkin', 'SandscourgeSkin'],
  Smolder: ['HeavenscaleSkin'],
  Sona: ['OriginalSkin', 'ArcadeSkin', 'DJSkin', 'GuqinSkin', 'ImmortalJourneySkin', 'MuseSkin', 'OdysseySkin', 'PentakillSkin', 'PrestigeImmortalJourneySkin', 'PsyOpsSkin', 'SilentNightSkin', 'SweetheartSkin', 'VictoriousSkin'],
  Soraka: ['OriginalSkin', 'CelestineSkin', 'DawnbringerSkin', 'DivineSkin', 'DryadSkin', 'FaerieCourtSkin', 'ImmortalJourneySkin', 'NightbringerSkin', 'PrestigeStarGuardianSkin', 'ProgramSkin', 'ReaperSkin', 'SpiritBlossomSkin', 'StarGuardianSkin', 'WinterWonderSkin'],
  Swain: ['OriginalSkin', 'BilgewaterSkin', 'DragonMasterSkin', 'NorthernFrontSkin', 'WinterblessedSkin'],
  Sylas: ['OriginalSkin', 'AshenSlayerSkin', 'FreljordSkin', 'LunarWraithSkin', 'PrestigePROJECTSkin', 'PROJECTSkin', 'WinterblessedSkin'],
  Syndra: ['OriginalSkin', 'BewitchingSkin', 'CovenSkin', 'SpiritBlossomSkin', 'StarGuardianSkin'],
  TahmKench: ['OriginalSkin', 'ArcanaSkin', 'MasterChefSkin', 'ShanHaiScrollsSkin'],
  Taliyah: ['OriginalSkin', 'CrystalisMotusSkin', 'FreljordSkin'],
  Talon: ['OriginalSkin', 'BloodMoonSkin', 'CrimsonEliteSkin', 'DragonbladeSkin', 'EnduringSwordSkin', 'PrestigeHighNoonSkin', 'PrimalAmbushSkin', 'RenegadeSkin'],
  Taric: ['OriginalSkin', 'ArmoroftheFifthAgeSkin', 'BloodstoneSkin', 'EmeraldSkin', 'PoolPartySkin', 'SpaceGrooveSkin'],
  Teemo: ['OriginalSkin', 'AstronautSkin', 'BadgerSkin', 'BeemoSkin', 'CottontailSkin', 'FirecrackerSkin', 'HappyElfSkin', 'LittleDevilSkin', 'OmegaSquadSkin', 'PandaSkin', 'PrestigeSpiritBlossomSkin', 'ReconSkin', 'SpaceGrooveSkin', 'SuperSkin'],
  Thresh: ['OriginalSkin', 'BloodMoonSkin', 'DarkStarSkin', 'DeepTerrorSkin', 'HighNoonSkin', 'JanitorSkin', 'PrestigePulsefireSkin', 'PulsefireSkin', 'SteelDragonSkin', 'UnboundSkin', 'WinterblessedSkin'],
  Tristana: ['OriginalSkin', 'BewitchingSkin', 'BuccaneerSkin', 'DragonTrainerSkin', 'EarnestElfSkin', 'FaerieCourtSkin', 'FirefighterSkin', 'GuerillaSkin', 'HextechSkin', 'LittleDemonSkin', 'OmegaSquadSkin', 'RiotGirlSkin', 'RocketGirlSkin', 'SpiritBlossomSkin'],
  Trundle: ['OriginalSkin', 'DragonslayerSkin', 'JunkyardSkin', 'LilSluggerSkin', 'TraditionalSkin'],
  Tryndamere: ['OriginalSkin', 'ChemtechSkin', 'DemonbladeSkin', 'HighlandSkin', 'KingSkin', 'NightmareSkin', 'SultanSkin', 'VictoriousSkin', 'VikingSkin', 'WarringKingdomsSkin'],
  TwistedFate: ['OriginalSkin', 'BloodMoonSkin', 'CrimeCityNightmareSkin', 'HighNoonSkin', 'JackofHeartsSkin', 'MusketeerSkin', 'OdysseySkin', 'PAXSkin', 'SpaceGrooveSkin', 'TheMagnificentSkin', 'UnderworldSkin'],
  Twitch: ['OriginalSkin', 'CrimeCitySkin', 'DragonslayerSkin', 'HighNoonSkin', 'KingpinSkin', 'MedievalSkin', 'VandalSkin', 'WhistlerVillageSkin'],
  Udyr: ['OriginalSkin', 'BlackBeltSkin', 'DragonOracleSkin', 'InkshadowSkin', 'PrimalSkin', 'SpiritGuardPhoenixSkin', 'SpiritGuardSkin', 'SpiritGuardTigerSkin', 'SpiritGuardTurtleSkin'],
  Urgot: ['OriginalSkin', 'BattlecastSkin', 'ButcherSkin', 'GiantEnemyCrabgotSkin', 'HighNoonSkin'],
  Varus: ['OriginalSkin', 'ArclightSkin', 'ArcticOpsSkin', 'BlightCrystalSkin', 'ConquerorSkin', 'CosmicHunterSkin', 'DarkStarSkin', 'EmpyreanSkin', 'HeartseekerSkin', 'PROJECTSkin', 'SnowMoonSkin'],
  Vayne: ['OriginalSkin', 'ArclightSkin', 'AristocratSkin', 'DawnbringerSkin', 'DragonmancerSkin', 'DragonslayerSkin', 'FirecrackerSkin', 'HeartseekerSkin', 'PROJECTSkin', 'SoulstealerSkin', 'SpiritBlossomSkin', 'VindicatorSkin'],
  Veigar: ['OriginalSkin', 'BadSantaSkin', 'BaronVonSkin', 'CurlingSkin', 'ElderwoodSkin', 'FinalBossSkin', 'FrightNightSkin', 'KingBeegarSkin', 'LeprechaunSkin', 'MonsterTamerSkin', 'OmegaSquadSkin', 'SuperbVillainSkin', 'VeigarGreybeardSkin', 'WhiteMageSkin'],
  Velkoz: ['OriginalSkin', 'ArclightSkin', 'BattlecastSkin', 'BeeKozSkin', 'BlackfrostSkin', 'InfernalSkin'],
  Vex: ['OriginalSkin', 'DawnbringerSkin', 'EmpyreanSkin'],
  Vi: ['ArcaneSkin', 'DebonairSkin', 'DemonSkin', 'HeartbreakerSkin', 'NeonStrikeSkin', 'PrimalAmbushSkin', 'PROJECTSkin', 'PsyOpsSkin', 'WarringKingdomsSkin'],
  Viego: ['OriginalSkin', 'DissonanceofPentakillSkin', 'KingSkin', 'LunarBeastSkin', 'SoulFighterSkin'],
  Viktor: ['OriginalSkin', 'CreatorSkin', 'DeathSwornSkin', 'FullMachineSkin', 'HighNoonSkin', 'PrototypeSkin', 'PsyOpsSkin'],
  Vladimir: ['OriginalSkin', 'BloodLordSkin', 'BrokenCovenantSkin', 'CafeCutiesSkin', 'CosmicDevourerSkin', 'CountSkin', 'MarquisSkin', 'NosferatuSkin', 'SoulstealerSkin', 'VandalSkin'],
  Volibear: ['OriginalSkin', 'InkshadowSkin', 'NorthernStormSkin', 'PrestigeDualityDragonSkin', 'RuneguardSkin', 'TheThousand-PiercedBearSkin', 'ThunderLordSkin'],
  Warwick: ['OriginalSkin', 'BigBadSkin', 'FeralSkin', 'FirefangSkin', 'GreySkin', 'HyenaSkin', 'LunarGuardianSkin', 'OldGodSkin', 'PROJECTSkin', 'TundraHunterSkin', 'UrftheManateeSkin', 'UrfwickSkin', 'WinterblessedSkin'],
  Wukong: ['OriginalSkin', 'ElderwoodSkin', 'GeneralSkin', 'JadeDragonSkin', 'LancerStratusSkin', 'RadiantSkin', 'UnderworldSkin', 'VolcanicSkin'],
  Xayah: ['BravePhoenixSkin', 'PrestigeBravePhoenixSkin'],
  Xerath: ['OriginalSkin', 'ArcanaSkin', 'AstronautSkin', 'BattlecastSkin', 'CrystalisIndomitusSkin', 'DarkStarSkin', 'RunebornSkin', 'ScorchedEarthSkin'],
  XinZhao: ['OriginalSkin', 'CommandoSkin', 'DragonslayerSkin', 'FirecrackerSkin', 'ImperialSkin', 'MarauderSkin', 'SecretAgentSkin', 'VisceroSkin', 'WarringKingdomsSkin', 'WingedHussarSkin'],
  Yasuo: ['BattleBossSkin', 'BattleWolfSkin', 'BloodMoonSkin', 'DreamDragonSkin', 'ForeseenSkin', 'HighNoonSkin', 'InkshadowSkin', 'NightbringerSkin', 'OdysseySkin', 'PrestigeInkshadowSkin', 'PrestigeTrueDamageSkin', 'PROJECTSkin', 'SeaDogSkin', 'TruthDragonSkin'],
  Yone: ['OriginalSkin', 'BattleAcademiaSkin', 'HEARTSTEELSkin', 'InkshadowSkin', 'PrestigeHEARTSTEELSkin'],
  Yorick: ['OriginalSkin', 'ArclightSkin', 'PentakillSkin', 'ResistanceSkin', 'SpiritBlossomSkin', 'UndertakerSkin'],
  Yuumi: ['OriginalSkin', 'BattlePrincipalSkin', 'BewitchingSkin', 'PrestigeCyberCatSkin'],
  Zac: ['OriginalSkin', 'BattlecastSkin', 'EmpyreanSkin', 'SpecialWeaponSkin'],
  Zed: ['OriginalSkin', 'DeathSwornSkin', 'DebonairSkin', 'EmpyreanSkin', 'GalaxySlayerSkin', 'PROJECTSkin', 'PsyOpsSkin', 'ShockbladeSkin', 'Worlds2016Skin'],
  Zeri: ['OriginalSkin'],
  Ziggs: ['OriginalSkin', 'HextechSkin', 'LaIlusiC3B3nSkin', 'MadScientistSkin', 'MajorSkin', 'MasterArcanistSkin', 'PoolPartySkin', 'SnowDaySkin'],
  Zilean: ['OriginalSkin', 'BloodMoonSkin', 'GroovySkin', 'OldSaintSkin', 'ShurimaDesertSkin', 'SugarRushSkin', 'TimeMachineSkin'],
  Zoe: ['OriginalSkin', 'ArcanistSkin', 'CyberPopSkin', 'PrestigeArcanistSkin', 'StarGuardianSkin', 'WinterblessedSkin'],
  Zyra: ['OriginalSkin', 'BloodMoonSkin', 'CovenSkin', 'CrimeCityNightmareSkin', 'DragonSorceressSkin', 'HauntedSkin', 'PrestigeCovenSkin', 'StreetDemonsSkin', 'WildfireSkin'],
}
