import type { ShopItem } from '../types'

export const SHOP_ITEMS: ShopItem[] = [
  // ── Weapons: Swords ──────────────────────────────────────────────────────────
  {
    id: 'ancient_bone_sword',
    name: 'Ancient Bone Sword',
    description: '+12% Combat Power (Bone Crit Amplification)',
    icon: '/img/itemShop/sword/AncientBoneSword.png',
    price: 1200,
    rarity: 'common',
    category: 'weapon',
    effects: { powerMultiplier: 1.12 },
  },
  {
    id: 'crystal_shard_sword',
    name: 'Crystal Shard Sword',
    description: '+10% CPS, +5% Combat Power (Magical Shard)',
    icon: '/img/itemShop/sword/CrystalShardSword.png',
    price: 1800,
    rarity: 'common',
    category: 'weapon',
    effects: { cpsMultiplier: 1.1, powerMultiplier: 1.05 },
  },
  {
    id: 'coral_cutlass',
    name: 'Coral Cutlass',
    description: '+15% Combat Power (Slowing Strike)',
    icon: '/img/itemShop/sword/CoralCutlass.png',
    price: 2500,
    rarity: 'common',
    category: 'weapon',
    effects: { powerMultiplier: 1.15 },
  },
  {
    id: 'holy_sunblade',
    name: 'Holy Sunblade',
    description: '+20% Combat Power, +15% CPS (Holy Lifesteal)',
    icon: '/img/itemShop/sword/HolySunblade.png',
    price: 15000,
    materialCost: { solar_essence: 1 },
    rarity: 'rare',
    category: 'weapon',
    effects: { powerMultiplier: 1.2, cpsMultiplier: 1.15 },
  },
  {
    id: 'mechanical_gear_sword',
    name: 'Mechanical Gear Sword',
    description: '+25% CPS, +12% Combat Power (Enhanced Attack Speed)',
    icon: '/img/itemShop/sword/MechanicalGearSword.png',
    price: 18000,
    materialCost: { nebula_quartz: 2 },
    rarity: 'rare',
    category: 'weapon',
    effects: { cpsMultiplier: 1.25, powerMultiplier: 1.12 },
  },
  {
    id: 'leaf_vine_sword',
    name: 'Leaf & Vine Sword',
    description: '+20% CPS, +18% Combat Power (Nature Regeneration)',
    icon: '/img/itemShop/sword/LeaveVinSword.png',
    price: 22000,
    materialCost: { solar_essence: 1 },
    rarity: 'rare',
    category: 'weapon',
    effects: { cpsMultiplier: 1.2, powerMultiplier: 1.18 },
  },
  {
    id: 'lava_forge_blade',
    name: 'Lava Forge Blade',
    description: '+28% Combat Power, +8% CPS (Lava Burn Damage)',
    icon: '/img/itemShop/sword/LavaForgeBlade.png',
    price: 28000,
    materialCost: { nebula_quartz: 2 },
    rarity: 'rare',
    category: 'weapon',
    effects: { powerMultiplier: 1.28, cpsMultiplier: 1.08 },
  },
  {
    id: 'storm_blade',
    name: 'Storm Blade',
    description: '+40% Combat Power, +12% CPS (Chain Lightning Discharge)',
    icon: '/img/itemShop/sword/StormBlade.png',
    price: 65000,
    materialCost: { void_shard: 1 },
    rarity: 'epic',
    category: 'weapon',
    effects: { powerMultiplier: 1.4, cpsMultiplier: 1.12 },
  },
  {
    id: 'frozen_tundra_sword',
    name: 'Frozen Tundra Sword',
    description: '+45% Combat Power, +8% CPS (Blizzard Freeze)',
    icon: '/img/itemShop/sword/FrozenTundraSword.png',
    price: 75000,
    materialCost: { void_shard: 1 },
    rarity: 'epic',
    category: 'weapon',
    effects: { powerMultiplier: 1.45, cpsMultiplier: 1.08 },
  },
  {
    id: 'void_reaper',
    name: 'Void Reaper',
    description: '+75% Combat Power, +15% CPS (Void Lifesteal)',
    icon: '/img/itemShop/sword/VoidReaper.png',
    price: 230000,
    materialCost: { dark_matter: 2 },
    rarity: 'legendary',
    category: 'weapon',
    effects: { powerMultiplier: 1.75, cpsMultiplier: 1.15 },
  },

  // ── Weapons: Staves ───────────────────────────────────────────────────────────
  {
    id: 'kristallstab',
    name: 'Crystal Staff',
    description: '+12% CPS',
    icon: '/img/staff.png',
    price: 1500,
    rarity: 'common',
    category: 'weapon',
    effects: { cpsMultiplier: 1.12 },
  },
  {
    id: 'kosmischerstab',
    name: 'Cosmic Staff',
    description: '+48% CPS',
    icon: '/img/staff.png',
    price: 50000,
    materialCost: { void_shard: 1 },
    rarity: 'epic',
    category: 'weapon',
    effects: { cpsMultiplier: 1.48 },
    setId: 'cosmic',
  },

  // ── Weapons: Hammers ──────────────────────────────────────────────────────────
  {
    id: 'eisenhammer',
    name: 'Iron Hammer',
    description: '+15% Combat Power',
    icon: '/img/hammer.png',
    price: 2000,
    rarity: 'common',
    category: 'weapon',
    effects: { powerMultiplier: 1.15 },
  },
  {
    id: 'sternenhammer',
    name: 'Star Hammer',
    description: '+80% Combat Power, +20% CPS',
    icon: '/img/hammer.png',
    price: 250000,
    materialCost: { dark_matter: 2 },
    rarity: 'legendary',
    category: 'weapon',
    effects: { powerMultiplier: 1.8, cpsMultiplier: 1.2 },
    setId: 'stellar',
  },

  // ── Armor ─────────────────────────────────────────────────────────────────────
  {
    id: 'lederpanzer',
    name: 'Leather Armor',
    description: '+8% Combat Power',
    icon: '🥋',
    price: 400,
    rarity: 'common',
    category: 'armor',
    effects: { powerMultiplier: 1.08 },
  },
  {
    id: 'kettenpanzer',
    name: 'Chain Armor',
    description: '+15% Combat Power',
    icon: '🛡️',
    price: 1800,
    rarity: 'common',
    category: 'armor',
    effects: { powerMultiplier: 1.15 },
  },
  {
    id: 'mythrilruestung',
    name: 'Mythril Armor',
    description: '+25% Combat Power',
    icon: '🔵',
    price: 7000,
    rarity: 'rare',
    category: 'armor',
    effects: { powerMultiplier: 1.25 },
  },
  {
    id: 'sternenschild',
    name: 'Star Shield',
    description: '+35% Combat Power, +5% CPS',
    icon: '🌠',
    price: 18000,
    materialCost: { solar_essence: 2 },
    rarity: 'rare',
    category: 'armor',
    effects: { powerMultiplier: 1.35, cpsMultiplier: 1.05 },
    setId: 'arcane',
  },
  {
    id: 'drachenpanzer',
    name: 'Dragon Armor',
    description: '+50% Combat Power',
    icon: '🐉',
    price: 55000,
    materialCost: { void_shard: 1 },
    rarity: 'epic',
    category: 'armor',
    effects: { powerMultiplier: 1.5 },
    setId: 'cosmic',
  },
  {
    id: 'kosmischeruestung',
    name: 'Cosmic Armor',
    description: '+80% Combat Power',
    icon: '🌌',
    price: 220000,
    materialCost: { dark_matter: 1 },
    rarity: 'legendary',
    category: 'armor',
    effects: { powerMultiplier: 1.8 },
    setId: 'stellar',
  },

  // ── Misc ─────────────────────────────────────────────────────────────────────
  {
    id: 'heiltrank',
    name: 'Health Potion',
    description: '+5% CPS',
    icon: '🧪',
    price: 300,
    rarity: 'common',
    category: 'misc',
    effects: { cpsMultiplier: 1.05 },
  },
  {
    id: 'gluecksamulett',
    name: 'Lucky Amulet',
    description: '+12% CPS',
    icon: '📿',
    price: 1500,
    rarity: 'common',
    category: 'misc',
    effects: { cpsMultiplier: 1.12 },
  },
  {
    id: 'quarzanhaenger',
    name: 'Quartz Pendant',
    description: '+22% CPS',
    icon: '💎',
    price: 5000,
    materialCost: { nebula_quartz: 1 },
    rarity: 'rare',
    category: 'misc',
    effects: { cpsMultiplier: 1.22 },
  },
  {
    id: 'aetherkristall',
    name: 'Aether Crystal',
    description: '+35% CPS',
    icon: '🔮',
    price: 15000,
    materialCost: { solar_essence: 2 },
    rarity: 'rare',
    category: 'misc',
    effects: { cpsMultiplier: 1.35 },
    setId: 'arcane',
  },
  {
    id: 'zeitohrring',
    name: 'Time Earring',
    description: '+48% CPS',
    icon: '⏳',
    price: 50000,
    materialCost: { void_shard: 1 },
    rarity: 'epic',
    category: 'misc',
    effects: { cpsMultiplier: 1.48 },
    setId: 'cosmic',
  },
  {
    id: 'dunklesplitter',
    name: 'Dark Matter Shard',
    description: '+65% CPS',
    icon: '🌑',
    price: 180000,
    materialCost: { dark_matter: 1 },
    rarity: 'legendary',
    category: 'misc',
    effects: { cpsMultiplier: 1.65 },
    setId: 'stellar',
  },
]

const ITEM_MAP = new Map<string, ShopItem>(SHOP_ITEMS.map((item) => [item.id, item]))

export function getItemById(id: string): ShopItem | undefined {
  return ITEM_MAP.get(id)
}
