import type { ShopItem } from '../types'

export const SHOP_ITEMS: ShopItem[] = [
  // ── Waffen: Schwerter ─────────────────────────────────────────────────────────
  {
    id: 'ancient_bone_sword',
    name: 'Ancient Bone Sword',
    description: '+12% Kampfkraft (Knochen-Crit-Verstärkung)',
    icon: '/img/itemShop/sword/AncientBoneSword.png',
    price: 1200,
    rarity: 'common',
    category: 'weapon',
    effects: { powerMultiplier: 1.12 },
  },
  {
    id: 'crystal_shard_sword',
    name: 'Crystal Shard Sword',
    description: '+10% CPS, +5% Kampfkraft (Magischer Splitter)',
    icon: '/img/itemShop/sword/CrystalShardSword.png',
    price: 1800,
    rarity: 'common',
    category: 'weapon',
    effects: { cpsMultiplier: 1.1, powerMultiplier: 1.05 },
  },
  {
    id: 'coral_cutlass',
    name: 'Coral Cutlass',
    description: '+15% Kampfkraft (Verlangsamender Schlag)',
    icon: '/img/itemShop/sword/CoralCutlass.png',
    price: 2500,
    rarity: 'common',
    category: 'weapon',
    effects: { powerMultiplier: 1.15 },
  },
  {
    id: 'holy_sunblade',
    name: 'Holy Sunblade',
    description: '+20% Kampfkraft, +15% CPS (Heiliger Lebensraub)',
    icon: '/img/itemShop/sword/HolySunblade.png',
    price: 15000,
    materialCost: { solar_essence: 1 },
    rarity: 'rare',
    category: 'weapon',
    effects: { powerMultiplier: 1.2, cpsMultiplier: 1.15 },
  },
  {
    id: 'mechanical_gear_sword',
    name: 'Mechanical Gear Sword',
    description: '+25% CPS, +12% Kampfkraft (Erhöhtes Angriffstempo)',
    icon: '/img/itemShop/sword/MechanicalGearSword.png',
    price: 18000,
    materialCost: { nebula_quartz: 2 },
    rarity: 'rare',
    category: 'weapon',
    effects: { cpsMultiplier: 1.25, powerMultiplier: 1.12 },
  },
  {
    id: 'leaf_vine_sword',
    name: 'Leaf & Vine Sword',
    description: '+20% CPS, +18% Kampfkraft (Naturregeneration)',
    icon: '/img/itemShop/sword/LeaveVinSword.png',
    price: 22000,
    materialCost: { solar_essence: 1 },
    rarity: 'rare',
    category: 'weapon',
    effects: { cpsMultiplier: 1.2, powerMultiplier: 1.18 },
  },
  {
    id: 'lava_forge_blade',
    name: 'Lava Forge Blade',
    description: '+28% Kampfkraft, +8% CPS (Lava-Brennschaden)',
    icon: '/img/itemShop/sword/LavaForgeBlade.png',
    price: 28000,
    materialCost: { nebula_quartz: 2 },
    rarity: 'rare',
    category: 'weapon',
    effects: { powerMultiplier: 1.28, cpsMultiplier: 1.08 },
  },
  {
    id: 'storm_blade',
    name: 'Storm Blade',
    description: '+40% Kampfkraft, +12% CPS (Kettenblitz-Entladung)',
    icon: '/img/itemShop/sword/StormBlade.png',
    price: 65000,
    materialCost: { void_shard: 1 },
    rarity: 'epic',
    category: 'weapon',
    effects: { powerMultiplier: 1.4, cpsMultiplier: 1.12 },
  },
  {
    id: 'frozen_tundra_sword',
    name: 'Frozen Tundra Sword',
    description: '+45% Kampfkraft, +8% CPS (Eissturm-Freeze)',
    icon: '/img/itemShop/sword/FrozenTundraSword.png',
    price: 75000,
    materialCost: { void_shard: 1 },
    rarity: 'epic',
    category: 'weapon',
    effects: { powerMultiplier: 1.45, cpsMultiplier: 1.08 },
  },
  {
    id: 'void_reaper',
    name: 'Void Reaper',
    description: '+75% Kampfkraft, +15% CPS (Lebensraub aus der Leere)',
    icon: '/img/itemShop/sword/VoidReaper.png',
    price: 230000,
    materialCost: { dark_matter: 2 },
    rarity: 'legendary',
    category: 'weapon',
    effects: { powerMultiplier: 1.75, cpsMultiplier: 1.15 },
  },

  // ── Waffen: Zauberstäbe ───────────────────────────────────────────────────────
  {
    id: 'kristallstab',
    name: 'Kristallstab',
    description: '+12% CPS',
    icon: '/img/staff.png',
    price: 1500,
    rarity: 'common',
    category: 'weapon',
    effects: { cpsMultiplier: 1.12 },
  },
  {
    id: 'kosmischerstab',
    name: 'Kosmischer Stab',
    description: '+48% CPS',
    icon: '/img/staff.png',
    price: 50000,
    materialCost: { void_shard: 1 },
    rarity: 'epic',
    category: 'weapon',
    effects: { cpsMultiplier: 1.48 },
    setId: 'cosmic',
  },

  // ── Waffen: Hämmer ────────────────────────────────────────────────────────────
  {
    id: 'eisenhammer',
    name: 'Eisenhammer',
    description: '+15% Kampfkraft',
    icon: '/img/hammer.png',
    price: 2000,
    rarity: 'common',
    category: 'weapon',
    effects: { powerMultiplier: 1.15 },
  },
  {
    id: 'sternenhammer',
    name: 'Sternen-Hammer',
    description: '+80% Kampfkraft, +20% CPS',
    icon: '/img/hammer.png',
    price: 250000,
    materialCost: { dark_matter: 2 },
    rarity: 'legendary',
    category: 'weapon',
    effects: { powerMultiplier: 1.8, cpsMultiplier: 1.2 },
    setId: 'stellar',
  },

  // ── Rüstung ───────────────────────────────────────────────────────────────────
  {
    id: 'lederpanzer',
    name: 'Lederpanzer',
    description: '+8% Kampfkraft',
    icon: '🥋',
    price: 400,
    rarity: 'common',
    category: 'armor',
    effects: { powerMultiplier: 1.08 },
  },
  {
    id: 'kettenpanzer',
    name: 'Kettenpanzer',
    description: '+15% Kampfkraft',
    icon: '🛡️',
    price: 1800,
    rarity: 'common',
    category: 'armor',
    effects: { powerMultiplier: 1.15 },
  },
  {
    id: 'mythrilruestung',
    name: 'Mythril-Rüstung',
    description: '+25% Kampfkraft',
    icon: '🔵',
    price: 7000,
    rarity: 'rare',
    category: 'armor',
    effects: { powerMultiplier: 1.25 },
  },
  {
    id: 'sternenschild',
    name: 'Sternen-Schild',
    description: '+35% Kampfkraft, +5% CPS',
    icon: '🌠',
    price: 18000,
    materialCost: { solar_essence: 2 },
    rarity: 'rare',
    category: 'armor',
    effects: { powerMultiplier: 1.35, cpsMultiplier: 1.05 },
    setId: 'arcane',
  },
  {
    id: 'drachenpanzer',
    name: 'Drachenpanzer',
    description: '+50% Kampfkraft',
    icon: '🐉',
    price: 55000,
    materialCost: { void_shard: 1 },
    rarity: 'epic',
    category: 'armor',
    effects: { powerMultiplier: 1.5 },
    setId: 'cosmic',
  },
  {
    id: 'kosmischeruestung',
    name: 'Kosmische Rüstung',
    description: '+80% Kampfkraft',
    icon: '🌌',
    price: 220000,
    materialCost: { dark_matter: 1 },
    rarity: 'legendary',
    category: 'armor',
    effects: { powerMultiplier: 1.8 },
    setId: 'stellar',
  },

  // ── Misc ─────────────────────────────────────────────────────────────────────
  {
    id: 'heiltrank',
    name: 'Heiltrank',
    description: '+5% CPS',
    icon: '🧪',
    price: 300,
    rarity: 'common',
    category: 'misc',
    effects: { cpsMultiplier: 1.05 },
  },
  {
    id: 'gluecksamulett',
    name: 'Glücksamulett',
    description: '+12% CPS',
    icon: '📿',
    price: 1500,
    rarity: 'common',
    category: 'misc',
    effects: { cpsMultiplier: 1.12 },
  },
  {
    id: 'quarzanhaenger',
    name: 'Quarz-Anhänger',
    description: '+22% CPS',
    icon: '💎',
    price: 5000,
    materialCost: { nebula_quartz: 1 },
    rarity: 'rare',
    category: 'misc',
    effects: { cpsMultiplier: 1.22 },
  },
  {
    id: 'aetherkristall',
    name: 'Äther-Kristall',
    description: '+35% CPS',
    icon: '🔮',
    price: 15000,
    materialCost: { solar_essence: 2 },
    rarity: 'rare',
    category: 'misc',
    effects: { cpsMultiplier: 1.35 },
    setId: 'arcane',
  },
  {
    id: 'zeitohrring',
    name: 'Zeit-Ohrring',
    description: '+48% CPS',
    icon: '⏳',
    price: 50000,
    materialCost: { void_shard: 1 },
    rarity: 'epic',
    category: 'misc',
    effects: { cpsMultiplier: 1.48 },
    setId: 'cosmic',
  },
  {
    id: 'dunklesplitter',
    name: 'Dunkle-Materie-Splitter',
    description: '+65% CPS',
    icon: '🌑',
    price: 180000,
    materialCost: { dark_matter: 1 },
    rarity: 'legendary',
    category: 'misc',
    effects: { cpsMultiplier: 1.65 },
    setId: 'stellar',
  },
]

const ITEM_MAP = new Map<string, ShopItem>(SHOP_ITEMS.map((item) => [item.id, item]))

export function getItemById(id: string): ShopItem | undefined {
  return ITEM_MAP.get(id)
}
