import type { ShopItem } from '../types'

export const SHOP_ITEMS: ShopItem[] = [
  // ── Waffen: Schwerter ─────────────────────────────────────────────────────────
  {
    id: 'holzschwert',
    name: 'Holzschwert',
    description: '+8% Kampfkraft',
    icon: '/img/sword.png',
    price: 500,
    rarity: 'common',
    category: 'weapon',
    effects: { powerMultiplier: 1.08 },
  },
  {
    id: 'arkanschwert',
    name: 'Arkan-Schwert',
    description: '+35% Kampfkraft, +5% CPS',
    icon: '/img/sword.png',
    price: 20000,
    materialCost: { nebula_quartz: 2 },
    rarity: 'rare',
    category: 'weapon',
    effects: { powerMultiplier: 1.35, cpsMultiplier: 1.05 },
    setId: 'arcane',
  },

  // ── Waffen: Zauberstäbe ───────────────────────────────────────────────────────
  {
    id: 'kristallstab',
    name: 'Kristallstab',
    description: '+12% CPS',
    icon: '/img/staff.png',
    price: 1500,
    rarity: 'common',
    category: 'weapon',
    effects: { cpsMultiplier: 1.12 },
  },
  {
    id: 'kosmischerstab',
    name: 'Kosmischer Stab',
    description: '+48% CPS',
    icon: '/img/staff.png',
    price: 50000,
    materialCost: { void_shard: 1 },
    rarity: 'epic',
    category: 'weapon',
    effects: { cpsMultiplier: 1.48 },
    setId: 'cosmic',
  },

  // ── Waffen: Hämmer ────────────────────────────────────────────────────────────
  {
    id: 'eisenhammer',
    name: 'Eisenhammer',
    description: '+15% Kampfkraft',
    icon: '/img/hammer.png',
    price: 2000,
    rarity: 'common',
    category: 'weapon',
    effects: { powerMultiplier: 1.15 },
  },
  {
    id: 'sternenhammer',
    name: 'Sternen-Hammer',
    description: '+80% Kampfkraft, +20% CPS',
    icon: '/img/hammer.png',
    price: 250000,
    materialCost: { dark_matter: 2 },
    rarity: 'legendary',
    category: 'weapon',
    effects: { powerMultiplier: 1.8, cpsMultiplier: 1.2 },
    setId: 'stellar',
  },

  // ── Rüstung ───────────────────────────────────────────────────────────────────
  {
    id: 'lederpanzer',
    name: 'Lederpanzer',
    description: '+8% Kampfkraft',
    icon: '🥋',
    price: 400,
    rarity: 'common',
    category: 'armor',
    effects: { powerMultiplier: 1.08 },
  },
  {
    id: 'kettenpanzer',
    name: 'Kettenpanzer',
    description: '+15% Kampfkraft',
    icon: '🛡️',
    price: 1800,
    rarity: 'common',
    category: 'armor',
    effects: { powerMultiplier: 1.15 },
  },
  {
    id: 'mythrilruestung',
    name: 'Mythril-Rüstung',
    description: '+25% Kampfkraft',
    icon: '🔵',
    price: 7000,
    rarity: 'rare',
    category: 'armor',
    effects: { powerMultiplier: 1.25 },
  },
  {
    id: 'sternenschild',
    name: 'Sternen-Schild',
    description: '+35% Kampfkraft, +5% CPS',
    icon: '🌠',
    price: 18000,
    materialCost: { solar_essence: 2 },
    rarity: 'rare',
    category: 'armor',
    effects: { powerMultiplier: 1.35, cpsMultiplier: 1.05 },
    setId: 'arcane',
  },
  {
    id: 'drachenpanzer',
    name: 'Drachenpanzer',
    description: '+50% Kampfkraft',
    icon: '🐉',
    price: 55000,
    materialCost: { void_shard: 1 },
    rarity: 'epic',
    category: 'armor',
    effects: { powerMultiplier: 1.5 },
    setId: 'cosmic',
  },
  {
    id: 'kosmischeruestung',
    name: 'Kosmische Rüstung',
    description: '+80% Kampfkraft',
    icon: '🌌',
    price: 220000,
    materialCost: { dark_matter: 1 },
    rarity: 'legendary',
    category: 'armor',
    effects: { powerMultiplier: 1.8 },
    setId: 'stellar',
  },

  // ── Misc ─────────────────────────────────────────────────────────────────────
  {
    id: 'heiltrank',
    name: 'Heiltrank',
    description: '+5% CPS',
    icon: '🧪',
    price: 300,
    rarity: 'common',
    category: 'misc',
    effects: { cpsMultiplier: 1.05 },
  },
  {
    id: 'gluecksamulett',
    name: 'Glücksamulett',
    description: '+12% CPS',
    icon: '📿',
    price: 1500,
    rarity: 'common',
    category: 'misc',
    effects: { cpsMultiplier: 1.12 },
  },
  {
    id: 'quarzanhaenger',
    name: 'Quarz-Anhänger',
    description: '+22% CPS',
    icon: '💎',
    price: 5000,
    materialCost: { nebula_quartz: 1 },
    rarity: 'rare',
    category: 'misc',
    effects: { cpsMultiplier: 1.22 },
  },
  {
    id: 'aetherkristall',
    name: 'Äther-Kristall',
    description: '+35% CPS',
    icon: '🔮',
    price: 15000,
    materialCost: { solar_essence: 2 },
    rarity: 'rare',
    category: 'misc',
    effects: { cpsMultiplier: 1.35 },
    setId: 'arcane',
  },
  {
    id: 'zeitohrring',
    name: 'Zeit-Ohrring',
    description: '+48% CPS',
    icon: '⏳',
    price: 50000,
    materialCost: { void_shard: 1 },
    rarity: 'epic',
    category: 'misc',
    effects: { cpsMultiplier: 1.48 },
    setId: 'cosmic',
  },
  {
    id: 'dunklesplitter',
    name: 'Dunkle-Materie-Splitter',
    description: '+65% CPS',
    icon: '🌑',
    price: 180000,
    materialCost: { dark_matter: 1 },
    rarity: 'legendary',
    category: 'misc',
    effects: { cpsMultiplier: 1.65 },
    setId: 'stellar',
  },
]

export function getItemById(id: string): ShopItem | undefined {
  return SHOP_ITEMS.find((item) => item.id === id)
}
