import type { UpgradeModifier } from '../types'

export const MODIFIER_POOL: UpgradeModifier[] = [
  {
    id: 'harmonische-resonanz',
    name: 'Harmonische Resonanz',
    description: 'Verstärkt den Effektwert um 50 % durch harmonische Schwingungen.',
    icon: '🎼',
    type: 'resonanceBoost',
    params: { boostFactor: 1.5 },
  },
  {
    id: 'sphärisches-echo',
    name: 'Sphärisches Echo',
    description: 'Jede Sekunde 15 % Chance auf einen Chime-Burst von 50.',
    icon: '🌀',
    type: 'chimeEcho',
    params: { burstAmount: 50, chance: 0.15 },
  },
  {
    id: 'melodische-synergie',
    name: 'Melodische Synergie',
    description: 'Verdoppelt den Effekt wenn Bardischer Nachhall ebenfalls aktiv ist.',
    icon: '🎹',
    type: 'synergyLink',
    params: { linkedUpgradeId: 'bardischer-nachhall' },
  },
  {
    id: 'kaskaden-harmonie',
    name: 'Kaskaden-Harmonie',
    description: 'Verleiht diesem Upgrade dauerhaft +5 % auf den Effektwert.',
    icon: '🌊',
    type: 'cascadeEffect',
    params: { cascadeBonus: 0.05 },
  },
  {
    id: 'adaptive-frequenz',
    name: 'Adaptive Frequenz',
    description: 'Effekt skaliert mit dem höchsten Gebäude-Level (+2 % pro Level).',
    icon: '📡',
    type: 'adaptiveScaling',
    params: { scaleFactor: 0.02 },
  },
  {
    id: 'zeitkristall-frequenz',
    name: 'Zeitkristall-Frequenz',
    description: 'Injiziert 100 Chimes/s direkt in die Produktion.',
    icon: '💎',
    type: 'timeCrystal',
    params: { crystalCPSBonus: 100 },
  },
  {
    id: 'bardische-resonanz',
    name: 'Bardische Resonanz',
    description: 'Bards Gitarre verdoppelt den Effektwert dieses Upgrades.',
    icon: '🎸',
    type: 'resonanceBoost',
    params: { boostFactor: 2.0 },
  },
  {
    id: 'kosmisches-lied',
    name: 'Kosmisches Lied',
    description: 'Kosmische Schwingungen skalieren mit Gebäude-Levels (+5 % pro Level).',
    icon: '⭐',
    type: 'adaptiveScaling',
    params: { scaleFactor: 0.05 },
  },
  {
    id: 'zeitlose-melodie',
    name: 'Zeitlose Melodie',
    description: '5 % Chance pro Sekunde auf einen massiven Burst von 200 Chimes.',
    icon: '⏰',
    type: 'chimeEcho',
    params: { burstAmount: 200, chance: 0.05 },
  },
]
