import type { SynergyDefinition, SynergyEffect } from '../types'
import type { PlanetType, ChampionRole } from '../types'

export interface ElementalSynergyDef extends SynergyDefinition {
  condition: { planetType: PlanetType }
}

export interface RoleEchoDef extends SynergyDefinition {
  condition: { roleKey: ChampionRole }
}

export interface LoreBondDef extends SynergyDefinition {
  pair: [string, string]
}

export const ELEMENTAL_SYNERGIES: ElementalSynergyDef[] = [
  {
    id: 'elemental_frozen_pact',
    name: 'Frozen Pact',
    description: '2+ Eis-Champions im selben Orbit — CPS +10%',
    type: 'elemental',
    icon: '❄️',
    color: '#7be8ff',
    tier: 'silver',
    effects: [{ type: 'cps', multiplier: 1.1 }] as SynergyEffect[],
    condition: { planetType: 'ice' },
  },
  {
    id: 'elemental_void_surge',
    name: 'Void Surge',
    description: '2+ Wüsten-Champions im selben Orbit — Macht +10%',
    type: 'elemental',
    icon: '🌑',
    color: '#9b48cc',
    tier: 'silver',
    effects: [{ type: 'power', multiplier: 1.1 }] as SynergyEffect[],
    condition: { planetType: 'desert' },
  },
  {
    id: 'elemental_lava_legion',
    name: 'Lava Legion',
    description: '2+ Lava-Champions im selben Orbit — DPS +12%',
    type: 'elemental',
    icon: '🔥',
    color: '#ff4500',
    tier: 'silver',
    effects: [{ type: 'dps', multiplier: 1.12 }] as SynergyEffect[],
    condition: { planetType: 'lava' },
  },
  {
    id: 'elemental_celestial_alignment',
    name: 'Celestial Alignment',
    description: '2+ Ringed-Champions im selben Orbit — CPS +15%',
    type: 'elemental',
    icon: '✨',
    color: '#e8c040',
    tier: 'gold',
    effects: [{ type: 'cps', multiplier: 1.15 }] as SynergyEffect[],
    condition: { planetType: 'ringed' },
  },
  {
    id: 'elemental_natures_embrace',
    name: "Nature's Embrace",
    description: '2+ Dschungel-Champions im selben Orbit — CPS +10%',
    type: 'elemental',
    icon: '🌿',
    color: '#50c060',
    tier: 'silver',
    effects: [{ type: 'cps', multiplier: 1.1 }] as SynergyEffect[],
    condition: { planetType: 'jungle' },
  },
  {
    id: 'elemental_oceans_depth',
    name: "Ocean's Depth",
    description: '2+ Ozean-Champions im selben Orbit — Macht +10%',
    type: 'elemental',
    icon: '🌊',
    color: '#3090e8',
    tier: 'silver',
    effects: [{ type: 'power', multiplier: 1.1 }] as SynergyEffect[],
    condition: { planetType: 'ocean' },
  },
  {
    id: 'elemental_stone_fortress',
    name: 'Stone Fortress',
    description: '2+ Fels-Champions im selben Orbit — DPS +10%',
    type: 'elemental',
    icon: '⛰️',
    color: '#a08060',
    tier: 'silver',
    effects: [{ type: 'dps', multiplier: 1.1 }] as SynergyEffect[],
    condition: { planetType: 'rocky' },
  },
  {
    id: 'elemental_cosmic_surge',
    name: 'Cosmic Surge',
    description: '2+ Gas-Riesen-Champions im selben Orbit — CPS +12%',
    type: 'elemental',
    icon: '💫',
    color: '#8060d8',
    tier: 'silver',
    effects: [{ type: 'cps', multiplier: 1.12 }] as SynergyEffect[],
    condition: { planetType: 'gas-giant' },
  },
]

export const ROLE_ECHO_DEFS: RoleEchoDef[] = [
  {
    id: 'echo_adc',
    name: 'Marksman Trio',
    description: 'Alle 3 Champions im Orbit spielen ADC — DPS +15%',
    type: 'role_echo',
    icon: '🏹',
    color: '#ff9300',
    tier: 'gold',
    effects: [{ type: 'dps', multiplier: 1.15 }] as SynergyEffect[],
    condition: { roleKey: 'adc' },
  },
  {
    id: 'echo_support',
    name: 'Support Trinity',
    description: 'Alle 3 Champions im Orbit spielen Support — Macht +15%',
    type: 'role_echo',
    icon: '💚',
    color: '#12b8ff',
    tier: 'gold',
    effects: [{ type: 'power', multiplier: 1.15 }] as SynergyEffect[],
    condition: { roleKey: 'support' },
  },
  {
    id: 'echo_mid',
    name: 'Mage Trio',
    description: 'Alle 3 Champions im Orbit spielen Mid — CPS +12%',
    type: 'role_echo',
    icon: '🔮',
    color: '#3694ff',
    tier: 'gold',
    effects: [{ type: 'cps', multiplier: 1.12 }] as SynergyEffect[],
    condition: { roleKey: 'mid' },
  },
  {
    id: 'echo_top',
    name: 'Tank Wall',
    description: 'Alle 3 Champions im Orbit spielen Top — DPS +10%',
    type: 'role_echo',
    icon: '🛡️',
    color: '#f34b49',
    tier: 'gold',
    effects: [{ type: 'dps', multiplier: 1.1 }] as SynergyEffect[],
    condition: { roleKey: 'top' },
  },
  {
    id: 'echo_jungle',
    name: 'Jungle Pact',
    description: 'Alle 3 Champions im Orbit spielen Jungle — CPS +10%',
    type: 'role_echo',
    icon: '🌿',
    color: '#5ce66a',
    tier: 'gold',
    effects: [{ type: 'cps', multiplier: 1.1 }] as SynergyEffect[],
    condition: { roleKey: 'jungle' },
  },
]

export const LORE_BONDS: LoreBondDef[] = [
  {
    id: 'lore_sisters',
    name: 'Sisterly Chaos',
    description: 'Jinx + Vi — DPS +12%',
    type: 'lore_bond',
    icon: '⚡',
    color: '#cc44cc',
    tier: 'gold',
    effects: [{ type: 'dps', multiplier: 1.12 }] as SynergyEffect[],
    pair: ['Jinx', 'Vi'],
  },
  {
    id: 'lore_celestial_opposition',
    name: 'Celestial Opposition',
    description: 'Leona + Diana — CPS +12%',
    type: 'lore_bond',
    icon: '☀️',
    color: '#e8c040',
    tier: 'gold',
    effects: [{ type: 'cps', multiplier: 1.12 }] as SynergyEffect[],
    pair: ['Leona', 'Diana'],
  },
  {
    id: 'lore_brothers_wind',
    name: 'Brothers of the Wind',
    description: 'Yasuo + Yone — Macht +15%',
    type: 'lore_bond',
    icon: '🌪️',
    color: '#80ccff',
    tier: 'gold',
    effects: [{ type: 'power', multiplier: 1.15 }] as SynergyEffect[],
    pair: ['Yasuo', 'Yone'],
  },
  {
    id: 'lore_lovers',
    name: 'The Lovers',
    description: 'Xayah + Rakan — CPS +12%',
    type: 'lore_bond',
    icon: '🌸',
    color: '#e060a0',
    tier: 'gold',
    effects: [{ type: 'cps', multiplier: 1.12 }] as SynergyEffect[],
    pair: ['Xayah', 'Rakan'],
  },
  {
    id: 'lore_piltover',
    name: "Piltover's Finest",
    description: 'Caitlyn + Vi — DPS +10%',
    type: 'lore_bond',
    icon: '🔫',
    color: '#50c8c8',
    tier: 'silver',
    effects: [{ type: 'dps', multiplier: 1.1 }] as SynergyEffect[],
    pair: ['Caitlyn', 'Vi'],
  },
  {
    id: 'lore_the_hunt',
    name: 'The Hunt',
    description: 'Thresh + Lucian — DPS +15%',
    type: 'lore_bond',
    icon: '⛓️',
    color: '#60c0ff',
    tier: 'gold',
    effects: [{ type: 'dps', multiplier: 1.15 }] as SynergyEffect[],
    pair: ['Thresh', 'Lucian'],
  },
  {
    id: 'lore_void_kin',
    name: 'Void Kin',
    description: "Kai'sa + Kassadin — Macht +12%",
    type: 'lore_bond',
    icon: '👁️',
    color: '#9b48cc',
    tier: 'gold',
    effects: [{ type: 'power', multiplier: 1.12 }] as SynergyEffect[],
    pair: ["Kai'sa", 'Kassadin'],
  },
  {
    id: 'lore_twin_sisters',
    name: 'Twin Sisters',
    description: 'Morgana + Kayle — CPS +10%',
    type: 'lore_bond',
    icon: '⚖️',
    color: '#c040c0',
    tier: 'silver',
    effects: [{ type: 'cps', multiplier: 1.1 }] as SynergyEffect[],
    pair: ['Morgana', 'Kayle'],
  },
  {
    id: 'lore_old_partners',
    name: 'Old Partners',
    description: 'Twisted Fate + Graves — CPS +10%',
    type: 'lore_bond',
    icon: '🃏',
    color: '#c0a030',
    tier: 'silver',
    effects: [{ type: 'cps', multiplier: 1.1 }] as SynergyEffect[],
    pair: ['Twisted Fate', 'Graves'],
  },
  {
    id: 'lore_bilgewater',
    name: 'Bilgewater Rivals',
    description: 'Miss Fortune + Gangplank — DPS +12%',
    type: 'lore_bond',
    icon: '☠️',
    color: '#c08030',
    tier: 'silver',
    effects: [{ type: 'dps', multiplier: 1.12 }] as SynergyEffect[],
    pair: ['Miss Fortune', 'Gangplank'],
  },
  {
    id: 'lore_eternal_rivals',
    name: 'Eternal Rivals',
    description: 'Darius + Garen — Macht +10%',
    type: 'lore_bond',
    icon: '⚔️',
    color: '#e04040',
    tier: 'silver',
    effects: [{ type: 'power', multiplier: 1.1 }] as SynergyEffect[],
    pair: ['Darius', 'Garen'],
  },
  {
    id: 'lore_ocean_deep',
    name: 'Ocean Deep',
    description: 'Nami + Nautilus — CPS +10%',
    type: 'lore_bond',
    icon: '🐟',
    color: '#3090e8',
    tier: 'silver',
    effects: [{ type: 'cps', multiplier: 1.1 }] as SynergyEffect[],
    pair: ['Nami', 'Nautilus'],
  },
  {
    id: 'lore_hagakure',
    name: 'Hagakure Bond',
    description: 'Ahri + Sett — Macht +10%',
    type: 'lore_bond',
    icon: '🦊',
    color: '#e060a0',
    tier: 'silver',
    effects: [{ type: 'power', multiplier: 1.1 }] as SynergyEffect[],
    pair: ['Ahri', 'Sett'],
  },
  {
    id: 'lore_chaos_engineers',
    name: 'Chaos Engineers',
    description: 'Ziggs + Jinx — DPS +12%',
    type: 'lore_bond',
    icon: '💣',
    color: '#e0a020',
    tier: 'silver',
    effects: [{ type: 'dps', multiplier: 1.12 }] as SynergyEffect[],
    pair: ['Ziggs', 'Jinx'],
  },
]

export const FULL_ORBIT_PER_ROLE: SynergyDefinition = {
  id: 'full_orbit_per_role',
  name: 'Voller Orbit',
  description: 'Alle 3 Slots im Orbit besetzt — CPS +8%',
  type: 'full_orbit',
  icon: '🌟',
  color: '#e8c040',
  tier: 'silver',
  effects: [{ type: 'cps', multiplier: 1.08 }] as SynergyEffect[],
}

export const FULL_CONSTELLATION: SynergyDefinition = {
  id: 'full_constellation',
  name: 'Complete Constellation',
  description: 'Alle 15 Champion-Slots besetzt — CPS +25%, Macht +25%',
  type: 'full_orbit',
  icon: '💫',
  color: '#ffd700',
  tier: 'gold',
  effects: [
    { type: 'cps', multiplier: 1.25 },
    { type: 'power', multiplier: 1.25 },
  ] as SynergyEffect[],
}

export const RARITY_LEGENDARY: SynergyDefinition = {
  id: 'rarity_legendary_assembly',
  name: 'Legendary Assembly',
  description: '3+ seltene Champions im Orbit — Macht +15%',
  type: 'rarity',
  icon: '💎',
  color: '#9b48cc',
  tier: 'gold',
  effects: [{ type: 'power', multiplier: 1.15 }] as SynergyEffect[],
}

export const RARITY_STAR_FORGED: SynergyDefinition = {
  id: 'rarity_star_forged',
  name: 'Star-Forged',
  description: '5+ seltene Champions im Orbit — Macht +25%',
  type: 'rarity',
  icon: '⭐',
  color: '#ffd700',
  tier: 'gold',
  effects: [{ type: 'power', multiplier: 1.25 }] as SynergyEffect[],
}
