function _generateBossNames(): string[] {
  const prefixes: string[] = [
    // Cosmic / Astronomical (28)
    'Void',
    'Nebula',
    'Quasar',
    'Stellar',
    'Pulsar',
    'Galactic',
    'Solar',
    'Astral',
    'Cosmic',
    'Dark Matter',
    'Event Horizon',
    'Supernova',
    'Nova',
    'Photon',
    'Plasma',
    'Neutron Star',
    'Ion Storm',
    'Aurora',
    'Comet',
    'Meteor',
    'Eclipse',
    'Celestial',
    'Orbital',
    'Zenith',
    'Stardust',
    'Starfall',
    'Moonfire',
    'Solaris',
    // Mythological / Epic (22)
    'Kronos',
    'Fenrir',
    'Leviathan',
    'Chimera',
    'Typhon',
    'Ragnarok',
    'Quetzalcoatl',
    'Anubis',
    'Osiris',
    'Moloch',
    'Gorgoroth',
    'Olympian',
    'Titan',
    'Colossus',
    'Goliath',
    'Behemoth',
    'Juggernaut',
    'Poseidon',
    'Zeus',
    'Ares',
    'Hades',
    'Enki',
    // Exotic / Alien (22)
    "Xar'veth",
    "Zh'kraan",
    "Vex'al",
    "Thul'nar",
    "Kyr'ax",
    "Soth'is",
    "Grax'ul",
    "Neth'ar",
    "Vor'kaan",
    "Zel'thar",
    "Ul'vaash",
    "Drax'eel",
    "Myr'och",
    "Pyr'ath",
    "Ryv'zel",
    "Cyx'nar",
    "Bael'thos",
    "Khaaz'ul",
    "Vrix'aal",
    "Thyx'nor",
    "Ghal'zyr",
    "Xoth'eel",
    // Elemental / Physical (10)
    'Entropy',
    'Antimatter',
    'Graviton',
    'Singularity',
    'Quantum',
    'Plasma Storm',
    'Dark Energy',
    'Null Field',
    'Tachyon',
    'Void Particle',
    // "The ..." names — ~20 % starts with "The" (20)
    'The Undying',
    'The Eternal',
    'The Infinite',
    'The Ancient',
    'The Sovereign',
    'The Void',
    'The Cosmic',
    'The Abyssal',
    'The Forsaken',
    'The Omnipotent',
    'The Galactic',
    'The Celestial',
    'The Primordial',
    'The Supreme',
    'The Boundless',
    'The Nullborn',
    'The Starborn',
    'The Deathless',
    'The Omega',
    'The Apocalyptic',
    // Extra cosmic / compound (10)
    'Binary Star',
    'Black Hole',
    'Magnetar',
    'Accretion',
    'Interstellar',
    'Hypernova',
    'Dark Flux',
    'Void Storm',
    'Nebular',
    'Axiom',
  ]

  const suffixes: string[] = [
    // Role / Title (20)
    'Devourer',
    'Destroyer',
    'Annihilator',
    'Obliterator',
    'Ravager',
    'Predator',
    'Hunter',
    'Stalker',
    'Tyrant',
    'Sovereign',
    'Emperor',
    'Warlord',
    'Conqueror',
    'Dominator',
    'Archon',
    'Arbiter',
    'Executor',
    'Exterminator',
    'Devastator',
    'Eradicator',
    // Cosmic / Horror (20)
    'Leviathan',
    'Colossus',
    'Goliath',
    'Juggernaut',
    'Horror',
    'Terror',
    'Nightmare',
    'Abomination',
    'Monstrosity',
    'Fiend',
    'Reaper',
    'Wraith',
    'Specter',
    'Phantom',
    'Revenant',
    'Shade',
    'Harbinger',
    'Titan',
    'Giant',
    'Dragon',
    // Epic / Destructive noun (20)
    'Wyrm',
    'Beast',
    'Demon',
    'Scourge',
    'Plague',
    'Blight',
    'Curse',
    'Malice',
    'Fury',
    'Wrath',
    'Chaos',
    'Null',
    'Cataclysm',
    'Apocalypse',
    'Armageddon',
    'Oblivion',
    'Nemesis',
    'Doom',
    'Entropy',
    'Ruin',
    // Cosmic forces / events (20)
    'Collapse',
    'Decay',
    'Corruption',
    'Madness',
    'Despair',
    'Desolation',
    'Extinction',
    'Devastation',
    'Decimation',
    'Manifestation',
    'Incarnation',
    'Avatar',
    'Entity',
    'Presence',
    'Nexus',
    'Vortex',
    'Core',
    'Soul',
    'Force',
    'Abyss',
    // Compound / action (20)
    'Bringer',
    'Walker',
    'Weaver',
    'Forger',
    'Breaker',
    'Fallen',
    'Risen',
    'Forsaken',
    'Ascendant',
    'Overlord',
    'Purger',
    'Subjugator',
    'Oppressor',
    'Sentinel',
    'Herald',
    'Vanguard',
    'Nullbringer',
    'Voidwalker',
    'Starkiller',
    'Worldender',
    // Abstract power (20)
    'Prime',
    'Omega',
    'Alpha',
    'Apex',
    'Pinnacle',
    'Ascension',
    'Awakened',
    'Risen One',
    'Undying',
    'Eternal',
    'Remnant',
    'Omen',
    'Specter Prime',
    'Void Spawn',
    'Null Shard',
    'Star Fiend',
    'Dark Servant',
    'Chaos Spawn',
    'Abyss Walker',
    'Death Mark',
  ]

  const names: string[] = []
  for (const p of prefixes) {
    for (const s of suffixes) {
      names.push(`${p} ${s}`)
    }
  }
  return names.slice(0, 10_000)
}

export const BOSS_NAMES: string[] = _generateBossNames()
