import { defineStore } from 'pinia'
import { ref } from 'vue'
import type { Mission } from '../types'

const MISSIONS: Mission[] = [
  {
    id: 'first_notes',
    name: 'First Notes',
    icon: '🎵',
    description: 'Earn a total of 500 Chimes and begin your journey.',
    condition: { type: 'totalChimes', target: 500 },
    rewardUpgrade: {
      id: 'reward_silver_strings',
      name: 'Silver Strings',
      description: 'Your strings shimmer with silver. +5% to all CpS sources.',
      icon: '🎸',
      cost: 0,
      effect: { type: 'cpsMultiplier', value: 1.05 },
    },
    claimed: false,
  },
  {
    id: 'street_performer',
    name: 'Street Performer',
    icon: '🎤',
    description: 'Click a total of 100 times and train your fingers.',
    condition: { type: 'totalClicks', target: 100 },
    rewardUpgrade: {
      id: 'reward_nimble_fingers',
      name: 'Nimble Fingers',
      description: 'Years of practice pay off. +15% CpC globally.',
      icon: '✋',
      cost: 0,
      effect: { type: 'cpcMultiplier', value: 1.15 },
    },
    claimed: false,
  },
  {
    id: 'building_collector',
    name: 'Building Master',
    icon: '🏛️',
    description: 'Own 3 different building types simultaneously.',
    condition: { type: 'ownedBuildingTypes', target: 3 },
    rewardUpgrade: {
      id: 'reward_harmonic_architecture',
      name: 'Architectural Harmony',
      description: 'Each building amplifies the others. +10% CpS.',
      icon: '🏗️',
      cost: 0,
      effect: { type: 'cpsMultiplier', value: 1.1 },
    },
    claimed: false,
  },
  {
    id: 'planet_saver_1',
    name: 'Planet Rescuer I',
    icon: '🌍',
    description: 'Bring any building to Level 10.',
    condition: { type: 'singleBuildingLevel', target: 10 },
    rewardUpgrade: {
      id: 'reward_planet_song_1',
      name: 'Planet Song Vol. I',
      description: 'Your melody saves the first planet. +20% CpS.',
      icon: '🌐',
      cost: 0,
      effect: { type: 'cpsMultiplier', value: 1.2 },
    },
    claimed: false,
  },
  {
    id: 'galactic_bard',
    name: 'Galactic Bard',
    icon: '🌌',
    description: 'Earn a total of 50,000 Chimes.',
    condition: { type: 'totalChimes', target: 50_000 },
    rewardUpgrade: {
      id: 'reward_cosmic_frequency',
      name: 'Cosmic Frequency',
      description: 'Your sound travels through the galaxy. +10% CpC globally.',
      icon: '📡',
      cost: 0,
      effect: { type: 'cpcMultiplier', value: 1.1 },
    },
    claimed: false,
  },
  {
    id: 'building_master',
    name: 'Master of Works',
    icon: '⚙️',
    description: 'Invest a total of 50 levels into buildings.',
    condition: { type: 'totalBuildingLevels', target: 50 },
    rewardUpgrade: {
      id: 'reward_synergy_boost',
      name: 'Synergy Master',
      description: 'All buildings work in perfect harmony. +25% CpS.',
      icon: '⚡',
      cost: 0,
      effect: { type: 'cpsMultiplier', value: 1.25 },
    },
    claimed: false,
  },
  {
    id: 'ten_worlds',
    name: 'Ten Worlds',
    icon: '/img/planet.png',
    description: 'Rescue all 10 planets — own all 10 building types.',
    condition: { type: 'ownedBuildingTypes', target: 10 },
    rewardUpgrade: {
      id: 'reward_star_concert',
      name: 'Star Concert',
      description: 'The concert of the entire galaxy. +30% CpS.',
      icon: '⭐',
      cost: 0,
      effect: { type: 'cpsMultiplier', value: 1.3 },
    },
    claimed: false,
  },
  {
    id: 'click_legend',
    name: 'Click Legend',
    icon: '👆',
    description: 'Click a total of 1,000 times.',
    condition: { type: 'totalClicks', target: 1_000 },
    rewardUpgrade: {
      id: 'reward_virtuoso_click',
      name: 'Virtuoso Click',
      description: 'A master of finger technique. +50% CpC globally.',
      icon: '🎯',
      cost: 0,
      effect: { type: 'cpcMultiplier', value: 1.5 },
    },
    claimed: false,
  },
  {
    id: 'galaxy_legend',
    name: 'Galaxy Legend',
    icon: '🏆',
    description: 'Earn a total of 1,000,000 Chimes.',
    condition: { type: 'totalChimes', target: 1_000_000 },
    rewardUpgrade: {
      id: 'reward_legendary_symphony',
      name: 'Legendary Symphony',
      description: 'The eternal symphony of infinity. +100% CpS.',
      icon: '👑',
      cost: 0,
      effect: { type: 'cpsMultiplier', value: 2.0 },
    },
    claimed: false,
  },
]

export const useMissionStore = defineStore('mission', () => {
  const missions = ref<Mission[]>(JSON.parse(JSON.stringify(MISSIONS)))

  return { missions }
})
